### PR TITLE
Bug 421

### PR DESCRIPTION
**Pull request by wlbragg**
Maybe someone that knows blender and texturing can look at the settings for the trim wheel and the other washed out buttons and knobs.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg okay, so the radios and flap label are perfect, thanks for fixing this! As for the whashed out objects, the ones I spotted are: trim wheel, cage knob of attitude indicator and instrument lightning knob. Should we wait for these to be fixed before merging this PR?

**Comment by Juanvvc** [comment]
I'm sorry for being so disconnected of this development. What do you mean by "washed out"?

Some of the objects you mentioned do not have any texture, only a plain color. Plain colors behave differently than textures. In my experience, the best option for any model to behave consistently in FlightGear is having everything textured or everything using only plain colors.

I guess we must texture these objects that currently use plain colors.

**Comment by gilbertohasnofb** [comment]
@Juanvvc 
>  What do you mean by "washed out"?

I mean that under the flashlight some of those objects become white. See the trim wheel becoming white in this image: https://github.com/Juanvvc/c172p-detailed/issues/421#issuecomment-121712521

> I guess we must texture the few objects that still use plain colors.

Yep, that seems to be the case. Should I add a couple of new textures to the `panel_parts.png`?

**Comment by wlbragg** [comment]
>the objects you mentioned do not have any texture, only a plain color

That make sense.

>Should I add a couple of new textures to the panel_parts.png

Yes, lets try that.

**Comment by gilbertohasnofb** [comment]
@wlbragg so I pushed the new textures. Here is where they are located:

untitled

And by "vent tube" what I meant is the side of the thermometer which is located in the end of the vent tube. See:

fgfs-screen-001

Also, both vent tubes seem to float on nothing because the wing part where they are installed isn't illuminated by the flashlight. This is a minor problem, but if it can be fixed it would be wonderful, see:

fgfs-screen-002

Let me know how the textures work for you, okay?

**Comment by wlbragg** [comment]
OK, I may be slow but I am tickled pink to get even this far with a texture. There is an issue though that i really don't know the answer to. Maybe a blender guru can comment on it for me.
The AI was using and RGB texture for the existing objects, we added a knob texture to panel_parts.png . I could not figure out how to tie to the panel_parts in /Models it wants the texture in the local AI sub-folder, 
Here is what it looks like though as it is now.
aiknob

**Comment by wlbragg** [comment]
@gilbertohasnofb, the AI cage knob, where is that suppose to be placed, behind the knob. I only ask because there is no object located behind the knob. Or am I suppose to try to apply that to the actual knob and I am not recognizing it in its 3d world?

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry, I wrote cage knob but I meant the AI offset knob, see:

image

I see that you actually already applied some texture to it (seems to me to be the instrument lightning), but I'd rather have the knob I marked as AI cage knob in the comment before, since the image I used as reference looked rather that way. Could you please change it?

**Comment by gilbertohasnofb** [comment]
@wlbragg 
> Maybe a blender guru can comment on it for me.

@Juanvvc or @dg-505, could you hep us out with this issue?

**Comment by wlbragg** [comment]
OK, I see where I went wrong.
What I am still unclear about is the "AI offset knob" you supplied looks like the face plate behind and surrounding the knob, what about the knob itself? Or am I not seeing it correctly?

**Comment by gilbertohasnofb** [comment]
@wlbragg Now it's me whom is not understanding :wink: 

> looks like the face plate behind and surrounding the knob, what about the knob itself?

Well, it seems that both the plate around the whole instrument as well as the knob are completely untexturized, so indeed it would be great to add textures to both of them. What you can do is to use the correct knob texture for the knob, and use the black centre of the knob texture for the plate (so it will be black and texturized). Does it make sense?

**Comment by wlbragg** [comment]
No it doesn't make sense to me :cry: 

>use the correct knob texture for the knob, 
Which one is that?

>and use the black center of the knob texture for the plate
Again, which one is that?

And what of the mislabeled AI Cage Knob" texture, is that not going to be used now?

**Comment by gilbertohasnofb** [comment]
@wlbragg look, sorry for the confusing, I will upload the image again:

panel_parts

So:

- use the instrument illumination texture only for the instrument illumination knob (currently you are using it for the AI offset knob)
- trim and vent tube should be clear, right?
- the AI offset knob is the one with chromatic surrounding and black centre; when the correct texture is applied it should look the same as the knob in the altimeter 
- you can "cheat" and use the black centre of the AI offset knob texture (marked as the dotted square in the image above) and use this black texture for the plate surrounding the AI (which currently looks dark grey and is untexturized).

Let me know what you think!

**Comment by gilbertohasnofb** [comment]
@wlbragg I have edited the comment above with some new information and made one more commit to this PR

**Comment by wlbragg** [comment]
Sounds like a plan, I think were on the same page now! :smile:

**Comment by wlbragg** [comment]
Here is the rgb version. Note the square plate was not showing before and is not showing now. I'm not sure it is suppose to.
Also notice the nut I pointed to with the yellow arrow, I thought I had all those accounted for in the flashlight effect, anyone know what object names those are?
knob1

Does this knob below below have a problem?
knob2

**Comment by wlbragg** [comment]
Never mind, i see the nut objects are called "bolts". I'll take care of that also.

**Comment by wlbragg** [comment]
OK, bolts are effected! :smile:
bolts

**Comment by wlbragg** [comment]
Here is the Instrument Light knob under the different lighting conditions. The last one is the flashlight.
inst

**Comment by wlbragg** [comment]
I hope this thread isn't to graphic intensive.
Here is the trim wheel. This one was a little tougher. It is a big complex wheel so I cheated and mapped the whole thing to the black leather looking texture at the bottom of panel_parts.png. I guess I could have scaled it even smaller and mapped it to the black square you made but don't know that it would look any different. Let me know what you think about all these before I push.
sml
lrg

**Comment by wlbragg** [comment]
Here it is with the specular cranked up (top natural light, bottom flashlight)
spec
specf

**Comment by wlbragg** [comment]
I went ahead and pushed all the changes so you all can test it and see for yourself what they look like. The vent tubes are the only things I didn't do because they are already textured and I think maybe either darkening up (contrast) the existing texture or changing the material lighting settings might help. As far as the wing structure that supports the vent tubes, It can be illuminated with the flashlight but causes other trouble then. the biggest problem is that the entire wing is then illuminated in external vies if you have the flashlight on. But from the inside it is kind of cool to shine the flashlight n the wing.

**Comment by gilbertohasnofb** [comment]
@wlbragg
> Does this knob below below have a problem? [about the heading indicator]

I also noticed this problem some days ago, never saw it before. Would you be able to fix it? Should I open a new Issue for it or can you do it in this PR?

About your work, everything is looking really good now! The AI looks much better, the same for the instrument light knob. As for the trim wheel, it looks fine to me even though it's a bit of a hack to use the panel's leather texture :smile: I will test it all myself today but I can already see it is looking very good!

> The biggest problem is that the entire wing is then illuminated in external view if you have the flashlight on. But from the inside it is kind of cool to shine the flashlight on the wing.

Can't we disable the flashlight using the following conditional (or something similar):

    <condition>
        <or>
            <equals>
                <property>sim/current-view/name</property>
                <value>Cockpit View</value>
            </equals>
            <equals>
                <property>sim/current-view/name</property>
                <value>Cockpit Right Seat View</value>
            </equals>
            <equals>
                <property>sim/current-view/name</property>
                <value>Left Passenger Seat View</value>
            </equals>
            <equals>
                <property>sim/current-view/name</property>
                <value>Right Passenger Seat View</value>
            </equals>                
        </or>
    </condition>
    
This way, the flashlight would show up only in the interior views. What do you think?

**Comment by gilbertohasnofb** [comment]
So, before merging this PR we need to:

* [ ] fix this issue with the flashlight in the wing on the outside views
* [ ] fix the vent tubes
* [ ] fix the horizontal indicator knob

@wlbragg please feel free to tick the issues above when they are solved!

**Comment by wkitty42** [comment]
FWIW: "real" flashlights (original with the bulb, not today's poor LED ones) so actually light other things through windows... having the wing light up when shone on with the flashlight is natural... it just depends on how much of the wing is lit by the flashlight's light cone... most of the LED flashlights i've used are too diffuse to be of any real good lighting things at a distance of more than a few feet...

**Comment by wlbragg** [comment]
>fix the horizontal indicator knob

I guess I missed this one.

>fix this issue with the flashlight in the wing on the outside views

I'm not sure about this one. Right now it is not illuminate, if we do illuminate it then it will illuminate the entire wing when viewed from the outside, I'm pretty sure you can't do a conditional; on an effect.. But even if you could, it will also stop the effect of seeing the interior cockpit of the aircraft from being illuminated when viewed from the outside, which is kind of cool as it is now (I noticed that side effect and really liked it).
If this part of the wing that holds the vent tubes is really an eye sore if not illuminated, there is a third option.
Please look at these and comment.
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-002.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-002.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-006.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-007.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-008.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-009.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-010.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-011.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-012.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-013.png
https://dl.dropboxusercontent.com/u/63093453/fg/c172p/flash/fgfs-screen-014.png

**Comment by gilbertohasnofb** [comment]
@wlbragg 

>  I'm pretty sure you can't do a conditional; on an effect..

So forget the conditional and apply the effect on the wing! This means that we may have some unrealistic light source when viewing from the outside, but the most important thing IMO is that the cockpit is realistic. Also, if that bothers someone they can just turn off the flashlight when viewing the plane from outside, no big deal as far as I can see. Your screen shots above are looking good and I love the flashlight on the wing just behind the vent tube, it looks much more realistic right now!

>> fix the horizontal indicator knob

> I guess I missed this one.

I really don't remember when this was introduced, but I am quite sure this knob was fine before (else I would have noticed while working on it). Nevertheless, it would be great to fix it :smile: 

Last thing: could you please post an image of how the right side vent tube (the one with the thermometer on the end) is looking like with the flashlight? Right now I can't use FG to check it out myself, but later today I will make a test with these modifications.

**Comment by wlbragg** [comment]
>So forget the conditional and apply the effect on the wing! This means that we may have some unrealistic light source when viewing from the outside

These pictures represent a third option. I separated the mesh that the vent tubes attach to from the rest of the wing, They are in effect a separate object now that I can apply the effect to. Notice the bottom of the wing is not lit up, just the face the tube is attached to. I included a bunch of different lighting conditions to show what that does to the "NEW" separated meshes because I am not sure what all the bumpspec effect does to to the wing and those two new separated pieces can't have both the bumpspec effect and the internal or flashlight effect.

**Comment by wlbragg** [comment]
Because the new faces that the tubes attach to are inheriting internal effect they also have the internal shadow applied to them which adds some interesting effect. I could separate them out away from "internal effects" and just give them the "flashlight effect" if needed, but I think it is OK the way it is. We need eyes on this to test multiple lighting conditions and male sure it is acceptable.

**Comment by wlbragg** [comment]
>fix the vent tubes

>I also missed this (referring to the black part around the thermometer)

That's why it got missed, I can't find it and don't know where it is or what it is called?

**Comment by gilbertohasnofb** [comment]
> I think [the effect on the tube vents and wings] is OK the way it is. We need eyes on this to test multiple lighting conditions and make sure it is acceptable.

Sure, it's your call. have you already committed these last changes? I will test this in some minutes.

>> I also missed this (referring to the black part around the thermometer)

> That's why it got missed, I can't find it and don't know where it is or what it is called?

I will try to find it out right now.

**Comment by gilbertohasnofb** [comment]
Found it, it's `Models/Interior/Panel/Instruments/oat.ac`. See the lines starting at 915 on `Models/c172p.xml`.

**Comment by wlbragg** [comment]
No I haven't commited it yet, I'm trying to find out what happened to the horizontal indicator knob.

Oh, thank you.

**Comment by wlbragg** [comment]
You want me to commit what I have now so you can test?

**Comment by gilbertohasnofb** [comment]
> You want me to commit what I have now so you can test?

Do you plan to fix the thermometer straight away? If so I can wait, but if you plan to work on it only later then I'd be happy to test it right now.

**Comment by wlbragg** [comment]
Yes, I'll take a look at it right now.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
oat

**Comment by gilbertohasnofb** [comment]
Fantastic! So now I think we only need to fix that Heading Indicator knob texture and that should be it for this PR! I checked the texture file and it's perfectly fine so the problem is with the UV mapping indeed.

**Comment by wlbragg** [comment]
>the texture file and it's perfectly fine so the problem is with the UV mapping indeed.

Yeah and so is the UV map, this is a very strange bug.

**Comment by gilbertohasnofb** [comment]
>> the texture file and it's perfectly fine so the problem is with the UV mapping indeed.

> Yeah and so is the UV map, this is a very strange bug.

That's bizarre... I am really convinced this was introduced some short time ago, but what else could have caused it than a texture modification (which I checked and is not happening) or a UV mapping modification (which you now say it's also not happening)?

**Comment by wlbragg** [comment]
OK, I brought the knob.rgb into gimp and re-saved it and it fixed it. I did this after I got desperate because my FG was crashing during loading and the only thing that I could attribute it to was that knob.rgb file.

**Comment by wlbragg** [comment]
So let me push and lets test, test, test...

**Comment by gilbertohasnofb** [comment]
> OK, I brought the knob.rgb into gimp and re-saved it and it fixed it. I did this after I got desperate because my FG was crashing during loading and the only thing that I could attribute it to was that knob.rgb file.

That's really bizarre, I haven't touched that texture in ages! But I am glad the problem is solved :smile: 

> let me push and lets test, test, test...

Yep!

**Comment by wlbragg** [comment]
I'm trying to push, my internet is CRAWLING right now. We've been experiencing a slow connection for the last hour or more.

**Comment by wlbragg** [comment]
OK, pushed, I hope that went through OK. It took a really long time to upload.

**Comment by gilbertohasnofb** [comment]
@wlbragg No worries, I will be online for the next hours so once this is done I will do some testing. And thanks a lot for having a look on all these problems, I think this PR will greatly enhance our plane! :smile: 

So just that we don't forget, what we need to test is this:
- if knob texture of the horizontal indicator is fixed
- if the air vents and thermometers all have working textures under flashlight
- if trim, instrument light knob, AI plate and knob all get normal colours under flashlight (instead of that horrible white)
- If the part of the wing where the vents are mounted get illuminated by the flashlight
- test flashlight under different light conditions to see how it behaves
- double check if radios and flap are now behaving normally under flashlight

(if I forgot something, please feel free to edit this message and add it here)

**Comment by gilbertohasnofb** [comment]
> OK, pushed, I hope that went through OK. It took a really long time to upload.

I can't see any new commit to this PR, are you sure it worked out well or that you pushed it to the correct branch?

**Comment by wlbragg** [comment]
Let me try this again.

**Comment by wlbragg** [comment]
It's there!

**Comment by gilbertohasnofb** [comment]
@wlbragg I pulled and it seems to be working, but somehow that commit was not added to this PR and I don't know why. Where is @onox when we need him?

I tested and everything seems to be working fine, but I found one problem and one thing that bother me a bit:

- the problem is that for some reason the texture in the heading bug of the HI is now inverted! Have you modified the UV map? See how the knob in the left side of the HI is normal but the one on the right is inverted. 
- the trim wheel does not look very nice with the leather texture in my opinion. I'd rather have that almost-black patch applied to it than the dashboard texture. What do you think?

**Comment by wlbragg** [comment]
By the way, I remembered how to point to textures in a different path than local.
It is using the 
~~~xml
<texture-path>Aircraft/c172p/Models</texture-path>
~~~

**Comment by gilbertohasnofb** [comment]
Your commit is here, it's just not shown among our conversation here for some unknown reason. But if you check https://github.com/Juanvvc/c172p-detailed/pull/425/commits then it's there, so no worries.

>  how to point to textures in a different path than local

Great! Next time we need then we won't duplicate all textures :smile:

**Comment by wlbragg** [comment]
>Your commit is here, it's just not shown among our conversation here for some unknown reason.
Yeah, I see that. This whole venture is bizarre...

>the problem is that for some reason the texture in the heading bug of the HI is now inverted! Have you modified the UV map? See how the knob in the left side of the HI is normal but the one on the right is inverted.

I also saw that but figured it was because I had turned it and it saved it there. No, I didn't have to do anything to the texture.

>the trim wheel does not look very nice with the leather texture in my opinion. I'd rather have that almost-black patch applied to it than the dashboard texture. What do you think?

Yes, I was going to remap it to the black texture you created and for got to, I'll do that now.

**Comment by gilbertohasnofb** [comment]
> I also saw that but figured it was because I had turned it and it saved it there. No, I didn't have to do anything to the UV.

So do you think you can check this out as well while you check the trim wheel?

Thanks a lot, we are almost there!

**Comment by wlbragg** [comment]
Yeah, let me look at that. I pushed the trim wheel.

**Comment by gilbertohasnofb** [comment]
> I pushed the trim wheel.

I will check it right now.

**Comment by wlbragg** [comment]
OH, I see what your talking about with the knob, it is mirrored somehow? I'm looking at it but not sure I can figure this one out.

**Comment by gilbertohasnofb** [comment]
Well, when I first worked on it the original texture was mirrored so I kept it that way. But the result was that both knobs had the text in the correct position, and after your commit the heading bug knob is inverted somehow.

I tested the trim wheel and I think it looks better. But I found one more thing: I believe you forgot to apply the texture `black.rgb` to the AI plate, haven't you?

**Comment by wlbragg** [comment]
>I believe you forgot to apply the texture black.rgb to the AI plate, haven't you? 

I did apply the blake texture to the AI plate, but I am unclear as to that plate even being visible. Can you post a picture with an arrow pointing to it?

Also, unfortunately I am out of time until tonight, so leave any concerns and I will work on it tonight.

**Comment by wlbragg** [comment]
I may revert back to the hi knob that is in history and start back from there, but it will be a little later tonight.

**Comment by gilbertohasnofb** [comment]
> I did apply the blake texture to the AI plate, but I am unclear as to that plate even being visible. Can you post a picture with an arrow pointing to it?

Here it is, it's the object marked in red:

fgfs-screen-001

> Also, unfortunately I am out of time until tonight, so leave any concerns and I will work on it tonight.

No worries, we continue tomorrow or some other time :smile: 

> I may revert back to the hi knob that is in history and start back from there, but it will be a little later tonight.

That would be all right, but that would also revert some good modifications, right? Or did you commit involved only that knob? Just let's be careful not to undo some good work here

**Comment by wlbragg** [comment]
>That would be all right, but that would also revert some good modifications, right

No, I meant that I will overwrite the problem with an older version and go from there if I have to.

OK, now I understand the plate issue and will also take care of it. I noticed that, but didn't understand that is what you were talking about.

**Comment by gilbertohasnofb** [comment]
> I meant that I will overwrite the problem with an older version and go from there if I have to.

Sounds good.

> OK, now I understand the plate issue and will also take care of it. I noticed that, but didn't understand that is what you were talking about.

Ok then! Once you apply that texture I will test it again.

**Comment by wlbragg** [comment]
OK, was able to sneak back in and get this little bit done. Test and I will deal with the HI knob later tonight.

**Comment by wlbragg** [comment]
ai1
ai2

**Comment by gilbertohasnofb** [comment]
Ok, so the plate is done! I actually made the `black.rgb` a bit brighter and I think it looks better that way. So tomorrow let me know when you have a look on the HI knob so we can test and close this PR.

But I also found a new strange bug which seems related to the shadows, and I am afraid it seems to have been introduced in this branch here. Have a look: https://youtu.be/MNkuBGVcNq8 (tell me if you think this isn't related to our branch here and so I should open a separate Issue for this)

**Comment by wlbragg** [comment]
@gilbertohasnofb, I'm not getting that strange effect at all. We need some others testing this to make sure. Did anything on your system change?

**Comment by wlbragg** [comment]
@gilbertohasnofb, this is everything. I had to re-UV map the HI knob, it was the map that was causing problems. This should be everything and hopefully it is all good. I still can't reproduce your strange youtube MNkuBGVcNq8 issue.

**Comment by wlbragg** [comment]
This is pretty much a record of everything we did.
changes

**Comment by gilbertohasnofb** [comment]
@wlbragg Fantastic work! I will test it thoroughly now and I will merge it then.

> I'm not getting that strange effect at all. We need some others testing this to make sure. Did anything on your system change?

Not as far as I know. And I am sure I never saw that before. I will try to see if I can reproduce it with the master branch before merging this and try to narrow down what is happening.

**Comment by gilbertohasnofb** [comment]
@wlbragg Okay, so I tested and everything seems to be fine, thank you so much for your efforts to fix this! I am merging it right now :smile: 

As for that bug in the video, I simply couldn't reproduce it. I am afraid it could have been due to a very specific combination of weather and lightning. I will open an issue for it anyway just in case I or anyone else find out how to reproduce it. See: https://github.com/Juanvvc/c172p-detailed/issues/428

**Pull request merged**
