### PR TITLE
Enable the new splash screens

### PR DESCRIPTION
**Pull request by onox**
Enables the new splash screens, randomly chosen when starting FlightGear.

Latest flightgear git version (e3c8ecc committed on 1st of June) required.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
When this gets accepted, we should also delete the splash.png and leave only the numbered ones.

**Comment by onox** [comment]
`splash.png` is deleted by this PR.

**Comment by gilbertohasnofb** [comment]
My bad, I didn't realize there were 2 file changes.

**Comment by onox** [comment]
Note that you can actually have as many splash screens as you want, it's not limited to just 4. You can merge this PR if you want.

**Comment by gilbertohasnofb** [comment]
> Note that you can actually have as many splash screens as you want

Sure, I understand that.

> You can merge this PR if you want.

Done.

**Comment by onox** [comment]
Thanks :smile: Now I can sleep :wink: Have a good night :sleeping:

**Comment by gilbertohasnofb** [comment]
Good night, onox! Soon is my time as well :zzz:

**Pull request merged**
