### PR TITLE
C172p detailed standalone

### PR DESCRIPTION
**Pull request by wlbragg**
Are you sure we're going to get what we want this way?
It will put all the new additions into master and also change all the paths in master to look like the paths in "standalone"?

### CODE REVIEW

**Comment by wlbragg** [comment]
Also I just did another "find in files" in np++. I see a couple /c172p/ paths I may have missed.
Note most of these are properties that are correct.

Search "/c172p/" (51 hits in 16 files)
  F:\FlightGear\Custom Aircrafts\c172p-detailed\c172p-detailed-set.xml (2 hits)
	Line 204:         <int n="1" alias="/sim/model/c172p/lighting/beacon-top/state"/>
	Line 205:         <int n="2" alias="/sim/model/c172p/lighting/strobes/state"/>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\gui\dialogs\aircraft-dialog.xml (16 hits)
	Line 28:                 setprop("/sim/model/c172p/bushkit_flag_0",0);
	Line 31:                 if (p == 0) { setprop("/sim/model/c172p/bushkit_flag_0",1); }
	Line 32:                 if (p == 1) { setprop("/sim/model/c172p/bushkit_flag_1",1); }
	Line 33:                 if (p == 2) { setprop("/sim/model/c172p/bushkit_flag_2",1); }
	Line 166:                     <property>sim/model/c172p/bushkit_flag_0</property>
	Line 175:                             setprop("sim/model/c172p/bushkit_flag_0",1);
	Line 176:                             setprop("sim/model/c172p/bushkit_flag_1",0);
	Line 177:                             setprop("sim/model/c172p/bushkit_flag_2",0);
	Line 185:                     <property>sim/model/c172p/bushkit_flag_1</property>
	Line 194:                             setprop("sim/model/c172p/bushkit_flag_0",0);
	Line 195:                             setprop("sim/model/c172p/bushkit_flag_1",1);
	Line 196:                             setprop("sim/model/c172p/bushkit_flag_2",0);
	Line 204:                     <property>sim/model/c172p/bushkit_flag_2</property>
	Line 213:                             setprop("sim/model/c172p/bushkit_flag_0",0);
	Line 214:                             setprop("sim/model/c172p/bushkit_flag_1",0);
	Line 215:                             setprop("sim/model/c172p/bushkit_flag_2",1);
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Instruments\dme\dme.xml (1 hit)
	Line 14:       <path>Aircraft/c172p/Instruments/dme/ki266.xml</path>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\c172p-detailed.blend (4 hits)
	Line 833: 
	Line 851: Ä
	Line 858: Ä
	Line 892: Ä
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\c172p-detailed.xml (3 hits)
	Line 4188:      <property>sim/model/c172p/fairing1</property>
	Line 4196:      <property>sim/model/c172p/fairing2</property>
	Line 4204:      <property>sim/model/c172p/fairing3</property>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\c172p-shadow.blend (4 hits)
	Line 621: Ä
	Line 638: Ä
	Line 645: Ä
	Line 757: 
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Effects\bumpspec-fuselage.eff (3 hits)
	Line 4:   <name>Aircraft/c172p/Models/Effects/bumpspec-fuselage</name>
	Line 5:   <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
	Line 8:       <image>Aircraft/c172p/Models/Liveries/fuselage-normal.png</image>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Effects\bumpspec-tail.eff (3 hits)
	Line 4:   <name>Aircraft/c172p/Models/Effects/bumpspec-tail</name>
	Line 5:   <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
	Line 8:       <image>Aircraft/c172p/Models/Liveries/tail-normal.png</image>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Effects\bumpspec-wing.eff (3 hits)
	Line 4:   <name>Aircraft/c172p/Models/Effects/bumpspec-wing</name>
	Line 5:   <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
	Line 8:       <image>Aircraft/c172p/Models/Liveries/wing-normal.png</image>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Effects\glass.eff (1 hit)
	Line 3:     <name>Aircraft/c172p/Models/Effects/glass</name>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Immat\immat.xml (1 hit)
	Line 389: 			<property>sim/model/c172p/immat</property>
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Models\Interior\Panel\Instruments\oat\oat.blend (1 hit)
	Line 2667: 
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Nasal\electrical.nas (2 hits)
	Line 56:     props.globals.getNode("sim/model/c172p/lighting/beacon-top/state", 0).setBoolValue(0);
	Line 57:     props.globals.getNode("sim/model/c172p/lighting/strobes/state", 0).setBoolValue(0);
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Nasal\immat.nas (2 hits)
	Line 22: var immat_dialog = gui.Dialog.new("/sim/gui/dialogs/c172p/status/dialog",
	Line 23: 				  "Aircraft/c172p/Dialogs/immat.xml");
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Nasal\light.nas (2 hits)
	Line 3: aircraft.light.new("sim/model/c172p/lighting/strobes", [0.015, 1.985], strobe_switch);
	Line 8: aircraft.light.new("sim/model/c172p/lighting/beacon-top", [0.10, 0.90], beacon_switch);
  F:\FlightGear\Custom Aircrafts\c172p-detailed\Nasal\physics.nas (3 hits)
	Line 165: 	setprop("/sim/model/c172p/fairing1", 0);
	Line 166: 	setprop("/sim/model/c172p/fairing2", 0);
	Line 167: 	setprop("/sim/model/c172p/fairing3", 0);

**Comment by wlbragg** [comment]
I corrected all the above. I hope.

**Comment by wlbragg** [comment]
Nope, got problems with the bumpspec, working on it now.

**Comment by wlbragg** [comment]
Wow, OK it's fixed. I don't understand why it won't take relative paths but it doesn't like it.

**Comment by onox** [comment]
Have you tested the model over multiplayer? I don't have time to test it until tonight.

**Comment by wlbragg** [comment]
Tested multi-player, generally works fine, except shadows may have a problem and I didn't really put damage through its paces. Still need to do that.

**Comment by onox** [comment]
Did a quick single-player test. Seems to look fine and damage occurs when I crash it.

**Comment by Juanvvc** [comment]
Can we merge this into master? After a visual inspection and some tests, it seems perfectly ok for me.

**Comment by onox** [comment]
:+1:

**Pull request merged**
