### PR TITLE
No preview lights and propeller.

### PR DESCRIPTION
**Pull request by wlbragg**
I don't know how to select a livery for preview in FGRun, but everything else is done.
I think I screwed up the naming on this PR or issue, I'm so confused. At any rate this is the fix for FGRun preview.

### CODE REVIEW

**Comment by wlbragg** [comment]
The livery that is being used is the one that is assigned as textures in Blender. Does anyone know if you can select a "livery" to show in fgrun VS the Blender texture that was assigned?

**Comment by gilbertohasnofb** [comment]
What about the following: why not move the older D-EEQA textures (interior and exterior) to the `Models/Liveries` folder, then move the textures from `Models/Liveries/4X-CHV` to `Models` and then use these to UV map the model to the chosen default 4X-CHV? A bit annoying, I know, but currently we have the D-EEQA textures in a prominent place while it isn't the default texture any longer.

If you all think this is a good idea, I can help with that (except the Blender part). @onox, do you think this is a good idea?

**Comment by onox** [comment]
I guess it's the only option we have.

**Comment by wlbragg** [comment]
If we have to actually redo the UV textures in Blender, no way, at least not me! I think the UV mapping of the entire aircraft is a lot of work just to get the one we want in FGRun..
If we can swap the texture file and Blender keeps the mapping and applies it to the new texture file, then OK.
Let me see if it is that easy, if so then cool!

**Comment by gilbertohasnofb** [comment]
Okay, I am working on it now. Soon I will commit it.

**Comment by gilbertohasnofb** [comment]
@wlbragg I think I have it done now without any need to do anything on Blender, I just reorganized the xml files and their locations. Gimme a second to test then I will push.

**Comment by gilbertohasnofb** [comment]
Done. I also fixed the horrible layout of those livery xml files... :scream:

**Comment by gilbertohasnofb** [comment]
And it works:

screenshot from 2015-11-23 18 54 18

**Comment by wlbragg** [comment]
Great, well gone!

**Comment by gilbertohasnofb** [comment]
You too!

**Pull request merged**
