### PR TITLE
Sparks not influenced by available light.

### LINKED ISSUE #295: Sparks not visible in evening and night
Sparks are visible during the day, but not in the evening and night. Shouldn't they actually appear brighter during the evening and night than during the day?

Noon (visible):
fgfs-screen-065

Dusk (still a little bit visible):
fgfs-screen-066

Evening:
fgfs-screen-068

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #295 

I think this covers it.

### CODE REVIEW

**Comment by onox** [comment]
Someone else should test this; particles are no longer visible on my computer.

**Comment by gilbertohasnofb** [comment]
> Someone else should test this; particles are no longer visible on my computer.

I can't see particles either, I think the particles system got broken some one or two weeks ago but for some reason that commit has not been reverted.

**Comment by legoboyvdlp** [comment]
They are broken; confirmed. Since at least December 22.

**Comment by wlbragg** [comment]
I tested this in as much as I commented out the condition on the front gear and the sparks went from not showing to showing at night. I think we can safely merge it.

**Comment by onox** [comment]
> My FG.exe is prior to sparks being broke.

Keep it that way then :worried:

**Comment by legoboyvdlp** [comment]
Are you Windows, wlbragg? I seem to remember you are.
If so, could you please, please, email the .exe to my email (legoboyvdlpATgmailDOTcom), since the current one has performance issues, which added to lots of planes at the USA TOUR.... not a good idea to fly at 1fps :P

**Comment by wlbragg** [comment]
I can do that. You will need to make sure your fgdata version file is 3.7.0

**Comment by legoboyvdlp** [comment]
Thanks, :)

**Comment by wlbragg** [comment]
@legoboyvdlp, sorry it took so long to do this. I got busy and then forgot and then it was to big to mail. So I zipped it up and threw it in my DropBox.
https://dl.dropboxusercontent.com/u/63093453/fgfs.zip

**Comment by legoboyvdlp** [comment]
No problem; It will help a lot :) thanks

**Comment by legoboyvdlp** [comment]
YAHOO! Smooth flying; ALS; wonderful! Thanks

**Pull request merged**
