### PR TITLE
Pontoon uv fix

### PR DESCRIPTION
**Pull request by wlbragg**
This corrects #507

### CODE REVIEW

**Comment by wlbragg** [comment]
This also should close #314

**Comment by wlbragg** [comment]
I can't believe I did that, I had it just the way I wanted and then I mad a couple last minute changes and totally mucked it up. You should notice the difference now.

**Comment by wlbragg** [comment]
Hey, I am really sorry about all this BS. I just went full circle to end up pretty much back where I started.  This is looking the way it is suppose to so I good with were it's at. Bottom line was there was some material entries in the blend file that needed corrected.

**Comment by wlbragg** [comment]
fix3

**Comment by onox** [comment]
> It will inherit model-combined-transparent and there was a noticeable difference, it's because I screwed it up right before I committed it. I'll recommit and you'll see the change. I'm glad your paying attention.

But why is it now -deferred instead of -transparent? I don't see any difference if I toggle between the two.

**Comment by onox** [comment]
Continued in PR #512

**Pull request closed without merging**
