### PR TITLE
Bug 704: ceiling looks black

### PR DESCRIPTION
**Pull request by wlbragg**
Lets try this again.

Should close issue #704

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I will test this now

**Comment by gilbertohasnofb** [comment]
Hmm, it does look much better but the speaker in the ceiling still looks completely different. Can't it be affected by the irradiance map as well as the ceiling, so they match colours?

fgfs-screen-001

**Comment by wlbragg** [comment]
Let me see what adding it to the effect does to it.

**Comment by wlbragg** [comment]
I think that fixed it. We used to have the seats and the floor added before we realized it was too dark. I tried them before I pushed this and they worked much better than before, but with the textures they were already using (already pretty grainy) it didn't seem to enhance them much (lighting wise) so I left them out. We can add any of the interior objects we want to include the effect. In the shuttle all the switches on the panels have the effect applied (although it may be slightly different as its base is ra-irradiance).

**Comment by gilbertohasnofb** [comment]
I think this looks better, thanks!

> We can add any of the interior objects we want to include the effect. In the shuttle all the switches on the panels have the effect applied (although it may be slightly different as its base is ra-irradiance).

Do you think adding the switches or other objects would enhance the visuals in some way? I am still a bit confused about the irradiance map and what it exactly does, so I can't visualize what applying it to the switches would cause

**Comment by wlbragg** [comment]
All it is doing is adding shadow (or taking away light) from objects that are not calculated to be in the light rays supposedly being cast depending on the mode you set. Ours is using the mode that says only object faces that are perpendicular to the light coming through the windows get the full light. Any parallel objects are going to have light removed. So in effect it is adding a shading to give depth.
I guess I should try a few switches and knobs and see what it does.

**Comment by gilbertohasnofb** [comment]
Sounds good to me. If you make some tests like that, please share some screenshots, I'm curious how the cockpit would look like.

**Pull request merged**
