### PR TITLE
reversing rudder pedal translation direction

### LINKED ISSUE #752: rudder pedals moving opposite
can someone check the code for this?
[https://forum.flightgear.org/viewtopic.php?p=284786#p284786](url)
DerryUL wrote:
>Just tried a flight in the Cessna and when viewing in the cockpit the rudder pedals move in the wrong sense.
>
When flying in real life if you want to turn left you move your left leg forward. Similarly to turn right you move your right leg forward.
>
The Cessna rudder pedals show the opposite ie to turn left you move your right leg forward.
>
I was using version 2016.1.1
>
Derry.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #752 by simply reversing the translation of the rudder pedals

### CODE REVIEW

**Comment by wkitty42** [comment]
i figured it would be something easy like that :smile_cat:

**Comment by gilbertohasnofb** [comment]
Yes that was an easy fix! I wonder how long this has been an issue, was this present since the original c172p before the "-detailed" project came along??

**Comment by wkitty42** [comment]
On 05/10/2016 12:44 PM, Gilberto Agostinho wrote:
> Yes that was an easy fix! I wonder how long this has been an issue, was this
present since the original c172p before the "-detailed" project came along??
 >

i have no idea... i think it was actually mentioned at one time in the past but 
not sure where or when...

i updated the topic in the forum that it has been fixed and is awaiting merge 
and then being placed in the tagged release for inclusion in 2016.2.1... there's 
only a couple of days left before that happens... hopefully these other fixes 
and updates will all be done in time :)

**Comment by gilbertohasnofb** [comment]
> i updated the topic in the forum that it has been fixed and is awaiting merge and then being placed in the tagged release for inclusion in 2016.2.1... 

Great, thanks a lot. And I suppose @onox or @wlbragg should merge this still today, or at least very soon

> there's only a couple of days left before that happens... hopefully these other fixes and updates will all be done in time :)

Yeah, thanks for the reminder. Someone probably needs to write to the list asking for a merge. @onox is there anything we still want to fix before proposing a merge or can I contact stuart?

**Pull request merged**
