### PR TITLE
Bug 616: Give flaps control a vertical drag direction

### LINKED ISSUE #616: Drag direction of flaps should be vertical instead of horizontal
Drag direction of flaps should be vertical instead of horizontal.

### PR DESCRIPTION
**Pull request by onox**
Fixes #616

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox this works much better than before, but clicking and dragging requires some good precision now as few pixels up or down move the flap. Is there a way to adjust this? Besides that, everything looks fine to me.

**Comment by onox** [comment]
You mean you want dragging to be less sensitive?

**Comment by gilbertohasnofb** [comment]
Yes, that's what I meant, I will check it again now.

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
