### PR TITLE
oil door to normal map

### LINKED ISSUE #500: Add oil door to normal map
Add oil door to normal map

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #500 

fgfs-screen-001

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
I must say it looks beautiful, Gilberto. Nice work! Is it correct that it is openable?

**Comment by onox** [comment]
Currently no. This PR just adds it to the normal map, which is used to create the illusion of some depth.

**Comment by gilbertohasnofb** [comment]
Yeah, onox is correct. An operable door would need a redesign of the 3D model, and given that @thevirtualfer is planning to do a major overhaul of the model I don't think we will add the door right now.

**Comment by legoboyvdlp** [comment]
I see. That's alright.

**Pull request merged**
