### PR TITLE
Bug 713: Adjust spacing between equipment in radio stack

### LINKED ISSUE #713: Adjust spacing between equipment in radio stack
Spacing and alignment between equipment on radio stack could stand to be spaced a little more evenly.

### PR DESCRIPTION
**Pull request by wlbragg**
I'm finished.

Will close #713

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I would bring the DME a bit to the left and a tiny fraction upwards:

fgfs-screen-001

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
I will check it now

**Comment by gilbertohasnofb** [comment]
Thanks!

**Pull request merged**
