### PR TITLE
new instrument: magneto switch

### PR DESCRIPTION
**Pull request by dg-505**
I have created a new folder named "magneto switch" in Models/Interior/Panel/Instruments, where the files for the magneto switch are included. In Models/c172p-detailed.xml I changed the path of the magneto switch to "Models/Interior/Panel/Instruments/magneto-switch/magneto-switch.xml".

Hope I did everything right. This is the first time I work with git...
I'm sorry, if I did any mistakes or did anything wrong.

### CODE REVIEW

**Comment by onox** [comment]
Looks much better, thanks! :smile:

**Comment by dg-505** [comment]
I'm glad you like it.
Now as the starter has it's own texture file, I suggest to remove the appropriate textures in panel_parts.png

**Comment by onox** [comment]
Is that something you could do?

**Comment by dg-505** [comment]
Yes, I'm gonna do it today.

**Comment by gilbertohasnofb** [comment]
Guys, let me deal with the panel_parts.png (there are several slightly different copies of it for each interior theme). Also, I need to optimize the pngs after any alteration. I will do it right now.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by dg-505** [comment]
Perfect :+1: Thank you :smile:

**Pull request merged**
