### PR TITLE
Bug 704: ceiling looks black

### LINKED ISSUE #704: ceiling looks black
Ceiling looks black while the panel with the speaker doesn't. I don't think the ceiling should be pitch black during day at any circumstances.

fgfs-screen-001

### PR DESCRIPTION
**Pull request by wlbragg**
Irradiance strength setting is working fine.

Should close #704

### CODE REVIEW

**Comment by wlbragg** [comment]
I got crap in my master. :sob:

**Comment by gilbertohasnofb** [comment]
:laughing:

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry for using this space for a totally out of subject message, but something seems to be wrong with your e-mail address. I tried replying to you now but my e-mail returned with the following message:

> Delivery to the following recipient failed permanently:
> 
>      wlbragg@cox.nex
> 
> Technical details of permanent failure: 
> DNS Error: 30812207 DNS type 'mx' lookup of cox.nex responded with code NXDOMAIN
> Domain name not found: cox.nex

Just thought I'd let you know. And as for the Cub, I am starting to work on the textures straight away, but the project link you once gave me is labelling it as "abandoned" (see: https://sourceforge.net/projects/fgj3cub/ ). Did you move to FGAddon by any chance?

**Comment by wkitty42** [comment]
@gilbertohasnofb  i'll bet that's supposed to be cox.net instead of cox.nex ;) 

on the cub, IIRC, i read either on the forums or on the dev list that work on the cub will be done in FGAddon now and that the development version has been dropped/abandoned... i know i read it from wlbragg but just not sure where i read it...

**Comment by gilbertohasnofb** [comment]
@wkitty42 thanks! @wlbragg contacted me and told me exactly the same thing. For some reason my Thunderbird recognized the origin of his first e-mail as from the domain cox.nex, which is really bizarre. But it's all solved now :smile: 

And you are also right about FGAddon, the Cub lives only there now.

**Comment by wkitty42** [comment]
:+1:

**Pull request closed without merging**
