### PR TITLE
Bug 280

### LINKED ISSUE #280: Tune g limits for wing damage
The current g limits might be too low and thus make it too easy to tear off the wings.

See https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-110781583 and https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-111212020 in #134.

### PR DESCRIPTION
**Pull request by onox**
Fixes #280, #336, #348, and #351. Additionally it:

* has more deterministic execution of damage logic
* fixes a small problem in 88d5db5
* frees up 5 MP properties
* removes the possibility to damage the aircraft when switching to a new bush kit
* the old code in `Nasal/physics.nas` had a problem that you could manage to get `settledelay` greater than 5, causing the code to continuously keep executing `poll_gear_delay()`

### CODE REVIEW

**Comment by wlbragg** [comment]
I'm OK with merging this as is if we need to. We can come back to it later if necessary.

**Comment by dany93** [comment]
Do you have these messages from the branch master:bug/280 ?
```
Failed to tie property fcs/ to object methods

In file /home/dany/FG/github/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.
Failed to tie property fcs/ to object methods
..................................
Failed to tie property fcs/ to object methods
```
The first ones are rather a question to @andgi
I found once that the other ones (10) can come from switches for which JSBSim do not like having no name.

**Comment by andgi** [comment]
@dany93 The `floats-enabled-norm` warning is due to me having the habit of declaring the input properties for JSBSim systems in the respective system file. In this case the other system that sets the input property is loaded first and thus has already created the input property. The warning as such is harmless. Declaring the inputs is also required for use in JSBSim/standalone if the input property in FG is created by a JSBSim external method (e.g. the -set file).

OTOH, having no name or an already used name on a component is not a good practice.

**Comment by onox** [comment]
I'll add names to the switches.

**Comment by onox** [comment]
@andgi I notice that when I add name attribute to the `<switch>` components, that JSBSim alters the type (int becomes double for example). Any way to prevent that?

**Comment by onox** [comment]
Never mind, it seems that if I use `name="right-wing-damage"` instead of `name="wing-damage/right-wing"` that JSBSim does nothing with it (which is what I want).

**Comment by onox** [comment]
I have nothing more to commit, so please give your :+1: or :-1: :smile:

**Comment by dany93** [comment]
OK.

**Comment by wlbragg** [comment]
See bottom of #280

**Comment by wlbragg** [comment]
Well done onox, lots of work here.

@dany93, are we closing #280 or are you still questioning the wing limits?

**Comment by dany93** [comment]
>@dany93, are we closing #280 or are you still questioning the wing limits?

No, thanks, the changes that I proposed (and you merged) solved my concern.

**Pull request merged**
