### PR TITLE
small improvements to the textures of ALT, HI and ADF

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Sorry for the last minute PR, but I did some work on the gauges for the Cessna 152 II and I realized that some of them actually fit better with the 172 model P as well! Using this as source:

The modifications are:

- ADF: white needle instead of yellow
- HI: different look, much more similar to the model used in RL
- altimeter: older Cessna style, which I have seen in several pictures of the model P. I think it's much more charming than the previous one :smile:

Results:

fgfs-screen-005

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg Would you mind taking a look on these new textures and see what you think?

**Comment by wlbragg** [comment]
Looks good to me. I prefer the white ADF needle also.

I'll let @onox approve and merge if that is OK.

**Comment by gilbertohasnofb** [comment]
Sure, no problems.

**Comment by onox** [comment]
I can understand the changes, but I find the new HI a bit more difficult to read. Can make the font a bit more bold or more readable in some way?

fgfs-screen-471
fgfs-screen-472

**Comment by onox** [comment]
Hmm... at full screen it's better to read, but I find all the instruments a bit difficult to read. Maybe the text should be made bit more white to increase the contrast.

**Comment by onox** [comment]
Or just make the N, E, S, W symbols bold like the NAV instruments.

**Comment by gilbertohasnofb** [comment]
Okay, give me a second

**Comment by onox** [comment]
I think just making NESW more bold would be best, then its easier to recognize the axes (NS/WE)

**Comment by gilbertohasnofb** [comment]
Done, can you pull it again and see what you think?

**Comment by onox** [comment]
Let me check.

**Comment by onox** [comment]
Better! :+1:

**Comment by onox** [comment]
I'm going to create the release branch now.

**Comment by gilbertohasnofb** [comment]
Great, thanks :+1:

**Comment by gilbertohasnofb** [comment]
I should be online for some 30 min more, then I have to leave. Let me know if I can be of any help in this meantime, okay?

**Comment by onox** [comment]
Branch [`release/2016.1`](https://github.com/Juanvvc/c172p-detailed/tree/release/2016.1) has been created! :clap: :tada:

**Comment by gilbertohasnofb** [comment]
Congrats to everyone, @onox @wlbragg @Juanvvc @dany93 @tigert @andgi et al! :clap: :clap: :clap:

**Comment by onox** [comment]
Some fun statistics with `git shortlog -sn --no-merges --since="2015-07-13 21:43"`:

```
   159  gilbertohasnofb
   119  onox
   105  wlbragg
    82  Wayne Bragg
    25  Tuomas Kuosmanen
    20  Jonathan Schellhase
     3  Gilberto Agostinho
     3  dany93
     2  IAHM-COL
     1  Delta Echo
     1  Philosopher
     1  dg-505
```

Thanks guys for all the hard work. I like the new and better cockpit instruments, the lighting, sounds, tutorials, web panel, pontoon + skis stuff :smile: And finally that glass reflection that I have always wanted so badly! :laughing:

**Comment by gilbertohasnofb** [comment]
:trophy: :laughing: :tada: (although this is only because @wlbragg is split between two user names for some reason!)

**Comment by wlbragg** [comment]
>@wlbragg is split between two user names

Apparently my Linux box and my Windows box use different accounts, or at least different profiles, if that is even possible?

I screwed up and forgot to mention the shadow and reflection contribution from jarlarntzen. I was half asleep and in a hurry when I committed his cubes. Maybe we can get his contribution mentioned at some point somewhere.

Yes, congrats to everyone that has contributed.
I can't wait for the next version. I was almost going to try to get the glass fog (defrost pattern) and sun glare masks in this morning, but my need for sleep superseded my desire for effects, ha.

**Comment by gilbertohasnofb** [comment]
It's funny how in the last 48h we tend to implement the same amount of features as in the previous month, right?! I am the same, improving the textures of the HI minutes before the last merge :smile:

**Comment by Juanvvc** [comment]
Congratulations to everyone involved in this release! I'm very sorry I couldn't contribute with anything useful this time. The team you have arranged is perfect and you made something awesome with the c172p. This project is a very good example of how open source is developed and evolves over time. You must be really, really proud!

Congrats!

**Pull request merged**
