### PR TITLE
Bug #683 - External lights aren't visible from certain angles

### LINKED ISSUE #683: External lights aren't visible from certain angles
Gijs wrote in the forum:

> The red and green lights should be visible when flying head on towards the aircraft. The table from FAR §23.1391 says that between 0° to 10°, the minimum (!) intensity should be 40 candelas. Below 0° the lights on the c172p are now completely invisible, whereas I would expect a gradual reduction. See for example the following videos:
> 
> https://www.youtube.com/watch?v=KR-Girnjcyg
> 
> https://www.youtube.com/watch?v=0kaXYQb5ko4

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #683 

I think this is better but may need further adjustments.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Is this ready for testing and merging?

**Comment by onox** [comment]
> Is this ready for testing and merging?

Not really. I think the XML is incorrect in the commit above. Ideally we should get GLSL lights. In the mean time the cone needs to be modified and then the XML needs to be modified.

**Comment by gilbertohasnofb** [comment]
Ok, so :warning: :warning: :warning: no merging please

**Comment by onox** [comment]
Branch has been superseded by `bug-683`.

**Pull request closed without merging**
