### PR TITLE
Bug 443

### PR DESCRIPTION
**Pull request by onox**
From PR #481: "I think even 2 more thunder sound modules and this would be optimal, especially if there were 2 or 3 different thunder sounds. It's really a nice feature, you guys did a great job. Very immersive, I really like the rain sound too."

Fix some issues in #443

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Don't merge this yet as the new sounds are not programmed in. I mentioned before that ideally they could be randomly selected (to avoid a 1->2->3->1->2->3 pattern), but if that's not possible we can simply use the 123 solution. Could any of you guys check this out when you have a chance? Thanks!

**Comment by onox** [comment]
In that case we need 9 sound definitions?

**Comment by gilbertohasnofb** [comment]
Hmm, I see that `<path>Sounds/thunder.wav</path>` can't be randomly selected, right? So in that case we can just go with the 123123 and see how it sounds. Maybe the effect will be good enough like that, particularly if we take into account the distance of the lightning when dealing with the volume (thus making each sound even more individual).

**Comment by onox** [comment]
OK, try to modify `<thunder2>` and `<thunder3>` and test how it sounds.

**Comment by gilbertohasnofb** [comment]
Will do that!

**Comment by gilbertohasnofb** [comment]
I think it sounds great, better than before. And the sounds are similar enough so that the 123 pattern can't be easily heard. As for making the volume proportional to distance, would you be able to have a look at it?

**Comment by onox** [comment]
You can do that as well :smile: 

`lightning_distance_norm` gives a value between 1.0 and 2.0. If you remove the '1 + ` part, then you get a number between 0 and 1.

Next step: replace `<sum>` with `<product>`.

**Comment by onox** [comment]
Hmm... I doubt the XML sound system supports `<expression>` though...

**Comment by gilbertohasnofb** [comment]
Hmm, so in that case would you have some other ideas of how to implement this? Do we need to use Nasal then?

**Comment by onox** [comment]
You can just add 3 small `<filter>`'s to `Systems/sounds.xml`.

**Comment by wlbragg** [comment]
I don't think the 123 pattern will happen anyway. because if you watch the debug properties it doesn't appear to stay in order (even though it should) I think various other actions may cause whats playing to execute at a different rate than the 9 seconds so it may go 1 2 3 then 2 may finish first and now it is available and so it get picked up, then 1 becomes available then it goes again then 3. So you might have 1 2 3 2 1 3. At least that's what I thought I saw last night.
I sure am glad you noticed my botched merge and commit. I don't know what I did to get to that state. I noticed it last night when I did it, that it looked strange but was to tired to look into it.
I haven't finished reading all the posts in this thread yet so if I am way out of order bare with me. This time difference can cause issues all on its own.

**Comment by wlbragg** [comment]
Thanks @onox, I just finished catching up on this thread. I wasn't sure how to get the volume because I don't know what the volume tag is expecting as input (as in the range of value 0-1 or 0-100 or what. I also didn't know what how it was calculating the factor and in our case using two products. I added the 1+ to make it a value between 1-2 to see if I could hear a difference easier to see if it was working. 

>particularly if we take into account the distance of the lightning when dealing with the volume (thus making each sound even more individual).

Yes I thought the same thing, it should really help mix it up.

**Comment by wlbragg** [comment]
@gilbertohasnofb Do you know how to add a filter?

**Comment by gilbertohasnofb** [comment]
@wlbragg not really, I was trying to read about it but still couldn't find anything about `<filter>`. If you are able to do that, feel free to implement this.

**Comment by wlbragg** [comment]
OK, I'll take care of it. You can look at what I do then you'll know, there really isn't much to it, unless you've never done it, ha!

**Comment by gilbertohasnofb** [comment]
Sounds good! :+1:

**Comment by onox** [comment]
@wlbragg @gilbertohasnofb I have fixed the issues I wrote about in the comments above. Currently `lightning_distance_norm` is very linear, but shouldn't the sound energy dissipate across a surface (2D) or volume (3D)?

**Comment by gilbertohasnofb** [comment]
I believe it should be squared (2D) as the intensity should be inversionally proportional to the surface area of a sphere around the sound source.

**Comment by gilbertohasnofb** [comment]
> The sound intensity `I` (energy) falls inversely proportional to the square of the distance

**Comment by onox** [comment]
What about this: `25000000/math.pow(lightning_distance, 2)`? This will give:

```
25000000/(5000**2) = 1.0
25000000/(15000**2)
```

Loudest (100 %) at 5000 meter, 10 % at 15 km.

**Comment by onox** [comment]
I'm not completely sure about squaring the distance. The volume decreases rather quickly if I change the minimal distance at which volume is 1.0.

**Comment by onox** [comment]
This expression is better: `1/((10000.0/5000.0)**2)`. Gives 25 % for 10 km, 100 % for 5 km.

**Comment by gilbertohasnofb** [comment]
Sounds reasonable (no pun intended), but maybe we want to bring that figure of 5km down to 1km, so that if a strike is very nearby it will be quite loud.

**Comment by onox** [comment]
Should we in that case switch to a different sound (just a bang, instead of lots of rumbling)?

**Comment by onox** [comment]
I did some measurement of 68 thunder strikes:

min: 4783.409328325995
mean: 8874.076194374664
median: 8802.61975248733
max: 13938.43289182003

**Comment by gilbertohasnofb** [comment]
In that case, I would say use the last formula you came up with. And I would keep the same sound files, I really like the rumbling.

**Comment by onox** [comment]
One more thing we can do is: you can hear thunder on the ground up to about 16 km. We can make that 20 km and limit playing sounds only for thunder < 20 km.

**Comment by gilbertohasnofb** [comment]
I think a limit of distance is indeed reasonable.

**Comment by wlbragg** [comment]
Looks good guys. The idea of a loud bang for lightning that is right on top of you isn't a bad idea. We get tons of lightning here and a close strike will about knock you out of your chair and then no other sound.
But I am good with it either way.

I'm getting ready to pull it and test.

**Comment by onox** [comment]
I have some changes to commit.

**Comment by wlbragg** [comment]
I agree, a limit of distance is reasonable, believe it or not it doesn't travel as far as you might think. We can't really hear it much over 10 miles under perfect conditions.

**Comment by wlbragg** [comment]
OK, I haven't pulled it yet.

**Comment by onox** [comment]
Committed. I have removed the clamping (to 50 seconds) because of the distance check.

**Comment by onox** [comment]
I'm a bit surprised I just cannot find the speed of sound anywhere in the property tree :open_mouth:

**Comment by gilbertohasnofb** [comment]
> I'm a bit surprised I just cannot find the speed of sound anywhere in the property tree :open_mouth:

Yep, I also spent some long time looking for it!

**Comment by wlbragg** [comment]
Really, how do we do sonic booms without it, ha?

**Comment by onox** [comment]
Can we find the atmosphere pressure and density somewhere in `/fdm/jsbsim/`?

**Comment by gilbertohasnofb** [comment]
I think you can find it in `/environment`

**Comment by wlbragg** [comment]
I don't know how I missed it but when I was cleaning up some of the commented out code, I cleaned c172p.nas but left the main unused "terrain_survol_loop" function. I deleted the reference to it but not the function. It needs to be deleted.
@onox, if your still to commit more to this branch, you can delete the "terrain_survol_loop" function.

**Comment by onox** [comment]
OK

**Comment by onox** [comment]
I guess density needs to be in kg/m^3.

**Comment by wlbragg** [comment]
Absolutely incredible, this is really cool, to bad it is so difficult to fly in the thunderstorms, I keep breaking my plane.

I have noticed on occasion that it still cuts off the sound prematurely. I can't tell why though. It may be that the 9 second timer needs to be extended a little bit to allow for system bottle necks?

**Comment by onox** [comment]
> I have noticed on occasion that it still cuts off the sound prematurely.

The problem is that the listener callback can be invoked multiple times shortly one after another, and in both cases they might think a sound is 0 because of the delay.

**Comment by onox** [comment]
So I think you need to delay the decision which sound to use until you actually want to play the sound.

**Comment by wlbragg** [comment]
Yeah, extending it didn't help.
OK, I see what your talking about, now how to do this?

**Comment by onox** [comment]
Call `settimer()` with appropriate delay. Choose a sound in its callback and then call `click()` with delay 0?

**Comment by wlbragg** [comment]
Use the same delay_seconds as a timer before calling the 
if (!thunder1) 

?

**Comment by onox** [comment]
Yes.

I have nothing to commit currently. Still busy with the speed of sound.

**Comment by wlbragg** [comment]
Oops, I posted same time you did. I need to think about this, my brain is fried today.

**Comment by wlbragg** [comment]
OK, that make sense, at least at the moment. :confused:

**Comment by wlbragg** [comment]
OK, testing it now.

**Comment by wlbragg** [comment]
Much better, I think that completely fixed it.

**Comment by wlbragg** [comment]
Yes, no more cutouts. Can I push my bug-443 now?

**Comment by onox** [comment]
Remove all tabs? :wink:

**Comment by wlbragg** [comment]
I removed "terrain_survol_loop"
I wasn't sure what to describe for the commit.

**Comment by onox** [comment]
"Removing unused function terrain_survol_loop"?

**Comment by wlbragg** [comment]
I've been listening to it this whole time and not so much as a hiccup.

Unfortunately it also fixed the randomness, it is now following the 123,123,123 order. But I don't think that it is really noticeable because you actually get, 12, 312, 31, 231, 23, 123 etc.

**Comment by wlbragg** [comment]
>"Removing unused function terrain_survol_loop"?

No, changing the delay to how we did it. I wasn't really sure how to describe it. :smile:

**Comment by onox** [comment]
But the function still exists?

**Comment by wkitty42** [comment]
On 11/01/2015 05:59 PM, onox wrote:
> Should we in that case switch to a different sound (just a bang, instead of
> lots of rumbling)?

there would be a really loud bang plus some loud rumbling that gets quieter as 
the sound dissipates...

**Comment by gilbertohasnofb** [comment]
> there would be a really loud bang plus some loud rumbling that gets quieter as the sound dissipates...

If you guys want to break the sound down to its components (that is, a sound file for the loud bang, another for the rumbling, another for low frequencies, etc.) it will get a bit complicated. This sound we have is a RL recording, and then either we will have to synthesize the components separately (tons of work, not good result) or we need to filter parts of it away (can get full of artifacts). My suggestion is to keep using our current sound which, IMO, is quite decent.

**Comment by onox** [comment]
Let keep it simple for now.

**Comment by wlbragg** [comment]
>But the function still exists? Any intention to remove it? 

I removed it in the last push, I thought?

**Comment by wlbragg** [comment]
I'm an idiot, I guess I forgot to actually delete it, only in my mind!

**Comment by onox** [comment]
Well? I still don't see it here on Github :laughing:

**Comment by wlbragg** [comment]
You don't see the push at all?

**Comment by onox** [comment]
Nope. Do `git status`.

**Comment by onox** [comment]
@wlbragg Everything OK over there on the other side of the pond? :wink:

**Comment by wlbragg** [comment]
I just pushed it again with the "ground detection" deletion.

**Comment by onox** [comment]
Yes. I see it now.

**Comment by onox** [comment]
Merge the PR?

**Comment by wlbragg** [comment]
Fine with me!

**Pull request merged**
