### PR TITLE
Add damaged Spinner, stop Spinner from spinning after crash.

### PR DESCRIPTION
**Pull request by wlbragg**
I think I covered everything.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Testing now

**Comment by gilbertohasnofb** [comment]
Okay, it works, but now the spinner changes its illumination after the crash, see how much brighter it looks:

before:
fgfs-screen-003

after:
fgfs-screen-004

**Comment by wlbragg** [comment]
I noticed that also, I'll see if I can find where that is being assigned. I thought that didn't look right.

**Comment by gilbertohasnofb** [comment]
Thanks, let me know if I can help.

**Comment by wlbragg** [comment]
Found it, in doing so I noticed the propeller doesn't have it either. So please also pay special attention to the damaged and undamaged propeller while testing.

**Comment by gilbertohasnofb** [comment]
Aha! So you probably solved https://github.com/Juanvvc/c172p-detailed/issues/159 as well, right?

I will test it all soonish, I just need to go after some dinner now :smile:

**Comment by wlbragg** [comment]
Probably so. :smile:

**Comment by wlbragg** [comment]
I verified #159 is fixed as well but please confirm.

**Comment by gilbertohasnofb** [comment]
@wlbragg Thanks you!

**Pull request merged**
