### PR TITLE
Bug 303

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Implementing chocks for bush configurations, tiedown for all except float and amphibian, improving xml code

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
:warning: :warning: :warning: 

Please test but do not merge this PR yet, as I have found a bug which needs further testing. Here is the rub: before, I was using the parking brakes property to implement the chocks and tiedowns. In the list, they recommend me to use `/fdm/jsbsim/forces/hold-down`, which is indeed much more elegant, and hold the aircraft down much better than parking brakes (which allows a bit of movement up and down. The issue is that if `/fdm/jsbsim/forces/hold-down` is set to `true` while the aircraft has even the slightest pitch movement (e.g., if one is braking in the runway and thus the nose of the plane is slightly downwards, even though the speed at that moment is 0 knots) the aircraft will continue in that movement (it will continue to pitch down and enter the ground and brake apart). Even the most imperceptible movement affects this (try accelerating the simulation time to 32x to observe this). _Summa summarum_: If the aircraft is fairly static when the chocks or tiedowns are activated, it works like a charm. But it has the potential to be very buggy, and so we need to decide what to do. Any ideas, @onox ?

**Comment by onox** [comment]
Let me first check the PR is functionally OK.

**Comment by gilbertohasnofb** [comment]
Sure. And by the way, I also asked the list for some other possible property that could be used to force the plane to be static, let's see if they have some interesting ideas.

**Comment by wlbragg** [comment]
>before, I was using the parking brakes property to implement the chocks and tiedowns

I don't know how you ended up on this but I would suggest that if possible the chocks should only be the brake implementation, the tiedowns should use the "hold-down".  If this is not to much trouble.

**Comment by onox** [comment]
I don't think we should use the `hold-down` property for now:

fgfs-screen-290
fgfs-screen-291

**Comment by onox** [comment]
Also, I would like to be able to remove the tiedowns by clicking on the tiedown rings (the metal thingies attached to the wings) themselves.

**Comment by gilbertohasnofb** [comment]
> I don't think we should use the hold-down property for now:

@onox besides that, did everything else work as planned? I tested this branch a zillion times and I am quite confident it works well besides the mentioned bug

I can revert it back to the parking brakes property, so at least we can merge this and then later try to improve on it, if the guys on the list suggest something better. The downside of using parking brakes for all these things is that we will have to check our checklist and Tutorials for any mentions of the parking brake property, but I can try to take care of that myself. If this sounds good to you, I will start to work straight away, and then we can retest it and merge.

**Comment by gilbertohasnofb** [comment]
> Also, I would like to be able to remove the tiedowns by clicking on the tiedown rings (the metal thingies attached to the wings) themselves.

Okay!

**Comment by onox** [comment]
Btw, could you make the textures of the tires more blackish? I don't like the grey color that much :stuck_out_tongue_winking_eye: This looks better: https://github.com/Juanvvc/c172p-detailed/blob/master/README.md

**Comment by gilbertohasnofb** [comment]
> Btw, could you make the textures of the tires more blackish?

I will open a new issue and a new PR for that, ok? I think I can do all this still tonight :sweat_drops:

**Comment by onox** [comment]
:+1:

**Comment by wlbragg** [comment]
>tiedown rings (the metal thingies attached to the wings) 

Eventually, I plan to cutout and recess the rings into the strut. You can see in the RL example image that the ring is recessed into a cutout on the strut. I didn't want to go to too much trouble though until the @thevirtualfer gets the new model finished.

>I don't like the grey color that much

When did it get changed?

**Comment by onox** [comment]
> The downside of using parking brakes for all these things is that we will have to check our checklist and Tutorials for any mentions of the parking brake property, but I can try to take care of that myself.

In theory `hold-down` is more logical choice to use, but it doesn't work that great in practice. So we should use the parking brake for now.

**Comment by onox** [comment]
> When did it get changed?

I don't know. The tires have always been so greyish.

**Comment by onox** [comment]
> we will have to check our checklist and Tutorials for any mentions of the parking brake property

I'll check the usage of the parking brake in the checklists and tutorials.

**Comment by onox** [comment]
Tutorials use `/controls/gear/brake-parking`. To which property should I change this @gilbertohasnofb ?

**Comment by gilbertohasnofb** [comment]
@wlbragg 

> I didn't want to go to too much trouble though until the @thevirtualfer gets the new model finished.

Makes sense, but we can't simply wait forever until his model is done. Let's keep working with what we have and if he comes up with a new model then we start reapplying stuff. 

> When did it get changed?

I also don't know if they ever got darker, but they will tonight :smile: 

@onox 

> I'll check the usage of the parking brake in the checklists and tutorials.

Thanks, I will take care of the rest then

> To which property should I change this 

I was using `/sim/model/c172p/brake-parking`, to make it consistent with the chocks and tiedowns.

**Comment by onox** [comment]
The yellow chocks are OK, but the wooden chocks need their position to be adjusted a little bit:

fgfs-screen-293

**Comment by gilbertohasnofb** [comment]
@onox the trick is that @wlbragg tried using the same chocks for both the 26' and the 31' tires, and so for the 26' they look slightly far away from the tire.

**Comment by onox** [comment]
Hmm.. basically it's 1 piece imported 4 times (twice for 26", and twice for 31").

**Comment by gilbertohasnofb** [comment]
> Hmm.. basically it's 1 piece imported 4 times (twice for 26", and twice for 31").

The model for the __wooden__ chocks consists of one object for both blocks (unlike my yellow model which consists of two objects).

**Comment by onox** [comment]
Wouldn't it be better to make it one piece? Then you can just rotate and translate it.

**Comment by onox** [comment]
Reverting to `/controls/gear/brake-parking` is not a great solution either. It's an input property controlled by the user :cry:

**Comment by gilbertohasnofb** [comment]
> Wouldn't it be better to make it one piece? Then you can just rotate and translate it.

Probably yes. If @wlbragg wants to take care of that, I don't mind separating the `woodchock` property into `woodchock26` and `woodchock31`.

> Reverting to /controls/gear/brake-parking is not a great solution either. It's an input property controlled by the user

I don't get it. I will bind `Shift+B` into the `/sim/model/c172p/brake-parking` and a `<logic>` block will dictate that if the parking brake lever or any of the securing objects is on, then `/controls/gear/brake-parking` is `true`. The lever will be tied to `/sim/model/c172p/brake-parking`. So what is the problem?

**Comment by onox** [comment]
Yeah, it's not an insurmountable problem. It's just when I read FG's C++ code, I see things using input properties (`/controls/`) directly. There's no place where you can intercept the command and control the actual output. (Only for throttle and mixture, etc. in JSBSim)

**Comment by onox** [comment]
Btw, `brake-parking` is a double apparently.

**Comment by gilbertohasnofb** [comment]
> brake-parking is a double apparently

Is it really? So how the hell this below works?

```
     <logic>
        <name>Parking Brake and chock</name>
        <input>
            <or>
                <property>/sim/model/c172p/brake-parking</property>
                <property>/sim/model/c172p/smallchock-visible</property>
                <property>/sim/model/c172p/woodenchock-visible</property>
                <property>/sim/model/c172p/tiedowns-visible</property>
            </or>
        </input>
        <output>
            <property>controls/gear/brake-parking</property>
        </output>
    </logic>
```

Does logic automatically map `false` and `true` into `0.0` and `1.0` in case of a `double` type?

**Comment by onox** [comment]
Yes, I think so.

**Comment by onox** [comment]
I'll replace `/controls/gear/brake-parking` with `/sim/model/c172p/brake-parking` in the `Tutorials/*` and `c172-checklists.xml`.

**Comment by gilbertohasnofb** [comment]
> I'll replace /controls/gear/brake-parking with /sim/model/c172p/brake-parking in the Tutorials/* and c172-checklists.xml.

Okay, I am also almost ready to push the parking brake reversion, as well as making the tiedown hooks clickable.

**Comment by wlbragg** [comment]
What do you want me to do with what chocks?
The wooden ones shouldn't have to be duplicated. The front wheel size is the same for both the 26" an 36" wheel. What is causing a bit of an issue is the compression of the front strut because of the back wheel size and angle. That back chock can be pushed closer to the tire.

**Comment by gilbertohasnofb** [comment]
> The front wheel size is the same for both the 26" an 36" wheel. What is causing a bit of an issue is the compression of the front strut because of the back wheel size and angle.

In that case, let me first have a look if I can fix this just by adjust the position, maybe I will find a good solution here.

**Comment by wlbragg** [comment]
You will find a happy median for rotation between the two tire sizes (rear). But I still may need to close the gap in the blocks a tiny bit.

**Comment by wlbragg** [comment]
Yes, I thought I had it without a gap on both the 26" and 36" but it rotated high in front on one size and high in back on the other size. I just used the median. You maybe changed the offset a little? Or it is shifting slightly depending on the terrain.

**Comment by gilbertohasnofb** [comment]
> You maybe changed the offset a little

I did have to lower them a bit, they were too high. I am now playing with the offset and maybe I will find a solution without any modification to the model, just give me a sec.

**Comment by wlbragg** [comment]
OK, I also had them sunk a little bit on purpose to help deal with the weird rotation issue depending on which wheels were selected. Take your time, I'm just providing you info of what I learned when I was making them.

**Comment by gilbertohasnofb** [comment]
So:

- parking brake solution reverted (including the Shift B keyboard bind)
- hooks now add/remove tiedowns as well
- better position of wooden chocks
- some small improvements on the xml code (smaller code than before)

If you guys think the wooden chocks are looking all right now, then as soon as onox finishes the modifications to the checklists and tutorials then we can merge

**Comment by onox** [comment]
Now it's the piece that is in front of the wheel that's positioned too far :laughing: :cry: :

fgfs-screen-294

**Comment by onox** [comment]
Parking brake + tiedowns work!

**Comment by gilbertohasnofb** [comment]
> Now it's the piece that is in front of the wheel that's positioned too far

I think that's the best I can do with simple offsets. If we want it tighter, we have to edit the model.

> Parking brake + tiedowns work!

:tada:

**Comment by onox** [comment]
> we have to edit the model.

@wlbragg?

https://media1.giphy.com/media/sXv0vaA4331Ti/giphy.gif

**Comment by wlbragg** [comment]
OK, getting on it now!

**Comment by onox** [comment]
:smile_cat:

**Comment by onox** [comment]
Better to make it 1 piece though IMO. Easier to edit XML than Blender :smile:

**Comment by gilbertohasnofb** [comment]
> Better to make it 1 piece though IMO. Easier to edit XML than Blender

Although positioning things is much easier in Blender than XML, unless I am missing a super easy technique: basically I edit via trial and error, and I have to reload the sim at every modification...

**Comment by onox** [comment]
You can reload the model via the Debug menu.

**Comment by gilbertohasnofb** [comment]
> You can reload the model via the Debug menu.

I think it doesn't take into consideration changes in the xml code, or at least from some files. But the positioning is very annoying with trial and error, while in Blender you can use the aircraft model to position things perfectly well.

**Comment by onox** [comment]
It should reload XML as well. Plus you can temporarily use properties (`/test/x`, `/test/y/`, etc.) for the offsets.

**Comment by wlbragg** [comment]
Except in this case because the back tire size changes the compression of the front tire ant the z-position slightly.

If I use the tire in the blend to line this up, it is way off in the sim. So I pulled all you new changes and I will try to line it up locally then push when I get it right, OK?

**Comment by onox** [comment]
OK.

**Comment by wlbragg** [comment]
fgfs-screen-006
fgfs-screen-005

**Comment by onox** [comment]
Btw, I got this in the terminal:

```
Could not find at least one of the following objects for animation: 'woodenchock'
Could not find at least one of the following objects for animation: 'tiedowns'
```

**Comment by onox** [comment]
Looks better @wlbragg.

**Comment by wlbragg** [comment]
I get that error also, I've had it for awhile but hadn't tracked it down.

OK, I'm pushing now.

**Comment by gilbertohasnofb** [comment]
@wlbragg let me know once you have pushed the improved model
@onox is there anything else besides the wooden chocks to fix in this branch?

**Comment by onox** [comment]
Those two errors above.

**Comment by gilbertohasnofb** [comment]
`Could not find at least one of the following objects for animation: 'woodenchock'`
`Could not find at least one of the following objects for animation: 'tiedowns'`

I will investigate

**Comment by wlbragg** [comment]
OK, done

**Comment by wlbragg** [comment]
Those error are inconsistent so I am thinking it is maybe on a gear change over or selecting an option.

**Comment by onox** [comment]
I think I found the problem.

**Comment by gilbertohasnofb** [comment]
> I think I found the problem.

What is it?

**Comment by onox** [comment]
You can merge the PR :+1:

**Comment by gilbertohasnofb** [comment]
Oops, _mea culpa_! Thanks for fixing it, onox :smile: 

@wlbragg the new wooden chocks look excellent to me, so let's merge this!

**Comment by gilbertohasnofb** [comment]
I'd say we can delete this branch, as the other things listed on #303 have now their own issue numbers, and I would create new branches for them.

**Comment by wlbragg** [comment]
:clap:

**Comment by gilbertohasnofb** [comment]
:tada: :beers:

**Comment by onox** [comment]
Nice work guys.

**Comment by wkitty42** [comment]
On 11/04/2015 01:54 PM, Gilberto Agostinho wrote:
> :warning: :warning: :warning:
> [...]
> /Summa summarum/: If the aircraft is
> fairly static whe n the chocks or tiedowns are activated, it works like a charm.
> But it has the potential to be very buggy, and so we need to decide what to do.
> Any ideas, @onox?

ask on the dev list... they'll know what to do...

have you looked at the other method that was given? the one that the airships 
use? or is this one that one?

you guys have been busy while i've been ""sidetracked"" working on my truck and 
haul trailer... 100+ posts since my last email pull :lol:

**Comment by wkitty42** [comment]
On 11/04/2015 02:46 PM, wlbragg wrote:
>     before, I was using the parking brakes property to implement the chocks and
>     tiedowns
>
> I don't know how you ended up on this but I would suggest that if possible the
> chocks should only be the brake implementation, the tiedowns should use the
> "hold-down". If this is not to much trouble.

i think i can agree with that... with only chocks, a craft can definitely be 
blown about by strong/tornado winds :wink:

**Comment by onox** [comment]
`hold-down` is buggy.

**Pull request merged**
