### PR TITLE
Add missing items to checklists (fixes #4)

### LINKED ISSUE #4: Checklist: Add more missing items
Some missing items could be added to the checklists:

To "Before Starting Engine":

1. [x] "Avionics Power Switch": Add a binding action to turn it off

2. [x] "Fuel Quantity", "CHECK"

To page 2 of "Before Takeoff":

1. [x] "Transponder Mode", "SBY OR ALT" (Remove from "Normal Takeoff" and "Short Field Takeoff" checklists)

2. [x] "Landing Light", "AS REQUIRED"

To "Cruise":

1. [x] "Altimeter", "SET"

2. [x] "Fuel Quantity", "CHECK"

3. [x] "Lights", "AS REQUIRED"

To "Descent":

1. [x] "ATIS", "NOTED"

2. [x] "Altimeter", "SET QNH"

3. [x] "Landing Light", "ON"

4. [x] "Fuel Quantity", "CHECK"

To "After Landing":

1. [x] "Transponder", "SBY"

2. [x] "Landing Light", "AS REQUIRED"

3. [x] "Taxi Light", "ON"

To "Securing Airplane":

1. [x] "Power", "SET 1000 RPM"

2. [x] Change "Avionics, Power, Electrical, Autopilot" to "Electrical Consumers", "ALL OFF" (Which switches should I check exactly?)

3. [x] "Avionics", "OFF"

4. [x] Fix marker location of "Ignition Switch"

5. [x] "Flashing Beacon", "OFF"

6. [x] "Master Switch", "OFF"

7. [x] "Parking Brake", "SET AS CONVENIENT"

### PR DESCRIPTION
**Pull request by onox**
This fixes #4. Before merging in Github, please do `git pull` (or fetch) and then `git checkout bug-4`. Then start FG to test the changes.

### CODE REVIEW

**Comment by Juanvvc** [comment]
I have just pushed two small fixes to the checklists:

- Before takeoff: LANDING LIGHT ON (not AS REQUIRED, must be ON); TRANSPONDER ON OR ALT (it said SBY and this is not correct: it must be sending data, not waiting. Do you hear about the missing Malaysia Airlines?)  
- Before landing: LANDING LIGHT ON

If you agree, we can merge this with the master branch.

**Comment by onox** [comment]
You can merge it! :smile: :shipit:

**Comment by gilbertohasnofb** [comment]
Checklist says to prime 2-6 times, but I think Juan programmed it to be 3-6 times. If that's the case, one of them should change.

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/81 and https://github.com/Juanvvc/c172p-detailed/issues/45

**Pull request merged**
