### PR TITLE
Bug 634: Improve flaps lever

### LINKED ISSUE #634: improve flaps lever
I think our flap lever is not the most common model found in the P model. Most of the images I found are of this model:

Note how it has only two colours (light blue and white) as opposed to ours with three, also note that the numbers inside these colours show the max speed for that flap extension and not the angle. 

I will work on the new texture, but probably the model will have to be slightly adapted. Any volunteers to fix it? (should be some really simple adjustments)

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #634 

Hum, this says you can't merge it?

Unrelated to the PR can't merge issue, there may be an issue with the ignition switch. In the blend and the ac file there are two keys (start and start.001) and keyholes (key and key.001) at different starting positions. I thought I used the wrong keyhole (key.001) in the first commit as it wasn't moving or staying lined up with the key. So I re-committed it using the other keyhole (key) however that does the same thing. So I don't know if this ever worked right or not? Someone needs to take a look at it.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I think it conflicts with the PR https://github.com/Juanvvc/c172p-detailed/pull/649, but this can be safely merged (manually) I believe. But before merging this, please see my comment at https://github.com/Juanvvc/c172p-detailed/issues/634 as I think we need to fix something before merging this PR!!! :warning: :warning: :warning:

**Comment by onox** [comment]
@wlbragg You modified `Models/c172p-skis.blend` in `master` on 2016-01-03 10:23, but the commit "new flap texture" is from before that date.

**Comment by onox** [comment]
I'm going to perform some surgery on this branch and will then force push.

**Comment by onox** [comment]
I have removed the moving of the .blend files to `dev/` from this branch. I agree with the moving though (to `dev/blender/`), so we can do that after this branch has been merged.

**Comment by onox** [comment]
@gilbertohasnofb You probably need to go back some commits before you pull the (two) new commits. Reset hard to `git merge-base bug-634 master`.

**Comment by gilbertohasnofb** [comment]
Ok!

**Comment by onox** [comment]
That should be 4 commits backwards (if you had pulled @wlbragg's changes), so you can do `git reset --hard HEAD~4`

**Comment by gilbertohasnofb** [comment]
@onox Sorry but I am having a terrible day with problems all over the place with my FG so I simply nuked my c172p repository and re-cloned it. Now `git log` on this branch gives me:

```
commit bd0dcc157da41755b2bee855344bc161fe83419b
Author: wlbragg <wlbragg@cox.net>
Date:   Sat Jan 9 14:53:28 2016 +0100

    UV map new flaps selector panel and adjust lighting of ignition switch
    
    Signed-off-by: onox <denkpadje@gmail.com>

commit 846b25e6bb1d037ac85c3d7f93b39158dbeed9bd
Author: Gilberto Agostinho <gilbertohasnofb@gmail.com>
Date:   Sat Jan 9 14:48:54 2016 +0100

    New flap texture
    
    Signed-off-by: onox <denkpadje@gmail.com>

commit 65de7dc388fe384dc4a9495d92ddd1829e04da2a
Merge: 0669e93 27d6a3f
Author: onox <denkpadje@gmail.com>
Date:   Fri Jan 8 21:13:42 2016 +0100

    Merge pull request #647 from Juanvvc/Bug-295
```

So I suppose it's all fine and I can work on the flaps xml file, right?

**Comment by onox** [comment]
I don't think nuking was necessary, but bd0dcc157da41755b2bee855344bc161fe83419b is indeed the last commit.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
@gilbertohasnofb I'm going to move the .blend files in a new branch (so don't work on any .blend file for now :wink:)

**Comment by gilbertohasnofb** [comment]
ok

**Comment by onox** [comment]
Moved files in PR #655

**Comment by onox** [comment]
@wlbragg @gilbertohasnofb I have implemented the animations for the flaps lever. I have also made the yoke, pedals, and parking brake lever control smooth instead of instant. (Press 5 to reset controls and the yoke/pedals and surfaces will no longer instantly move to their default position).

I guess this PR is ready and can be merged after testing.

**Comment by gilbertohasnofb** [comment]
Thanks @onox, I will take a look at it now.

**Comment by gilbertohasnofb** [comment]
That flap animation looks gorgeous! :clap:

**Pull request merged**
