### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by onox**
* Fixes turning on master battery and alternator in the checklists
* Remove the JSBSim error about the `fcs/mixture-pos-norm` property

Please test the master switches and the mixture. If your git status is clean:

1. `git fetch origin`

2. `git checkout misc-bug-fixes`

### CODE REVIEW

**Comment by dany93** [comment]
Sorry still a question about git
I've tested your fix  for fcs/mixture-pos-norm property (OK).

But after coming back to my branch I'm now in a git status of which I'm not certain it is good.
git status message:" detached HEAD on origin/master".

To remind:
```
 $ git remote -v
origin  https://github.com/dany93/c172p-detailed.git (fetch)
origin  https://github.com/dany93/c172p-detailed.git (push)
upstream    https://github.com/Juanvvc/c172p-detailed.git (fetch)
upstream    https://github.com/Juanvvc/c172p-detailed.git (push)
```

here is my history
```
dany@dellinux ~/FG/git_c172/c172p-detailed $ git fetch upstream
remote: Counting objects: 333, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 333 (delta 219), reused 137 (delta 137), pack-reused 78
Réception d'objets: 100% (333/333), 4.21 MiB | 3.77 MiB/s, done.
Résolution des deltas: 100% (234/234), done.
Depuis https://github.com/Juanvvc/c172p-detailed
 * [nouvelle branche] c172p-detailed-standalone -> upstream/c172p-detailed-standalone
 * [nouvelle branche] dual-control -> upstream/dual-control
 * [nouvelle branche] internal-shadow-control -> upstream/internal-shadow-control
   e2080dc..cfd6c71  master     -> upstream/master
 * [nouvelle branche] misc-bug-fixes -> upstream/misc-bug-fixes
 * [nouvelle branche] pontoon    -> upstream/pontoon
dany@dellinux ~/FG/git_c172/c172p-detailed $ git checkout misc-bug-fixes
La branche misc-bug-fixes est paramétrée pour suivre la branche distante misc-bug-fixes depuis upstream.
Basculement sur la nouvelle branche 'misc-bug-fixes'
dany@dellinux ~/FG/git_c172/c172p-detailed $ git fetch origin
dany@dellinux ~/FG/git_c172/c172p-detailed $ git status
Sur la branche misc-bug-fixes
Votre branche est à jour avec 'upstream/misc-bug-fixes'.

rien à valider, la copie de travail est propre
dany@dellinux ~/FG/git_c172/c172p-detailed $ git remote -v
origin	https://github.com/dany93/c172p-detailed.git (fetch)
origin	https://github.com/dany93/c172p-detailed.git (push)
upstream	https://github.com/Juanvvc/c172p-detailed.git (fetch)
upstream	https://github.com/Juanvvc/c172p-detailed.git (push)
dany@dellinux ~/FG/git_c172/c172p-detailed $ git checkout origin
Note: checking out 'origin'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD est maintenant sur 0c98e43... README, dany93 contribution
dany@dellinux ~/FG/git_c172/c172p-detailed $ git status
HEAD détachée sur origin/master
rien à valider, la copie de travail est propre
dany@dellinux ~/FG/git_c172/c172p-detailed $ git fetch origin
dany@dellinux ~/FG/git_c172/c172p-detailed $ git status
HEAD détachée sur origin/master
rien à valider, la copie de travail est propre
dany@dellinux ~/FG/git_c172/c172p-detailed $ 

```

**Comment by Juanvvc** [comment]
The "detached HEAD" message means your are in a temporal (local) branch that will be deleted when you exit the branch. Run the command:

"git checkout master"

to go back to the master branch, and your temporal branch is deleted from your local PC (probably, not immediately but after a "git gc")

**Comment by dany93** [comment]
Thanks, Juanvvc

**Comment by onox** [comment]
The problem is:

```
dany@dellinux ~/FG/git_c172/c172p-detailed $ git checkout origin
Note: checking out 'origin'.
```

You're trying to switch to the "origin" branch. But there is no origin branch. If you do `git branch` you will see a number of branches, including the "master" branch. So, after testing my branch, you need to do `git checkout master` to switch back to your master branch.

```
dany@dellinux ~/FG/git_c172/c172p-detailed $ git fetch upstream
remote: Counting objects: 333, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 333 (delta 219), reused 137 (delta 137), pack-reused 78
Réception d'objets: 100% (333/333), 4.21 MiB | 3.77 MiB/s, done.
Résolution des deltas: 100% (234/234), done.
Depuis https://github.com/Juanvvc/c172p-detailed
 * [nouvelle branche] c172p-detailed-standalone -> upstream/c172p-detailed-standalone
 * [nouvelle branche] dual-control -> upstream/dual-control
 * [nouvelle branche] internal-shadow-control -> upstream/internal-shadow-control
   e2080dc..cfd6c71  master     -> upstream/master
 * [nouvelle branche] misc-bug-fixes -> upstream/misc-bug-fixes
 * [nouvelle branche] pontoon    -> upstream/pontoon
dany@dellinux ~/FG/git_c172/c172p-detailed $ git checkout misc-bug-fixes
La branche misc-bug-fixes est paramétrée pour suivre la branche distante misc-bug-fixes depuis upstream.
Basculement sur la nouvelle branche 'misc-bug-fixes'
dany@dellinux ~/FG/git_c172/c172p-detailed $ git fetch origin
```

1. First you do `git fetch upstream`. That's good. You can see that git downloads new data from Github, including new branches like "pontoon" and "misc-bug-fixes".

2. Then you did `git checkout misc-bug-fixes`. That's also good because you need to switch to the "misc-bug-fixes" branch in order to test it.

3. Then you did `git fetch origin`. In your case this doesn't make any sense. You're trying to download new data from your repository from Github. And you're the only contributor of your repository to Github, so there's no one else who is able to send new data to your repository.

To explain what `git fetch` does: basically it downloads data from the internet for you. If you do:

```
git fetch upstream
git fetch upstream
```

Then the first execution will either download data or download no data. The second execution will not download any data because it was already downloaded when you executed `git fetch` the first time. (Assuming there's basically no time between the two executions here)

To explain what `git pull` does: it first calls `git fetch` to download new branches and commits. And then does `git merge` to merge new commits with your commits.

**Comment by dany93** [comment]
Thanks onox, for this detailed explanation.
I realized and understood this during this day... (after my stumbling and research on the Internet, and thanks to your explanations, Juanvvc and you).

**Pull request merged**
