### PR TITLE
Bug 157

### PR DESCRIPTION
**Pull request by wlbragg**
@gilbertohasnofb, please check carefully.

Also, has something happened to the prop blur for the c172p. It seems like you only see the prop blur in very few conditions. Shouldn't you see it at normal cruse speed? This is something I noticed missing for awhile now, not just since I did this prop texturing.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks, I will check it out now!

> has something happened to the prop blur for the c172p[?]

Do you mean the circle created by the propelled when it's spinning? It has always been a bit temperamental to me, I'd say that 10% of the time it was not being displayed. The thing is I couldn't troubleshoot it so I didn't open an issue for that (yet). Do you have any idea under which conditions it is disappearing?

**Comment by gilbertohasnofb** [comment]
Perfect, thanks! :+1:

**Comment by wlbragg** [comment]
No, I notice it when I flipped upside down and it started to kill the engine, then I saw the prop blur and realized it must be missing from other conditions. I'll take a look at it and see if it is something obvious.

**Comment by gilbertohasnofb** [comment]
> I'll take a look at it and see if it is something obvious.

Ok, that sounds good. If you find something, please report on the new issue I opened for this: https://github.com/Juanvvc/c172p-detailed/issues/434

**Pull request merged**
