### PR TITLE
Bug 690: Improve instrument gauges

### LINKED ISSUE #690: Improve instrument gauges
- fix tachometer's range. The instrument should display a range between 300 and 3500 RPM, and the green arc should be between 2100 and 2700. 

- the VS instrument could be improved as well (no lines after "10") and the numbers "5" and "15" needs to be bigger.

- the black Artificial Horizon looks a bit different than ours in the source images 

- our oil pressure has a green arc and yellow arc. In some photo's the yellow arc is green and they don't have any other arc.

- check for low resolution gauges

For images, see: http://www.airliners.net/search/photo.search?aircraft_genericsearch=%3D%28%22cessna+172+skyhawk%2Fcutlass%2Fhawk+xp+%28t-41%2Fmescalero%29%22+OR+%22reims+f172+skyhawk%2Freims+rocket%2Fhawk+xp%22%29&airlinesearch=&countrysearch=&specialsearch=&keywords=172P+cockpit&sort_order=photo_id+desc&page_limit=15&daterange=&range=&thumbnails=&engine_version=6.0

For the discussion, see: https://github.com/Juanvvc/c172p-detailed/pull/689#issuecomment-180994034

### PR DESCRIPTION
**Pull request by onox**
Fixes #690 and #373

Most of the instruments are fixed. @gilbertohasnofb has created some new textures for some instruments. See https://github.com/Juanvvc/c172p-detailed/issues/690#issuecomment-181131002.

### CODE REVIEW

**Comment by wlbragg** [comment]
Please test the AI carefully. There has been a serious texture defect all this time and it looks like it is also carried over to the c182. I think I corrected it but as I am completely uneducated in the mechanics of this indicator I want to make sure it still behaves appropriately.

**Comment by wlbragg** [comment]
Bottom line is

Cleared up the light arc in the blue sky area.
Resized the 8-ball (Pitch object) to include more hidden area so it doesn't duplicate anymore at extreme roll (angles) and made it more of a one-to-one with the cage and the texture.

ai1

I'm not sure when or why it was ever changed. I noticed also that the AI in the fgdata c172p is textured more like this new edit I did than before I edited it. Before I edited it it was not a circle but an ellipse, both the object and the texture.

**Comment by gilbertohasnofb** [comment]
> Please test the AI carefully. There has been a serious texture defect all this time and it looks like it is also carried over to the c182.

I am aware of that. It seems to be perfect now though :smile: :+1:

**Comment by onox** [comment]
AI and TC look like they're fixed. I see the ADF now has a different background compared to the ring around it, so I guess that's the 'fix' for the ADF.

**Comment by wlbragg** [comment]
I'm done here!

**Comment by onox** [comment]
Nice work @wlbragg and @gilbertohasnofb! :smile:

**Comment by gilbertohasnofb** [comment]
Thanks! :+1: 

(by the way, I am back and I will be online during most of the day today, in case anyone needs me)

**Comment by gilbertohasnofb** [comment]
I am restoring this branch as I would like to make some very small modifications to the textures! I will create a new PR in a few minutes

**Pull request merged**
