### PR TITLE
shorten EMERGENCY Checklist titles and tabs2spaces

### PR DESCRIPTION
**Pull request by wkitty42**

### CODE REVIEW

**Comment by onox** [comment]
Could you create a PR which only fixes the titles? We have to cleanup the formatting in in separate PR later.

**Comment by onox** [comment]
Try to save the diff of the second patch, then go a `git reset --hard` to a certain previous commit (I think that's 1e09421713756a0336d9e790dae474eff3e2ef44) and then apply the patch you had saved. Then force push to your repository.

**Comment by onox** [comment]
I have some specific instructions:

1. `git format-patch dde6ac0651de5bc0ca1cec42e9b618cd22e416bf..8ac348e6c617fef114f4ab3ad72a674000a3d9af`

2. `git reset --hard 0635ad03d74bdc4a0abb30b240f7584462a7d4cd`

3. `git pull upstream master`

4. Then manually apply the patch.

Personally I think the "EMERGENCY" should be named "EMERG" instead of "EMGCY".

**Comment by onox** [comment]
@wkitty42 Was the upstream merge necessary to make this PR be able to get merged automatically? If not, say so, because then I have some easier instructions for you

**Comment by wkitty42** [comment]
i'm still learning how to do it... most of our work is done live and only stored in a repo for historical reasons... i can back the whole thing out and split the two if really necessary... i just saw those tabs when i was scrolling down to the emergency titles and fixed them to spaces as i went without thinking about it... i still have the original file here that i can start over with... i guess i can reset back to before... i don't know what point i was at before doing those two and then i also pulled from upstream which brought in two more...

**Comment by onox** [comment]
If you do that `git format-patch` above, then you'll see it's a fairly small patch. So it would be nice if you could modify your repository to only fix the titles.

**Comment by onox** [comment]
I agree with you that tabs needs to be replaced with spaces, but this should be done in one massive commit later, perhaps after the feature freeze.

**Comment by wkitty42** [comment]
just to be clear on how i've normally been doing...

git fetch upstream   (pulls from juanvvc/c172p-detailed)
git merge upstream/master  (brings me even with juanvcc/c172p-detailed/master)
git push origin (pushes to my fork on github)

in this case, i made the edits, copied them to my local repo and then
git add c172-checklists.xml
git commit
git push origin

then i went to my github and did the pull request... we talked about the titles which i fixed and repeated the above...

then i saw that i was behind juanvcc so i did the first set of commands again... only this time a editor popped up when i did the "merge upstream/master" which i've never seen before... i think it was because my repo was ahead of upstream...

so, whatever it takes... i can back up all the way and start again doing one pull request for each, tabs2spaces and shortening the emergency checklist titles... i think i'll need help just backing up to before i did my first alteration to the checklist file...

**Comment by onox** [comment]
Just do the instructions I typed above :smile: And please forget about the tabs2spaces PR. We'll do that later.

**Comment by wkitty42** [comment]
ok... i was typing and didn't see your posts :laughing: i'll try doing that format patch method ;)

**Comment by onox** [comment]
Yes, it will generate a `0001-*.patch` file. Don't try to apply the patch (with `git am` or `git apply` because it will fail), but it will show you what to modify.

**Comment by wkitty42** [comment]
i guess it automatically closed when i pushed the new up ??

**Comment by onox** [comment]
I think so yeah.

**Comment by onox** [comment]
You did a `git push --force`, right?

**Comment by onox** [comment]
I'll create an issue for the style formatting.

**Comment by wkitty42** [comment]
yeah, i did the --force... now i've done the add, commit, push and generated a new pull request... #261

**Pull request closed without merging**
