### PR TITLE
Window latch backing

### PR DESCRIPTION
**Pull request by wlbragg**
latch

### CODE REVIEW

**Comment by wlbragg** [comment]
Oops, I thought I started with a clean master but see I have the no-preview commit. What should I do when I make this error, keeping in mind I am using a limited GUI shell? Although I do have the command line interface also.

**Comment by gilbertohasnofb** [comment]
Maybe you can save your modifications elsewhere, rebase this branch and the commit the modifications again. Or (more wisely) you can wait for @onox's advice :smiley:

**Comment by wlbragg** [comment]
For one I need to change my local workflow. I have a tendency to work from master then save it to a branch after I am done and committed locally. I need to branch master first and them make the changes to the branch. I have to remember from now on to do that.

**Comment by gilbertohasnofb** [comment]
> I need to branch master first and them make the changes to the branch. I have to remember from now on to do that.

Yep, I always use other branches for modification, including some local branches for testing random stuff. I screwed that up so many times that now I absolutely always do a `git status` to check which branch I am and what's the situation before a `git checkout -b <newbranch>`.

**Pull request closed without merging**
