### PR TITLE
Bug 700: Problems with the DME

### PR DESCRIPTION
**Pull request by wlbragg**

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
You forgot to add to the description that this PR closes https://github.com/Juanvvc/c172p-detailed/issues/700

**Comment by gilbertohasnofb** [comment]
Looks good to me! :+1:

**Comment by wlbragg** [comment]
Thanks.

Did you see the LATE additions I thought we might add to the NEWS.md

>Amphibious plane improvements:
    Added two metal **reinforcement** bars in the cockpit

>New sounds:
   **Wheel damage**

>Improved textures of instruments, primer, and cabin air/heat levers in cockpit, **flap lever animations**.

>**Improved shadow and reflection cubes**

Didn't you add wheel damage sound?
Should I update an PR?

**Comment by wlbragg** [comment]
Also where to give credit to @jarlarntzen?

**Comment by gilbertohasnofb** [comment]
> Didn't you add wheel damage sound?

Yes, we did add the wheel collapse + scratching sound

> Should I update an PR?

I guess a separated PR

> Also where to give credit to @jarlarntzen?

`README.md` is the place we add our contributions. Probably we can also add D-ECHO for the 3D model of the pitot tube + cover.

**Comment by gilbertohasnofb** [comment]
And please check https://github.com/Juanvvc/c172p-detailed/issues/704, is this related to the new cube map or is it something else? Never noticed that before

**Comment by wlbragg** [comment]
OK, I'll do them both in a PR.

#704, OK I'll check.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by onox** [comment]
Commits backported to `release/2016.1`.

**Pull request merged**
