### PR TITLE
Begin to add more autopilot tooltips

### PR DESCRIPTION
**Pull request by geoffmcl**
If this looks good hope it can be merged... thanks...

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@geoffmcl thanks for the contribution, I just a test now and I have only some recommendations before we merge this:

- IMO, `Autopilot Up On` and `Autopilot Dn On` doesn't make much sense. We should simply have `Autopulot Up` and `Autopilot Down` I think.
- If possible, we could also add tooltips for the `ARM` and `BARO` buttons.

Do you think you could have a look on these?

**Comment by geoffmcl** [comment]
@gilbertohasnofb after seeing them on my screen decided they were all TOO BIG ;=))

Have now reduced them to a curt `ALT on/off`, which I think looks better...

One improvement I would like but do not know how to do, and that is to add whether going `On` or `Off`... seem to remember other tooltips that did this...

TODO: And yes at the moment missed `ARM` and `BARO`

**Comment by geoffmcl** [comment]
Took the xml sample from `Beacon: %s`, and added it the `ALT` toggle...

It works ;=))

**Comment by gilbertohasnofb** [comment]
Much better, thanks!

> TODO: And yes at the moment missed ARM and BARO

Should I wait for you to do that before merging? I think a single PR would probably make sense here.

**Comment by onox** [comment]
I think a single PR is a good idea. Just add more commits to your geoffmcl:master branch and they should show up here automatically.

**Comment by geoffmcl** [comment]
@gilbertohasnofb have now added ARM and BARO...

Also converted HDG, NAV, APR, REV, like ALT to on-off toggles...

This seems the end of this series of autopilot tooltips... maybe ready to merge?

**Comment by gilbertohasnofb** [comment]
@geoffmcl All is working fine now, thanks for your contribution!

**Pull request merged**
