### PR TITLE
ALS Flashlight

### PR DESCRIPTION
**Pull request by wlbragg**
It's done. Requires a new fgdata pull as of today.

### CODE REVIEW

**Comment by wkitty42** [comment]
i'm fully updated... just waiting on the merge so i can pull a new craft :smile_cat:

**Comment by wlbragg** [comment]
Seeings how this is a minor addition, I'll merge it now so you can have at it.

**Comment by wkitty42** [comment]
:+1:

**Comment by onox** [comment]
@wkitty42 Next time you can do things like download https://github.com/Juanvvc/c172p-detailed/archive/ALS-Flashlight.zip or do: `git checkout ALS-Flashlight` if you have a git clone of this repository.

**Comment by wkitty42** [comment]
i have two git repos of the craft... you have to if you're going to do any pull requests but anyway the problem is that i'm flying the craft at the moment... my second round (aka return trip) of "Cross Country USA - Hatteras to Oxnard"... if there was a way to save the state of the sim and come back to resume exactly, i'd do it but... i wanna finish this flight and then i'll be able to restart the sim with the new c172p files in place :wink:

**Comment by onox** [comment]
It was just for your information, so that in the future a PR doesn't have to merged in order to test it :stuck_out_tongue_winking_eye:

**Comment by onox** [comment]
@wlbragg I tried to pull latest fgdata, but I'm not getting any updates. Latest commit is "Make METAR string editable in GUI.  Fix bug 1764".

**Comment by wkitty42** [comment]
yeah, yeah, no problem :lol:

**Pull request merged**
