### PR TITLE
Bug 701: Reduce interior side glass reflection.

### LINKED ISSUE #701: New glass reflections look bad at night
New glass reflections look bad at night:

fgfs-screen-001

They are really strong. Also, as I discussed previously with @wlbragg, we should recreate the reflection cube using 4X-CHV's cockpit (as it's the default livery) as well as add the instruments to the reflection (see #699 )

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #701 

There are two ways this can be done. This was the fastest and the easiest. The other way would be to change the reflective qualities of the glass in Blender, but currently it matches the front glass so I thought this might be more appropriate.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Tested, it looks much better IMO. I would normally merge this but given the situation I'd rather hear from @onox before doing it...

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
This PR closes https://github.com/Juanvvc/c172p-detailed/issues/701

**Comment by jarlarntzen** [comment]
Hi.
Would just like to say that I've made a new commit of 'reflection_*.png' cube with black instrument panel, instruments and darker sky color which has reduced and even eliminated the strong cubemap reflection at night and late evening. 
https://github.com/jarlarntzen/c172p-detailed/commit/60799f76c1c62fccc3f010a4adf37db674fd36da

**Comment by onox** [comment]
@wlbragg You can use `--author="Name"` when you use `git commit` to set the name of the author.

**Comment by onox** [comment]
@wlbragg I have force pushed the branch (amended last commit).

**Comment by onox** [comment]
I'll backport this one as well.

**Comment by onox** [comment]
Commits backported to `release/2016.1`.

**Comment by jarlarntzen** [comment]
Thanks @onox !

**Pull request merged**
