### PR TITLE
checklist: Add items for float planes

### PR DESCRIPTION
**Pull request by onox**
Add items from #269 to checklists for float planes.

@tigert @wezzer What should be the takeoff speed and landing speed for float planes?

### CODE REVIEW

**Comment by wezzer** [comment]
I believe the speeds are pretty much the same, but operating procedures are a bit different. @tigert has already provided the operating procedures here: https://github.com/Juanvvc/c172p-detailed/issues/269#issuecomment-110267638

**Comment by onox** [comment]
PR can be merged if the items are OK.

**Comment by onox** [comment]
@gilbertohasnofb Could you test this PR as well?

**Comment by gilbertohasnofb** [comment]
Same question: can this branch be deleted or is there any other float plane operation related issue to be implemented?

**Comment by onox** [comment]
I didn't implement the "Balked landing (go-around)" checklist (it would be one item) and item 3 and 5 of the takeoff checklist. They are bit useless because "the sim starts to jump the nose up and down" (in item 5) doesn't apply anymore; you could hold yoke full aft and just takeoff when airspeed becomes high enough.

**Comment by wkitty42** [comment]
is there any way to limit these float craft checklist items so they only show then a float craft is in use?

**Comment by onox** [comment]
Unfortunately no.

**Comment by wkitty42** [comment]
ugh... that bites... oh well... it was worth asking about...

**Pull request merged**
