### PR TITLE
small improvements to OH-CTL and N301DP panels

### LINKED ISSUE #426: Small improvements to OH-CTL and N301DP panels
Small improvements to OH-CTL and N301DP panels:

- addition of OH-CTL callsign
- remove hard textured screws from N301DP (on a second thought they don't look good as I first imagined and the panel looks better plain gray)

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Small improvements to OH-CTL and N301DP panels:

- addition of OH-CTL callsign
- remove hard textured screws from N301DP (on a second thought they don't look good as I first imagined and the panel looks better plain gray)

Closes #426

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox how can I make a PR to automatically close an issue it solves?

**Comment by gilbertohasnofb** [comment]
Well, I am merging this myself since it's only related to textures and no one else is doing it :wink:

**Comment by onox** [comment]
> how can I make a PR to automatically close an issue it solves? 

Just reference the issue in your PR. That's why I always write "Fixes #\<number\>"

**Comment by gilbertohasnofb** [comment]
Thanks, @onox, next time I will do that!

**Pull request merged**
