### PR TITLE
Bug 715: Improve kr87, kap140  and DME displays

### LINKED ISSUE #715: Improve kr87, kap140 and DME displays
Currently our DME display is completely black if turned off, but actually in RL you can see the six spaces where the numbers are displayed, as well as the words MILES, MIN and KTS and two circles:

I am talking about the green areas specifically:

dme

In our plane, if a digit is being illuminated, then the display behind it is visible. Not how the background behind each of the three 9's is not fully black:

fgfs-screen-001

But as soon as the number isn't illuminated, the display also disappear:

fgfs-screen-002

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #715 

I didn't create an issue for this. If anyone wants to rename this or if we want to add the potential dme changes before merging, that be OK. I just wanted to get it pushed.

### CODE REVIEW

**Comment by wlbragg** [comment]
fgfs-screen-002

**Comment by wlbragg** [comment]
@gilbertohasnofb, @onox, I don't know if it's worth trying to adjust the color of the autopilot digits any farther. All I did was copy that section of kap10.png to a new layer, change color level and merge it back on top and export. It looks like it is still slightly off color, but closer that it was.

**Comment by wlbragg** [comment]
Don't merge this, I just noticed the digits in the dme are mirrored again. I don't know why this keeps doing this. I'll fix it tomorrow.

**Comment by onox** [comment]
@wlbragg Please create an issue for this so that it can be tracked. Add the issue to the 2016.3 release milestone.

**Comment by gilbertohasnofb** [comment]
> I don't know if it's worth trying to adjust the color of the autopilot digits any farther. All I did was copy that section of kap10.png to a new layer, change color level and merge it back on top and export. It looks like it is still slightly off color, but closer that it was.

Let me take a look at that, I will try to do so tonight. Also, I left a couple of comments here: https://github.com/Juanvvc/c172p-detailed/issues/715#issuecomment-220269425

**Comment by gilbertohasnofb** [comment]
@wlbragg given that the digits are inverted, would you mind reverting that commit that flipped them? It's always very difficult to judge which ones got inverted and which ones didn't like we did last time, and I'd rather revert it to be sure that the ADF has the display completely correct

**Comment by wlbragg** [comment]
>Please create an issue for this so that it can be tracked. Add the issue to the 2016.3 release milestone.

How about combining it with the DME work? Either way, you choose!

>would you mind reverting that commit that flipped them? It's always very difficult to judge which ones got inverted and which ones didn't like we did last time

Yes, I guess, not sure what you mean by revert (technically)?

What I am doing is grabbing the previous ac, manually changing the ambient number and making a new commit of that.

While I am at it I am going to see if the original blend, opened that way (bad mirroring) or somehow got that way after saving the new one. We need to fix this so it quits happening. Like I said, I did nothing to cause this and we know it already happened once before.

**Comment by wlbragg** [comment]
I'm not sure what do do here. I can't manually edit the original ac, is to complicated.
If I revert we loose the improvements and we leave a buggy blend.

I ran some tests and this is what I found out.
If I open the original blend, it has mirroring problems.
If I import the original ac it has mirroring problems.

I corrected the easily seen mirroring problems (ANT, FRQ and ET) saved then in the blend and exported them.
Then I tried to open each one (blend and import ac) and they remained correct.

So if we want this to match the rest of the equipment then we need to do this the hard way and figure out which, if any, of the digits are mirrored incorrectly.

**Comment by wlbragg** [comment]
This is really frustrating. I got all the digit flipped and corrected and all that is left is the knobs. Well there is obviously some trickery involved with displaying them correctly and I'm not sure I can figure it out. It looks like they lost part of their uv mapping. But it's not a simple straight forward mapping and export.

**Comment by wlbragg** [comment]
On further inspection, there is either a real trick to using what is in the blend, or it is missing something. I think it is missing something. I may have to rebuild the knobs.

**Comment by wlbragg** [comment]
Got it figured out and it looks much better. It's been broke for who knows how long. I am going to combine this with the DME edits if there are no objections.
The only digits not guaranteed verified are the 1000 digits
fgfs-screen-005

**Comment by gilbertohasnofb** [comment]
> How about combining it with the DME work? 

Combining the DME and ADF in a single PR sounds fine to me, since it is all about "improving the radio stack", right?

> The only digits not guaranteed verified are the 1000 digits. I could use some help figuring that out, I don't know how to tune it to exceed 999?

I think the ADF frequencies are up to 1xxx only, so the first digit is either a 1 or blank (I think they range from 190 to 1750 kHz).


And by the way, the ADF radio suffers from the same issue as the DME: when a digit is not being displayed, the background of that digit should be dark grey and not full black. Should I try to create a background texture for both of these radios, so when a digit disappears we still can have the same colour?

**Comment by gilbertohasnofb** [comment]
@wlbragg I pushed some work on this branch, so please pull before you continue working. I adjusted the ADF KR87 display colour, so now when the digits are not displayed the background display has more or less the same colour (not perfect because the objects likely have different light reflection properties but it's quite acceptable IMO).

I also pushed a new texture for the DME display:

display

So once this is applied ONLY to the background, i.e. the object highlighted in green below, it will look like the real thing:

fgfs-screen-001

real photo:



What do you think?

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry, just one more thing I noticed: the DME has basically two groups of digits, one in the left and one in the right (in the image below, the left displays 10.6 while the right displays 110):



So, the left-hand side group is a teeny weeny higher than the right-hand one. Maybe bringing the left group a bit down would make it look better.

Yeah, I am nitpicking today.... :smile:

**Comment by wlbragg** [comment]
@gilbertohasnofb, I don't think the left digits are higher than the right. I checked the pos in Blender and they are all the same. Maybe it is an optical illusion? I can't see it myself.

**Comment by wlbragg** [comment]
Are we done?

**Comment by gilbertohasnofb** [comment]
Looking really great so far, thanks a lot @wlbragg! :smile: 

> I went ahead and created the knob texture so I could finish this up.

No problems, looks good. I will add it to the `.xcf` file and upload it to the textures repository.

Also, I pushed another commit, as now that you UV mapped the DME display I am able to fine tweak its colour. Please do a pull before continuing to work.

But about the UV-map, could you please take another look at it? I think the UV-mapping is slightly off, see:

fgfs-screen-001

**Comment by gilbertohasnofb** [comment]
Also, this DME model should have a chrome rim around the octagonal thing. Our used to be silver but now it's black. See the RL model and compare with the picture above:

**Comment by wkitty42** [comment]
On 05/20/2016 01:21 AM, wlbragg wrote:
> @gilbertohasnofb, I don't think the left digits are higher than the right. I
> checked the pos in Blender and they are all the same. Maybe it is an optical
> illusion? I can't see it myself.
 >

is the decimal point too low, then? or if it is an optical illusion, could the 
decimal point be too far forward and not back with the digits? the bottom of the 
decimal should be in line with the bottom of the digits...

**Comment by wlbragg** [comment]
@gilbertohasnofb, any comment about the decimal?

Also, don't know how I lost the chrome frame, I'll fix it.

**Comment by wkitty42** [comment]
remember, too, that the decimal is part of the LED block as can be seen in this image...
[https://www.tindie.com/products/rajbex/serial-8-digit-7-segment-led-display-yellow/](url)
it is the dot to the bottom right of each set of seven segments... in other words, it should be lit only when the device is powered on and it should follow the brightness of the digits...

**Comment by gilbertohasnofb** [comment]
@wlbragg @wkitty42 the decimal point is in the correct position for this model, see:

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry, but I just now found out that there is also a model with a black octagonal rim:



So I'd say just keep what we current have, it looks nicer than the previous silver one IMO.

Also, I found out that @dg-505 has developed a nice looking model of this same DME, though without the texture for the display. See: https://forum.flightgear.org/viewtopic.php?f=4&t=21965&start=540#p271655

Finally, I am trying to figure out what those two circles in the display do, but I can't find the manuals online. Any ideas?

**Comment by wlbragg** [comment]
I already changed it, I think it looks better silver. Please see my new post in the issue thread #715

**Comment by wlbragg** [comment]
I didn't get your change prior to my work so I had to merge it, please double check that I still have your changes in the branch. I've been touching many parts and it was starting to  get confusing. Now we can take a really hard look and decide the final version. This will at least give you something to compare to.

**Comment by wlbragg** [comment]
>Yeah, my change to one of the textures got undone, your commit 6fb1900 did it

Dang it, if we don't hear from onox before tonight, I can manually put it back with a new commit.

**Comment by wkitty42** [comment]
after beating on numerous search engines for some sort of documentation on the KI-266 DME display (part# 066-3047-00), i've finally just written an email to the BendixKing technical support folks asking if they can provide documentation or at least say what those two lights above the pushbutton are for and how they are controlled... we'll see what happens ;)

**Comment by gilbertohasnofb** [comment]
>  i've finally just written an email to the BendixKing technical support folks asking if they can provide documentation or at least say what those two lights above the pushbutton are for and how they are controlled...

That's great, thanks a lot! :+1: Hopefully they will be nice to give us an answer :smile:

**Comment by wkitty42** [comment]
i don't expect anything before monday but... yup! :)

**Comment by wlbragg** [comment]
>Yeah, my change to one of the textures got undone, your commit 6fb1900 did it.

Are you sure? The one that remains is the one that has the lighter colored "glass" where the digits display. Isn't that the newest one you committed?

Also, I just discovered the ra-irradiance wasn't actually working on the radio stack. Somehow the code to activate it was missing. You can't see it very well in this picture but you should be able to notice a huge improvement in the sim now at night with the instrument and radio light turned all the way up. Enough so the back lighting from the radio lt knob really isn't necessary to see where the knobs are in the dark.

Now one more thing to consider. Look at the  ADF HD knob (heading knob), heading offset and heading bug on the left instrument panel, see how bright they are compared to all the other knobs on the instrument panel side and the radio stack? We need to verify that is correct, I think maybe it is not, I think they should be like the rest of the knobs with only ra-irradiance affect applied.

ra-irradiance

**Comment by wlbragg** [comment]
There was another bug in the radio stack lighting system. A material emission wasn't being applied at 0.0 when it should have been. Can someone please verify this was the correct fix?

Does anyone know if the amphibious gear deploy panel was ever tied into the electrical system, it appears it wasn't. If not we need to do that.

**Comment by gilbertohasnofb** [comment]
> Are you sure? The one that remains is the one that has the lighter colored "glass" where the digits display. Isn't that the newest one you committed?

You are right, the correct file is in the branch right now (I just double checked it by substituting it for the one on my hard drive which I am sure is the correct one, and then doing a `git status` showed me nothing was changed). So everything is fine, let's just keep it as it is now.

> Also, I just discovered the ra-irradiance wasn't actually working on the radio stack. [...] Enough so the back lighting from the radio lt knob really isn't necessary to see where the knobs are in the dark.

This is great news, @wlbragg!! 

> Look at the ADF HD knob (heading knob), heading offset and heading bug on the left instrument panel, see how bright they are compared to all the other knobs on the instrument panel side and the radio stack? We need to verify that is correct, I think maybe it is not, I think they should be like the rest of the knobs with only ra-irradiance affect applied.

Looks to me the ADF heading knob (HD label) shouldn't be illuminated as there is no backlight for it. You could also check if the two knobs of the heading indicator (HI) are also fine, as they look quite bright to me but maybe that's just the re-irradiance effect, in which case it would be all fine with me!

> Does anyone know if the rocker switches on the lower console (master Alt, Bat, Landing, Taxi, Strob, Nav, etc.) are suppose to be back light or any kind of illumination?

I am quite sure they are not backlit at all, they are completely solid plastic, see:

**Comment by onox** [comment]
> Yeah, my change to one of the textures got undone, your commit 6fb1900 did it. @onox can you help us remove that commit?

6fb1900 is a merge commit and it merges "better colour for DME display" by @gilbertohasnofb. So you want to undo your own commit? You can do `git revert THE_COMMIT_ID`. It will add a new commit reverting the changes made by that particular commit.

**Comment by gilbertohasnofb** [comment]
> 6fb1900 is a merge commit and it merges "better colour for DME display" by @gilbertohasnofb. So you want to undo your own commit? 

No, I don't want to remove my commit. Sorry this was my mistake, I thought @wlbragg had reverted that texture to a previous one, but actually it's all good in this branch now. Sorry for the mess.

**Comment by wlbragg** [comment]
>I am quite sure they are not backlit at all, they are completely solid plastic, see:

You may very well be right, but I could still see that having a light source the illuminates or makes the red plastic glow. I'll settle for your thoughts on it until proven otherwise.

I did find this on the squawk though
cessna 152 panel

Notice the ident numbers and the mode select "choice" is lit-up.

I'd like to see if the mode select "choice" in the DME is also lit-up.

**Comment by gilbertohasnofb** [comment]
> You may very well be right, but I could still see that having a light source the illuminates or makes the red plastic glow. I'll settle for your thoughts on it until proven otherwise.

Well, but there is another thing to support "my theory": there would be no light to illuminate the master switch since this very switch is what turns the battery on! In other words, it would be lit only in the position ON. I am really 99.9999% sure about it; I also checked it on other 172 and similar Cessna models of the same period as ours in other simulators, and none of them have masters, avionics or circuit breakers illuminated with back light.

> I'd like to see if the mode select "choice" in the DME is also lit-up.

That looks cool! How would we proceed to do that? I guess you'd need some sort of texture for it, right? I see that the `kt76a.png` has the labels "hard coded" above the background, should we somehow separate them, so that they can be individually lit (since only the selected mode it lit)? Give me the instructions and I can work on that! :smile:

**Comment by wlbragg** [comment]
Just pushed a commit for it. I need to clean it up though. I am vacillating on whether or not to illuminate the Off choice?

I have to leave now, you can check it out and let me know what you think.

**Comment by wlbragg** [comment]
> there would be no light to illuminate the master switch since this very switch is what turns the battery on! 

In this case probably. But that's also why I'm questioning the "Off" on the kt76. Sometimes equipment is wired into the master power and as soon as you turn on the ignition key, or in this case the master bat/alt switch, they receive power to things like the mode selector, possibly even the "Off" legend even when it is set to "Off".

So That is the next question, do we illuminate the "off" in that manner?

**Comment by gilbertohasnofb** [comment]
> So That is the next question, do we illuminate the "off" in that manner?

Yeah, I see your point. I suppose we can make a "guess" right now and leave it not illuminated as you say, and later change it if we find the correct information.

**Comment by gilbertohasnofb** [comment]
A couple of things:

- also guessing here, but I would thought the "ident" button in the transponder wasn't backlit

- I think the DME still needs to have the UV mapping corrected, see: https://github.com/Juanvvc/c172p-detailed/pull/760#issuecomment-220543546

- one small issue: during the day, now we can correctly see that the DME has several tiny displays (two rectangles + 2 circles) as well as that the ADF has a single display of the size of the whole equipment:

fg-1

But because these displays are "hard coded" into the main texture of these radios, when the night falls the illumination of the displays make them disappear, while the background of individual digits still look like displays:

fg-0

So note for instance how in the night the ADF in the image above looks like having 5 individual displays ("ANT", "1779", "FRQ", "6" and "41") instead of a single one.

How could we fix this? Would a better approach be to create these displays as rectangles in Blender instead of trying to fix them with textures?

**Comment by wlbragg** [comment]
>"ident" button in the transponder wasn't backlit

I think it is. It looks to be a clear glass or plastic with either an orange light or orange tint to the glass or plastic? See the image in https://github.com/Juanvvc/c172p-detailed/pull/760#issuecomment-220794919.

>DME still needs to have the UV mapping corrected

Yep thanks for the reminder, I remembered that again last night.

>How could we fix this? Would a better approach be to create these displays as rectangles in Blender instead of trying to fix them with textures?

Maybe, let me take a closer look and see what comes to mind. I haven't taken the time to see how noticeable it is. Apparently it's enough for you bring it up though.

Here is the kma20 so far. I have two more hurdles or questions.

kma20

1) Two things that use to work in the original ac, now don't work in the new ac. I'm guessing old techniques in Blender weren't accounted for in the import script?

The two things that don't work are the picks and the last toggle on the right.

I've never seen these types of pick objects before. They are more like a 4 point object instead of 4 sided. Anyone know what they are and how to work with them? If not I am going to have to convert them to what we normally use. Again I am guessing the import/export script doesn't quite know how to handle them.
The toggle switch on the far right lost its identity in FG. It's not being recognized as an object. The code has no effect on it? I am completely stumped as to why it isn't hot anymore.

2) I want to confirm whether or not any of the text legend is backlit.

**Comment by wlbragg** [comment]
I just noticed a new Blender import script may handle the point objects. We'll see!
Ver 2.10, points fixed in 2.8.

**Comment by wlbragg** [comment]
ARRRRRGGGG!
The new version of the script appears to fix the issues, which just caused me to loose a days worth of work! Why didn't I think of this 24 hrs ago?
ARRRRRGGGG!

**Comment by wlbragg** [comment]
OK, using the new import script I am already finished with this piece of equipment (with the exception of adding any "Radio LT" illumination, if any). One positive of doing all this work is the text legend in each piece is closer to the same lighting level now, you can see the text and knobs better. Even at dark illumination.
kma20

**Comment by wkitty42** [comment]
when you speak of the import script, are you talking about the one from nicolatis?

is that the same io_scene_ac3d one that we have in the repo now?

should the one in the repo be updated?

what are the differences between the two if they are not the same?

**Comment by wlbragg** [comment]
Yes
Not sure, it needs to be ver 2.10
If not 2.10, yes
See the link above to the thread about it, it has the change log.

**Comment by wlbragg** [comment]
@wkitty42 that is part of my problem, not paying attention. If the script saved in the repo is 2.10, then I am even more of an idiot for not realizing it.

**Comment by wkitty42** [comment]
all i know is it is the io_scene one but i've just gone digging and from the 
__init__.py file it looks like v2.0 by chris marr for blender 2.6.0...

**Comment by gilbertohasnofb** [comment]
I think you are right, the ident is backlit in your image above, please ignore my previous comment.

Everything else is looking really good!

**Comment by gilbertohasnofb** [comment]
@wlbragg is there still something missing in this PR? Also, about the different brightness curve for some displays when using the RADIO LT knob, was there any luck finding what is causing that? (the COMs and NAVs get brighter much faster than the DME, for instance)

**Comment by wlbragg** [comment]
>different brightness curve for some displays when using the RADIO LT knob,

No I took a brief look for it and it wasn't readily apparent. It my be the blend settings. It may take me some time to find it.

**Comment by wlbragg** [comment]
We can commit this and open a new issue for the "brightness curve" if you want. As this PR is quite large as it is.

**Comment by gilbertohasnofb** [comment]
> We can commit this and open a new issue for the "brightness curve" if you want. As this PR is quite large as it is.

Sounds like a plan. I will just double check everything is working well in this PR and I will merge it.

**Comment by gilbertohasnofb** [comment]
@wlbragg it's all very good, but we forgot to do one thing. We spoke about removing the back light from all knobs, but we missed the ADF and maybe the HI as well (I write maybe because it might be just irradiance, though it looks too bright for that):

fgfs-screen-006

fgfs-screen-007

Do you think you could take a look at it before we merge?

**Comment by wlbragg** [comment]
Yes, I'll do it now.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
BTW, I created https://github.com/Juanvvc/c172p-detailed/issues/770

**Comment by wlbragg** [comment]
I saw that, thanks. I'm suddenly having issues in my console, are you seeing any of this in your console see #765

**Comment by wlbragg** [comment]
Do we still want this knob text to be "orange", that is the color of the texture?

ki227_228

**Comment by gilbertohasnofb** [comment]
> Do we still want this knob text to be "orange", that is the color of the texture?

There are some knobs with that colour, but I am yet to see one of those in a 172. Our ADF model is more like this:



So please push your modifications to the illumination and let me improve that texture. Just let me know once you have pushed so I can push the texture and merge this PR.

**Comment by wlbragg** [comment]
The hi is done also.
tst2

I'm done, all yours.

**Comment by gilbertohasnofb** [comment]
Okay, thanks!

**Comment by gilbertohasnofb** [comment]
fgfs-screen-001

@wlbragg what do you think? I think it's much better. If you like it I will push it and merge this PR!

**Comment by gilbertohasnofb** [comment]
Pushed and merged. Great work, @wlbragg! :tada:

**Pull request merged**
