### PR TITLE
Updated c172p-set.xml (authors, status, rating)

### PR DESCRIPTION
**Pull request by dg-505**
Status: Advanced production

Rating:
- FDM :star: :star: :star: :star:
- Systems :star: :star: :star: :star: :star:
- Cockpit :star: :star: :star: :star: :star:
- Model :star: :star: :star: :star:

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I might have missed something but how came our model has been downgraded from 5 stars to 4 stars?!

**Comment by dg-505** [comment]
See issue #240

**Comment by gilbertohasnofb** [comment]
Thanks, I didn't follow that issue very closely and I totally overlooked that the model was going to be downgraded. Well, if that's what the majority thinks, then fine with me, but by the standards of the other aircraft with 5 stars model I'd say ours should be up there with them.

**Comment by dg-505** [comment]
Yes I know that other models have also 5 stars, but the wiki says "As a guideline, a "5" model is as realistic as possible given the available rendering technology." So to meet  this requirement, I thought 4 stars would match better.

**Comment by gilbertohasnofb** [comment]
Sure, as I wrote I've seen you guys discussed it (sorry for missing it before), so of course I accept it. But if I may ask you, what improvements do we need to the 3D model to get a 5 stars? I have been discussing issues https://github.com/Juanvvc/c172p-detailed/issues/216 and https://github.com/Juanvvc/c172p-detailed/issues/6 with ludomotico and those will surely make the 3D model look better.

**Comment by dg-505** [comment]
IMHO http://wiki.flightgear.org/North_American_P-51_Mustang. *That* model deserves 5 stars.

**Comment by gilbertohasnofb** [comment]
Sure, that is an outstanding model. But I don't think the 5 stars is deserved by a single airplane only, and as I wrote before there are similar planes to ours with 5 stars models. But my question was meant to be  more practical actually: do you think we lack some specific 3D details? Do you think our model is not high-poly enough? I am just thinking in terms of improvements, that's why I ask.

**Comment by dg-505** [comment]
1 example: 
unbenannt

**Comment by gilbertohasnofb** [comment]
@dg-505 Jonathan, I really hope you are not getting me wrong. I understand your opinion and I understand this has been discussed and I am not trying to change the rating of the aircraft (hence why I already merged this PR). I am simply trying to brainstorm some ideas on how to improve the 3D models, particularly because you know quite a lot about 3D modelling and I know next to nothing! 

About the example you posted above, that's a good point and should be simple to fix and it won't make the model any heavier (it will be just a couple more of polygons to make the hole I guess). So I opened a new issue for that: https://github.com/Juanvvc/c172p-detailed/issues/259

If you do think of some other things like this example above, please consider opening issues for them so we can continue to improve this plane.

Cheers!

**Comment by dg-505** [comment]
I'm not getting you wrong at all. I'm phoning, so I'm a bit curtly atm.

**Comment by gilbertohasnofb** [comment]
No problems :smile: 

(I added your second picture to the same issue)

**Comment by dg-505** [comment]
Roger :+1: :smile:

**Comment by onox** [comment]
How many vertices does the model has? About 17000? That's very low poly.

**Comment by dg-505** [comment]
The c172p.ac has 16,945 vertices and 16,406 surfaces.

**Comment by gilbertohasnofb** [comment]
Of course we must keep in mind that since this aircraft will be the default FG plane from now on, we should keep it as low poly as possible. IMO the exterior is looking good (still has room for improvements without increasing too much the poly count) and the plane run well on modest computers.

**Comment by Juanvvc** [comment]
I also prefer having a low polys exterior model, at least during the v3.6 version, and we can check how it goes. We can decide adding extra details after the freeze.

In any case, iirc, the fuselage has probably less vertices than the old model since I removed many repeated vertices. This is compensated by the cockpit, whit many additional objects and vertices. This is why issue #30 probably deserves a visit before the freeze: we have added many models that are probably still visible also in multiplayer.

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
