### PR TITLE
Restoring c172p historical commit logs

### PR DESCRIPTION
**Pull request by IAHM-COL**
This merge does no change to current code, but restores all previous contributions to the c172p project. The FG hallmark aircraft.

(this merge goes for all three active branches)

### CODE REVIEW

**Comment by Juanvvc** [comment]
I'm hesitant to merge this. The history of the original must be preserved with the original c172p. In fact, once merged into FGDATA, what will be lost is our history. If I understand correctly, the c172p-detailed project will be a single commit into FGDATA. It must be like this, there are lots of files we are not going to submit as all the .blend files. It is OK for me because our history is preserved in this repository, not in FGDATA. This is the same with the original c172p: we don't know the history inside any private repository it could live during its development.

Another example: wlbragg copied the pontoons from another aircraft and we are not preserving the complete history of these pontoons inside the c172p-detailed project. As far as the c172p-detailed project goes, they appeared one day. This is the same with the many other things we have reused, such as instruments or the walkers.

I won't merge this pull request, but I don't have a strong opinion. If any other contributor wants to merge this, go ahead.

**Comment by IAHM-COL** [comment]
What you say Ludomo is correct. 
The "detailed" history will not be passed over FGDATA.

All this does is restore the history on the detailed project (so it is the other way around)

As you can see there is 0 changes to the code for every branch, so in principle it is a totally harmless merge. On the other hand the commit restoration provides several advantages, including GPL patternity compliance, and the ability to troubleshoot, and look for how methods and steps were implemented. 

Merging this also does not prevent making a zip for merging to FGDATA without the sources.

I am totally confused about what is the hesitations. After merging this, we can merge my "rename" branch back, which will be a large step into creating the zip for merging back

**Comment by Juanvvc** [comment]
My hesitation is mainly size: we are already forcing the download of a huge repository. I have received some complains about the size of the current repository, and zero complains about not preserving the history of some files we are no longer using. The size of the repository is currently a problem, preserving history is not. Specially since the history of the original c172p *will be preserved* in FGDATA, while the history of this private repository won't.

AFAIK, there is not a single word in the GPL about preserving the history of a project. We must give recognition to the original authors, not the history of the project. I can care less about the state of the c172p-detailed one month ago. Much worse than now, that is for sure!

**Comment by IAHM-COL** [comment]
The size change after merging is almost unperceived. 
(the large size of this repository is due to the content of high res. textures and source files) -- which all come after the merge.

size of the repository directory after the merge is complete 
            
               $ du -sh
               500 M
               $ du -h 
               511840

current size of the repository without the merge

             $du -sh
             499 M
             $ du -s
             510484

As you can see this merge has 0 changes, and a really really small size increase. In the order of a few Kb.

**Comment by Juanvvc** [comment]
I was wrong with the size of the repository. I have checked myself and the difference in size is negligible.

Israel, I'd be delighted if there is any easy way to remove any reference to any version of any file older than one month. I want us to focus on the future, not the past. Please, help us to improve the current state of the project and let us not "waste" any additional second on what happened 13 years ago.

From my point of view, we will be doing a single commit to FGDATA. Yes, our commit is going to be huge and complex, and this is why we need our own history. It is a bit like a fractal: we have our little history inside a much larger history. We keep only our little history of microsteps and FGDATA looks from a different point of view and preserves only larger steps.

Again, I won't merge this request but if any other contributor feels like this must be merged, go ahead.

**Comment by IAHM-COL** [comment]
I completely agree with you Ludomo
1. The size increase cannot be a main concern. 
2. We are all focusing in the future. Restoring the repository history is not focusing on the past. Is just like record keeping (with several additional technical -functionally- advantages)
3. Indeed, I understand the project goes to FGDATA in only 1 commit. Restoring this history does not change that either.

I would really appreciate this merge --which I am certain will cause no harm to this project [at all]
But your last statement does not sound really like an invitation to your contributors to proceed. If I were in your board of contributors, I really will read on that line a "please, do not merge"

That could be just a linguistic difference thou.

**Comment by Juanvvc** [comment]
Please, if I sounded rude, please, this was not my intention.

**Comment by IAHM-COL** [comment]
sure Ludomo. Likewise

No es mi intencion -ni interes- ser rudo. Os digo, que estoy completamente de acuerdo con todo lo que dices, excepto con no mezclar este contenido. Como habeis verificado no tiene ningun efecto en el tama~o del contenido en Kb, ni tampoco en cambiar el contenido del repositorio.

Solamente introduce los "commit" antes de la separacion de este proyecto. 

La unica diferencia entre tu opinion y la mia es que, como conclusion esta peticion no es aprobada por ti. En mi opinion la aprobacion no deberia ser tan compleja. 

Entiendo que dices que si alguien mas en tu lista de colaboradores piensa distinto a ti no os importaria que ese otro hiciera el "merge". Lo que os digo finalmente es que tal postura realmente hace muy dificil para todo colaborador del proyecto venir a contradecir lo que tu ya habeis decidido (siendo todavia tu repositorio)

**Comment by Juanvvc** [comment]
This is not "my" repository. Someone had to create a repository and it was me because, at that time, I seemed to be the most skilled contributor in using git. Some months later, I'm totally surpassed by other contributors. Please, this is not "my" repository and I know perfectly I can't take any decision on my own!

Israel, esto es ahora más filosófico que otra cosa. En la universidad, tengo que recordar constantemente a mis estudiantes que se fijen en el futuro, en acabar los proyectos, que se pongan metas y que llegen a ellas. La meta de este proyecto es que quede todo perfecto. Todos sabemos de dónde viene y realmente no veo que haya ningún beneficio en poder conocer el estado de la c172p en el año 2002. Sobre todo porque ese estado se puede conocer en FGDATA. Prefiero que no se pierda el poco tiempo que tenemos todos en hacer esfuerzos que no mejoren el proyecto. En realidad aceptar tus cambios es tan fácil como pulsar el botón verde que tengo aquí abajo, pero realmente estoy convencido de que no debo sentar el precedente de aceptar cosas que solo nos hacen "perder tiempo" a todos.

En cualquier caso, lo digo completamente en serio: esta es mi filosofía y mi opinión y realmente no me importa que alguien tenga otra y pulse el dichoso botón verde :)

**Comment by onox** [comment]
The way these commits are added back into the repository is completely useless. If you do `git log <file>` or `git blame <file>` then you won't find any of the old commits. So adding back the old history is not that useful. On top of that you first get to see all these old commits if you do `git log --graph` or `tig` for example, and you have to scroll down a lot to see the graph part of our commits.

The "best" way would be to try to rebase all of our commits on top of the old commits, but that will change all the commit IDs and will be very invasive as well. But I don't think we should go that way. It's maybe a bit unfortunate that the old commits are not present, but I rather not mess with all our commits.

**Comment by IAHM-COL** [comment]
I will as you say ONOX be completely against a rebase.

**Comment by wlbragg** [comment]
So this is all prior to c172p-detailed?
I see the logic in adding this, but I also don't see the necessity (me of all people right).
If the c172p was loosing it's history them I might be more inclined to want to keep it.

Maybe a few more contributors can weigh in.

I have less say in this than Juanvvc, who along with gsagostinho I feel are the rightful owners of this repo.

At any rate, Israel, which ever way this goes, please know we appreciate the thought and effort involved to create the data, it's not a bad idea in a perfect strategy.

**Comment by onox** [comment]
You can still find the history in FGData via `git log Aircraft/c172p/`

**Comment by IAHM-COL** [comment]
@ONOX 

intriguingly you can still check the file log and the file blame. 
So it is not "useless" itself. Just more involved.

I just tested 

example

        $git log git log 488ae47 -- c172p.xml
        commit c520440cb622265240afa9a2c2bb084f351c63c2
           Author: Juan Vera <juanvvc@gmail.com>
           Date:   Thu Feb 19 02:09:05 2015 +0100
           Initial commit


but, if choosing the proper revision

         $git log 
         commit 82ce3c6e294e690e68e086d21284796cc8a6bacb
         Author: Stuart Buchanan <stuart_d_buchanan@yahoo.co.uk>
         Date:   Wed Dec 21 21:24:34 2011 +0000
          ***
         Add back FDM configuration handling a tailwind.
         commit cd61d1de95054e4537176b8ed8e56a6dcd898073
         Author: Stuart Buchanan <stuart_d_buchanan@yahoo.co.uk>
         Date:   Tue Dec 20 21:43:44 2011 +0000
         ***
         Sync c172p FDM with JSBSim version, incorporating "Add propeller induced velocity factor 
         to  Cmde and Cndr. Enhances ground operations." rev 1.27 from jentron.

The length of each output (with pretty=oneline)
is 

for the head revision: 1
for the 488ae47 revision:  28

clearly, if the information is in the repository it can be obtained.

**Comment by IAHM-COL** [comment]
@wlbragg 
Thanks.
I appreciate your kind words.
There is no perfect strategy here. The way that onox indicated (with a rebase) guarantees a lineal history but at great expense. I am with him: A rebase should NOT take place.
The strategy I applied is a merging of a branch. It works technically. It also has caveats in that history is not lineal and revisions are created to handle past.

Yes. all this commit does is add historical commits for everything happening before ludomo and Gilbert started this work. In principle the history should have preceeded them. 

For one side: I found difficult now to trust valuable historical data over FGData. For the other, that historical commits really belong here too, and they acknowledge all those contributors before us. (note as an example the readme file do not acknowledge them explicitly, not the tree contains an inclusive "AUTHORS.txt"). This strategy cleans that in one simple step.

Ludomo has a Philosophical difference of opinion about this. And yes, I agree with you, he and Gilbert are ultimately the "Parents" of this project. 

I think ONOX, you and I agree more of beign --to say the least-- nice to have the commits there. But again, the solution is not technically perfect, as ONOX outlies. It is just the best of all possible options I know of. 

And I said before, accepting the merge has no practical "harming" consequences. It only does a bit of good, where it can.

**Comment by IAHM-COL** [comment]
Also, I found important to note that Ludomo first reaction was this is inconvenient over repo size bloating away. 
Which is not exactly correct --with great fortune--

**Comment by IAHM-COL** [comment]
@ALL  

Had you seen also that I am looking forward to send another pull request that includes a "restoreName" to get the aircraft to work as "c172p" ?
This is needed work ahead of merging back to FGDATA as well.

I am sooo looking forward to get these merges completed, but I feel in a way my help is totally not-appreciated here :( 

https://github.com/IAHM-COL/c172p-detailed/pull/1

**Comment by Juanvvc** [comment]
Your help is totally appreciated if you fix any of the 60 open issues! It is just I really don't want to "waste" time to fix something that is not an issue now, and it won't be an issue in the future because past history is perfectly preserved in FGDATA.  It is our history than is in danger, not the history of the original c172p :)

My current role as "curator of the project" (I don't want to say "manager", I'm looking for a term less formal) makes me kindly push you to use your time and skills in any open issue by not accepting this merge.

**Comment by IAHM-COL** [comment]
ok. you are the boss Ludomo

I deleted the "previous" history now, to allow me to send the pull request for aircraft renaming
Which is also completed now.

Best,
Israel


So this discussion is over and this is the new topic
https://github.com/Juanvvc/c172p-detailed/pull/221

**Comment by IAHM-COL** [comment]
Can I politely ask this to be merged?

**Comment by onox** [comment]
First of all, the answer was/is no. Second, Github says the PR cannot be reopened because "the master branch was force-pushed or recreated."

**Comment by IAHM-COL** [comment]
the second argument is no problem.
I can regenerate the pull

The answer of WHO was no ?

**Comment by onox** [comment]
However, could you create a new branch (--orphan branch I think) with just the old commits? (from " 	Updated with animations, more detail, and new panel." to "c172p: define CG envelope")

**Comment by onox** [comment]
To quoate @Juanvvc:

> Your help is totally appreciated if you fix any of the 60 open issues!

**Comment by IAHM-COL** [comment]
That is not a NO answer. Read well ONOX

**Comment by onox** [comment]
No need to start shouting.

**Comment by IAHM-COL** [comment]
I can create an orphan branch but that is totally unnecesary. 
The c172p is hosted here: https://github.com/FGMEMBERS/c172p
So we don't need an "orphan branch"

I need the history to be restored over the detailed instead. Unless this is technically impossible, which is not my perspective .

Shouting? via text?

**Comment by IAHM-COL** [comment]
> Second, Github says the PR cannot be reopened because "the master branch was force-pushed or recreated.

I generated the pull requests again so now this is fixed ONOX

**Comment by wkitty42** [comment]
i'm confused at why israel ***needs*** this history restored... what is the real need or purpose? it doesn't provide anything beneficial to the project that i can see...

i certainly hope that this doesn't blow up like what happened on the dev list :disappointed:

**Comment by gilbertohasnofb** [comment]
Israel, I know your intentions are good and that you believe you are doing something beneficial, and also that you believe you are seeing something that none of us are, but you must realize that this discussion is turning into one of "those" discussions. Look, ludomotico already told you very politely that this is not a current issue and that we won't bother with it right now and that if you'd like to help you can have a look on our current opened issues (which you are welcome to help us with!), but then you started a discussion with both onox and wlbragg (in different PRs but about the same thing). You are doing us no favour by continuing with these discussions... look, even if you think you are right, in the end you are causing these annoying discussions here, and you are the one that can easily make them stop. So far we had zero problems in this project concerning people being pushy and the whole development has been so smooth, so please consider if it's really relevant to press on with these discussions when clearly nobody else is up for it. Very likely the only thing you will manage to achieve is to start having problematic relations to all these already mentioned developers here, and that will make it even more difficult for you to convince anyone that you are right. So I kindly ask you to reconsider this, please.

**Comment by IAHM-COL** [comment]
Am I the one being pushy Gilberto?
Someone said:

>My current role as "curator of the project" (I don't want to say "manager", I'm looking for a term less formal) makes me <b>kindly push</b> you to use your time and skills in any open issue by not accepting this merge

Which is exactly whats going on here, too.

Look. When I find an issue I can fix, I will gladly do it, and I will not need to be kindly pushed to it.
There is not such philosophical ground difference here. Is merely a couple of unrelated technical issues. The first one is whether the aircraft is to be renamed. The second one is whether it is possible that you kindly accept the historical commits into this repository. 

The second petition will change nothing in your code, but will place back historical data. I am not thinking I am right about this. I am sure. 

The only technical "con" has been repository size bloating. Which already got demonstrated this is not really an issue (unless you worry for less than 10Kb of data).

Because I am sitting myself downstream of this repository (over FGMEMBERs) and the c172p of FGDATA is going to be replaced by this version, I would largely apprecciate these historical commits merge to be accepted. And if there is a technicality that I am not seeing why this is not acceptable, I will like to know that. But that this is not accepted based that is not Ludomo's priority --and he is trying to push me in one direction not another: that's a more complex explanation in my book.

Besides, he did not say: "No"
He said, he will not accept them, but will be OK with other Collaborator accepting them. 

I really hope this clarifies the current status of this request.

**Comment by onox** [comment]
@gilbertohasnofb @Juanvvc Is it ok if I force push to restore the original master? (without IAHM-COL's commits)

**Comment by Juanvvc** [comment]
@onox, please, do not restore the original master, this will only take more trouble. Let's forgive this nasty episode and keep up the good work!

Please, @IAHM-COL , don't do something like this again. If an issue is closed, it must remain closed unless there is a good and new reason to open it again.

**Comment by onox** [comment]
It's just a push of the master before COL's commits, as if nothing had happened.

**Pull request closed without merging**
