### PR TITLE
Correct addition of irradiance map.

### PR DESCRIPTION
**Pull request by wlbragg**
The irradiance code I pushed broke the interior shadow. You can't have the same object assigned to two different effects which is what I did. I needed to have the irradiance lines added to the original interior effect which is what this commit does.

### CODE REVIEW

**Comment by wlbragg** [comment]
Because of the interest in the c172p and this is a limited correction to an error, I went ahead and merged this.

**Comment by onox** [comment]
Did this PR fix #482?

**Comment by wlbragg** [comment]
I don't know, I need gilbertohasnofb to check for the line he saw. But it was a mistake on my part and needed to be corrected regardless.

**Comment by gilbertohasnofb** [comment]
@wlbragg I've had my hands full the whole day and I still couldn't check it. I will try to do it still today but unfortunately later, okay? Sorry about that.

**Comment by wlbragg** [comment]
@gilbertohasnofb, no worries, good work your doing!

**Comment by gilbertohasnofb** [comment]
@wlbragg Finally made some tests and it seems that problem is fixed! Under the same conditions that line isn't appearing at all. The shadow also looks much better somehow, I love the effect :smile: 
I will close #482

**Comment by wlbragg** [comment]
Good, glad to here this. It must have been a side effect of the faulty effect I corrected.

**Comment by gilbertohasnofb** [comment]
Thanks for it, my impression was that the whole shadow cube and the interiors were looking much better, although I can't tell exactly why!

**Pull request merged**
