### PR TITLE
Set instruments to correct position

### PR DESCRIPTION
**Pull request by dg-505**
As mentioned in issue #128, I corrected the positions of the VSI, the RPM, and also the Battery Gauge. To do this I had to made some changes in the .ac-files, so I created three new folders (BatteryGauge, RPM, and VSI in Models/Interior/Panel/Instruments.
When committing the changes I messed up something, but finally it should be right.
I'm a newcomer to Git and so I apologize for the chaos in these 6 commits. :confused:

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Why does it say that 2 of those commits were made by me?? Anyway, let's merge and see how it looks, thanks for the work!

**Comment by gilbertohasnofb** [comment]
Tested, all seems to be fine, much better than before!

**Comment by dg-505** [comment]
I don't know. Something went wrong when I comitted/added/pushed, or whatelse...
The main point is, that it works. Also after the chaos made by me.

**Comment by onox** [comment]
@gilbertohasnofb If you want to see how something looks before merging it, click on "command line" in the "This pull request can be automatically merged." box, then you execute the instructions of "Step 1" to test the PR.

**Comment by gilbertohasnofb** [comment]
@onox thanks for the info, onox; I will do that next time.

**Comment by onox** [comment]
@gilbertohasnofb Could you also take a look at my PR #152 ? :smile:

**Comment by gilbertohasnofb** [comment]
@onox just did it, easy peasy to test it before merging :)

**Pull request merged**
