### PR TITLE
Bug 329, 525, and 545

### LINKED ISSUE #329: New crash sounds
I just added two new sounds to our project to be used when the plane gets damaged:

- `crash.wav` sound (when the plane is completely shattered)
- `damage.wav` for smaller damage (such as damage to the wing only, but not a complete destruction to the plane

A new branch `bug-329` has been created.

### PR DESCRIPTION
**Pull request by onox**
Fixes #329, #525, and #545 

* `crash.wav` is played when the wing collapses (dive to the ground then pull up just before impact) or if both main gear are broken

* `damage.wav` is played when a wing becomes lightly damaged, heavily damaged, or broken. Perhaps we want a more dramatic sound for a broken wing? (not `crash.wav`, which is used for impact with the ground)

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox Some comments:

- maybe we could make the `crash.wav` a bit louder, what do you think? It sounds softer than the engine to me, and I think a heavy crash should be louder than that
- I can't listen to `damage.wav` when the wings get slightly damaged. I can see they are damaged, but no sound is played at that moment.
- I pushed a new sound called `damage-heavy.wav`, which is a less dramatic version of `crash.wav`. So you can now use `damage.wav` for the light damage and `damage-heavy.wav` for heavier ones

**Comment by onox** [comment]
You should definitely hear `damage.wav` when you damage a wing. I'll use `damage-heavy.wav` later today.

**Comment by onox** [comment]
Hmm.. I'm not sure about `damage-heavy.wav`. It sounds to similar to `crash.wav`.

I'm rather looking for a sound that immediately gives you a "$%&^@ We lost a wing! :fearful: :scream: :tired_face: " feeling :stuck_out_tongue_winking_eye: Something that sounds catastrophic.

**Comment by wkitty42** [comment]
On 11/07/2015 06:05 AM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> Some comments:
>
>   * maybe we could make the |crash.wav| a bit louder, what do you think? It
>     sounds softer than the engine to me, and I think a heavy crash should be
>     louder than that

when we crash, the engine shout shut off, too, shouldn't it?? i had a crash 
yesterday when the T-storm knocked my out of the sky and the engine kept on 
running even though the craft was buried nose first in a mountain side...

**Comment by gilbertohasnofb** [comment]
@wkitty42 hehe sure! I meant that the volume of a crash should be louder than the volume of a running engine, but nowhere I stated that both should be heard at the same time :wink: I am just trying to give references of volume.

**Comment by wkitty42** [comment]
On 11/07/2015 06:44 AM, Gilberto Agostinho wrote:
> @wkitty42 hehe sure! I meant that the volume of a crash should be louder than
> the volume of a running engine,

right right right... i agree there, completely... maybe we can cut the engine 
volume down when we have the crash sound play?

> but nowhere I stated that both should be heard at the same time :wink:

there is that, too...

> I am just trying to give references of volume.

:+1:

**Comment by gilbertohasnofb** [comment]
> maybe we can cut the engine volume down when we have the crash sound play?

But I believe we are already doing that! My point is: there is nothing wrong with the engine sound nor its volume nor with the moment it's played/not played, the only thing is that the crash should be louder, that's all..

**Comment by wkitty42** [comment]
On 11/07/2015 06:52 AM, Gilberto Agostinho wrote:
>     maybe we can cut the engine volume down when we have the crash sound play?
>
> But I believe we are already doing that! My point is: there is nothing wrong
> with the engine sound nor its volume nor with the moment it's played/not played,
> the only thing is that the crash should be louder, that's all..

ahhhh... ok... if this is in master, i'm taking off at KSFO in the amphibious 
right now... can test and see how it is on my setup? the sounds do seem to be a 
bit better than they used to be but i still have trouble hearing the stall 
warning but that's a different issue i think :wink:

**Comment by gilbertohasnofb** [comment]
The new crash sounds are not merged in the `master` yet, but the engine sounds should stop on a crash in either branch

**Comment by gilbertohasnofb** [comment]
@onox I just pushed a new wind sound which may solve #525 and a second attempt for the heavy damage. Let me know what you think.

**Comment by onox** [comment]
Sounds are better, but the wind sound is very soft in Audacity. Can you amplify it? It is always better to make sure the sound is as loud as possible (no clipping), because it is very simple to lower the volume in the XML file.

**Comment by gilbertohasnofb** [comment]
Sure, I forgot to do that. Give me 1 min.

**Comment by gilbertohasnofb** [comment]
done

**Comment by onox** [comment]
@gilbertohasnofb Can you test the various sounds?

**Comment by gilbertohasnofb** [comment]
Sure I can. But I think you forgot the code for the new wind sound which is also on this branch.

**Comment by onox** [comment]
We already had a `<wind>` sound.

**Comment by gilbertohasnofb** [comment]
Ah, okay, and since our `wind.wav` is in the folder `Sound`, the code first look for the local file before going to FGDATA, correct?

**Comment by onox** [comment]
Yes.

**Comment by gilbertohasnofb** [comment]
Okay, so `crash.wav` is playing correctly on a major crash. The `damage.wav` is being played when both wings get damaged (but not completely collapsed), as for instance by diving then pulling back. I am not being able to collapse wings so I didn't hear `damage-heavy.wav`, would you recommend me some method for it? And I can't hear any wind on my sim, but I am suspecting it's some trouble with my configuration. If you hear it then it should be fine.

**Comment by gilbertohasnofb** [comment]
I got to go for today, tomorrow I can test some more, ok?

**Comment by onox** [comment]
Wing collapse means the wings are bended downwards. That's when you should hear `crash.wav`. When a wing breaks off completely, then you should hear `damage-heavy.wav`.

**Comment by gilbertohasnofb** [comment]
I haven't seen either the collapsed wings (breaking downwards) not them breaking off completely. Diving and pulling up gives me "both wings damaged".

**Comment by onox** [comment]
You need to dive towards the ground and then pull at the last second so that the belly of the airplane smashes into the ground. That should give the required g load that you need.

**Comment by gilbertohasnofb** [comment]
I see. I will make some more tests tomorrow and then hopefully merge this.

**Comment by onox** [comment]
You do get "both wings damaged", but only just before you hit the ground.

**Comment by onox** [comment]
@gilbertohasnofb You might want to play with line 252 to control the volume of the wind a bit. Perhaps 0.7 or 0.8 is a better value. 1.0 is maybe too loud in the cockpit.

**Comment by onox** [comment]
@gilbertohasnofb I have already increased the volume a bit from 0.5 to 0.7. Now it should be hearable.

Don't merge this PR yet, I think I want to create two wind sounds (one left, one right) and fix the pontoon wave sounds as well (distance + volume when opening one of the doors)

**Comment by gilbertohasnofb** [comment]
@onox Okay, so I got the `damage-heavy.wav` sound. As for the wind, I am having troubles with it but I am sure it's not related to our plane: for some reason, since some time ago I have no wind sound in the sim at all, even using our master. I don't know if it's related to my weather configuration or something, but I hear no wind or whatsoever. In that case, please do set the values as you judge them and merge the PR yourself, ok?

**Comment by wkitty42** [comment]
On 11/07/2015 08:08 PM, Gilberto Agostinho wrote:
> I haven't seen either the collapsed wings (breaking downwards) not them breaking
> off completely. Diving and pulling up gives me "both wings damaged".

i did a water landing with the amphib the other day... everything seemed great 
but then i couldn't take off... it wasn't until i used the heli view that i saw 
the right wing was broken off :cry:

it almost seems like we're getting more fragile...

**Comment by onox** [comment]
:warning: Don't merge this PR yet, I think I want to create two wind sounds (one left, one right) and fix the pontoon wave sounds as well (distance + volume when opening one of the doors)

**Comment by onox** [comment]
@gilbertohasnofb (and others) Can you check rain, wind, and pontoon sounds? Check you can hear attenuation depending on external view, or internal with closed/open door. There are separate sounds for wind and pontoon sounds (left and right to their corresponding door).

I hope you have a headphone or something. I don't have one currently, so it's a bit difficult to hear a difference between left and right.

If some sounds need to have a lower volume, let me know.

**Comment by gilbertohasnofb** [comment]
Sure!

**Comment by gilbertohasnofb** [comment]
rain: seems fine, though it could be louder in the cockpit IMO (the engine is really killing the rain sounds). The effect of opening and closing doors is super cool! It does not attenuate with distance (which I think is intentional, right? The rain sounds shouldn't change with distance I believe)

pontoon: everything seems fine, and it is attenuated with distance

wind: I honestly can't hear any wind at all. As I said before, I suspect this to be an issue of mine, but it's strange that I can hear all other sounds... Even with the max volume on my system (which leads to a super loud engine sound) I can't hear any wind or whatsoever :cry: 

Maybe @wlbragg can test it as well so we can compare results.

**Comment by gilbertohasnofb** [comment]
As for the water sounds for the pontoon and amphibian, I feel that the sound it quite abruptly cut when the airplane takes off. Is there any way of improving this? Maybe using a short fade out?

**Comment by onox** [comment]
> Maybe using a short fade out?

I'll work on this.

**Comment by onox** [comment]
@gilbertohasnofb You can merge the branch if you're fine with the change.

**Comment by gilbertohasnofb** [comment]
Really nice @onox, it sounds much better now! So now that we merged these sounds, I will tell Thorsten to copy the wind, rain, rain on windshield and thunder sounds into FGDATA. Then we can delete our local copies.

**Comment by wlbragg** [comment]
>Maybe @wlbragg can test it as well so we can compare results.

Sounds are GREAT!

Only the rain sound gets louder with door open, shouldn't wind, engine, really any external sound be louder with door open?

Surround stereo works really well upon view change (left to right).

I can hear the wind sound by shutting down engine and gliding.

Engine sound does not overpower rain sound.

Need to increase volume of all external sounds when doors, and now windows, are open.

**Comment by wlbragg** [comment]
I haven't used sound much at all because I have a "pip" TV always playing.
But I will test it extensively over the next couple weeks.

We need to have the sound setting "spot on" to give the sim the best possible reality effect. What I mean is it is really important to have the sound levels right compared to each other.

My first impression is that the levels of water, flaps and rain are to loud. Maybe they are right at present levels with doors or windows open. But I think they should all be softer with doors and windows closed. I don't think they should be so overpowering.
I think the engine is about right, if anything, to loud, but not by much.

**Comment by wlbragg** [comment]
In helicopter view the engine is muted way down yet the water sounds are loud.

Please, don't think this is complaining or criticizing, I'm just giving my impression.

**Comment by gilbertohasnofb** [comment]
> I can hear the wind sound by shutting down engine and gliding.

Oh, I can also hear the wind that way! The thing is before we had wind sounds _regardless_ of the plane speed, so if you were parked with the engine off you would still hear some wind. That's why I thought I had a problem with my configuration. I would bring that back to be honest, I think a bit of wind sound while parked could be very cool. We can take the speed of the wind in consideration for that I think.

**Comment by onox** [comment]
> Only the rain sound gets louder with door open, shouldn't wind, engine, really any external sound be louder with door open?

Wind and engine sounds should get louder as well when opening a door.

**Comment by onox** [comment]
> In helicopter view the engine is muted way down yet the water sounds are loud.

Zoom in with mouse scroll wheel, then engine shouldn't be muted down.

Engine and water sounds should get a lower volume when you zoom out (with mouse scroll wheel, not x/X)

**Comment by onox** [comment]
So this should change:

1. Make sure wind sound is hearable when aircraft is parked

2. Reduce volume of rain

3. Reduce volume of water "at all times" sounds

4. Greater difference in volume when having all doors closed versus one or two doors open. (Currently boost is 20 % for 1 door, 32 % for 2 doors, 40 % for external view.

I think the boost for 1 door should be perhaps more like 30 % and then only very minor extra boost for 2 doors (32 %).

@gilbertohasnofb @wlbragg Do you all agree with this?

**Comment by gilbertohasnofb** [comment]
I agree, but I just would add:

1. Make sure wind sound is hearable when aircraft is parked __if there is wind__

2. Reduce volume of rain __a tiny bit__ (IMO it's quite good already, I imagine rain should be quite loud in the cockpit anyway, see: https://www.youtube.com/watch?v=wZJS0Eacl3w at around 0:52)

**Comment by wlbragg** [comment]
:+1:

**Comment by wlbragg** [comment]
>Greater difference in volume when having all doors closed versus one or two doors open. (Currently boost is 20 % for 1 door, 32 % for 2 doors, 40 % for external view.

That is currently set for all sounds?

>I think the boost for 1 door should be perhaps more like 30 % and then only very minor extra boost for 2 doors (32 %).

I think the 2nd door should be enough to hear a distinct difference, is 2% distinguishable?

**Comment by onox** [comment]
> That is currently set for all sounds?

Currently only for the sounds which are in the center (not left or right) like the engine. For the wind and water sounds I created two sounds (one next to each door). For those latter sounds the boost is 20 % for 1 door and 40 % for external view. These sounds do not care about the state of the opposite door.

> I think the 2nd door should be enough to hear a distinct difference, is 2% distinguishable?

Well, actually no. I think having 3 different boost levels (1 door, 2 doors, external view) is maybe a bit too much. With my sound system, I find 20 % difference between levels to be barely distinguishable. So perhaps it's better to give 2 doors and external view the same boost level.

So that would mean 30 % for 1 door and 40 % for 2 doors or external view.

**Pull request merged**
