### PR TITLE
Elevator animation (was reversed) and move FDM aerorp backwards vs CG

### PR DESCRIPTION
**Pull request by dany93**
3D animation: elevator movement was in the wrong way.

### CODE REVIEW

**Comment by onox** [comment]
Elevator animation is fixed :+1: PR can be merged if no one objects to moving the aerorp backwards.

**Comment by dany93** [comment]
I have completed the title with aerorop to draw at least gsagostino's attention.
In fact, I believed that the second pull request would make a separate subject with a separate title and I didn't know how to do (my lack of knowledge of github...).
Thanks, onox, to have risen the question in the forum.
I've seen no drawback up to now, anyway that's easy to go backwards.

**Comment by gilbertohasnofb** [comment]
> I have completed the title with aerorop to draw at least gsagostino's attention.

Sorry Dany but I don't understand what you mean!

**Comment by dany93** [comment]
Hi, Gilbert,

cf. your remark on the weak "nose down" effect at stall.
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=885#p239795

**Comment by gilbertohasnofb** [comment]
Oh, I see. Sorry but everything I have been talking about lately was concerning textures and the 3D model so that's why I didn't get it at first :) Cool then, I will test the stalls once again soon.

**Comment by wlbragg** [comment]
I just noticed this hasn't been merged.
I can't certify the aero reference point move as I know nothing about it. But Dany is our FDM point man and we need the elevator corrected. If the aero reference point move should prove to be incorrect, it can be moved again.

**Comment by wlbragg** [comment]
I also just noticed this only went to Danys' FDM I will adding the elevator changes to master FDM.

**Comment by dany93** [comment]
I think the elevator changes merge is waiting for the aerorp agreement.
See above onox's message

>Elevator animation is fixed :+1: PR can be merged if no one objects to moving the aerorp backwards.

I've unfortunately sent two Pull requests for two subjects one after one, and they have been gathered into one.
I you can tell what I should have done, thanks.

**Comment by Juanvvc** [comment]
dany93, you are the only one skilful enough to change the FDM It is going to be difficult for the rest of us to evaluate the convenience of the changes, so just push them and we will complain if the aircraft seems "weird" while flying :)

**Comment by dany93** [comment]
OK.
But I have a message " We can’t automatically merge this pull request."
It could be (??) because this morning I have done a "git pull" from (your) juanvvc master branch and "git commit" to update mine (dany93 master). This merge request for elevator and aerorp  was still pending, and my last pull request and git commit may be included in it (??). It appears above under "mise a jour depuis juanvvc".
I've done nothing else since that on my branch
I do not know what to do:
- I cannot merge this pull request by myself from here,
- I do not dare to do a "git push" from my dany93 branch to yours. I'm afraid of doing something wrong or having a conflict.

**Comment by Juanvvc** [comment]
It is because you changed some lines that were also changed by someone else between your pull and your push. Git cannot decide if the right lines are your lines or the other, so they must be manually evaluated. This is called "a conflict": several authors modifying the same lines at the same time.

If no one beat me, I'll look into the conflict in a few hours.

**Comment by dany93** [comment]
If you can, thank you and pardon. That's above my knowledge in git.
I think that the conflict comes from my git pull from your juanvvc master to my dany93 branch, followed by a commit to my branch (this morning, "mise a jour depuis juanvvc, bd1d8d7") which appears in this merge request.

**Comment by onox** [comment]
What is this "mise a jour depuis juanvvc" all about? Was that commit intentional or do you rather wish you didn't make that commit?

**Comment by dany93** [comment]
Thanks onox, I was waiting for your intervention.
After my pull request for elevator and aerorp, I wanted to update my "dany93 master" branch with the last juanvvc master.
I did a "git pull" from juanvvc master to my dany93 master and "git commit" to update mine (dany93 master). The problem is that the merge request for elevator and aerorp was still pending, and my last pull request and git commit (the update) have been be included in this pull request. It appears above under "mise a jour depuis juanvvc" (<==>"update from juanvvc") because git asked me the question. That  "mise a jour depuis juanvvc" commit inclusion was totally intentional, I didn't expect it would be included in the pending pull and merge request. You can remove it.
What I wished to be merged:
- elevator correction (but I think wlbragg has added it manually, see above),
- aerorop correction.
I hope to be clear enough despite my english.

**Comment by wlbragg** [comment]
Dany, are you still stuck here?
I already did the elevator correction manually, I will do the same for aerorop correction. Will that help you get unstuck? What do you need done?

**Comment by dany93** [comment]
Many thanks, wlbragg.

I see the aerorp correction in juanvvc master, merged by yourself.
Do you think I can try doing a git pull from juanvvc master, then git commit to my dany93 master branch without risking to add a mess?

**Comment by wlbragg** [comment]
I merge master into shadow-control periodically and I always have some "conflict" that I have to sort out. That requires you decide what part of the conflict you want to keep and use in the code. Then you commit the changes you make to the files that had conflicts.

If you think you can do that then you should be OK. If you get stuck I think we could get you through it. Where is your branch? Is it local on your computer or on GitHub? I always do all my merging local, and then just commit to GitHib. I think the maybe the conflict on GitHub threw both you and me. I never had to work out a conflict when trying to merge on GitHub and thus wasn't really sure how to go about it.

**Comment by dany93** [comment]
>Where is your branch? Is it local on your computer or on GitHub?

For me there ***was*** no question, my branch is on Github
https://github.com/dany93/c172p-detailed
I've followed onox's advices:
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=885#p239572
i.e. "Go to https://github.com/Juanvvc/c172p-detailed and then click on the grey "Fork" button" (upright). This has created a fork at https://github.com/dany93/c172p-detailed 

Do you have access to this fork, would you be able do see it and download?
(currently, the very new damage files for which I sent you a link are not on it, I haven't touched it for 2 or 3 days).

My current problem is that, if I have a conflict, I totally ignore what to do. With command lines? I'm ready to learn but I would not want to mess your repositories...
I guess I would be able to access to the files in conflict, compare and choose which lines I want to keep or not?
Not easy to ask for a question on the forum, there are so many posts per day...

I will try to do a git pull from juanvvc:master to my branch, do a git commit and see what it does... Hoping everything is back to normal.
If not I will call for help. Very sorry.

**Comment by dany93** [comment]
I have done a git pull from juanvvc master:
 https://github.com/Juanvvc/c172p-detailed
to my branch
https://github.com/dany93/c172p-detailed
***I had conflicts*** but I resolved them by:
git status, git add (the files which were listed), git commit, git push to my branch
I hope that was the right way...
Thank you for your help and for what you have done to upload my files.

**Comment by onox** [comment]
No that's not the right way. When you have a conflict, you get files with something like this in it:

```
something here
<<<<<<< HEAD
code from branch A
=======
code from branch B
>>>>>>>
more code here
```

In this case you have to choose between using the code from branch A or from branch B. If you choose branch A for example, then you remove all those arrows and the code from branch B, so you get:

```
something here
code from branch A
more code here
```

If you simply add all the conflicts with git add and then commit, then you get this [mess](https://github.com/dany93/c172p-detailed/commit/c52896cc26576a47a93558aa1df9e9c03f81b83a#diff-2c45035f7c12c1228f5d7a5a757bc36aR218).

**Comment by onox** [comment]
Since @wlbragg already committed your changes to master, we can simply reset your branch to the commit 685f49daf849c626e7704d9276a3d88d87f85e92 ("reworked all older liveries"):

1. Check that you're in your dany93/c172p-detailed folder on your local computer

2. Do this: `git remote -v`. Check that origin points to github.com/dany93/c172p-detailed and github.com/Juanvvc/c172p-detailed

3. Now do the following command which will forget everything that came after the "reworked all older liveries" commit: `git reset --hard 685f49daf849c626e7704d9276a3d88d87f85e92`

4. Do: `git log` and check that the commit from @gilbertohasnofb with message "reworked all older liveries" is your latest commit.

5. Do: `git pull upstream master` (I'm assuming here that "upstream" is the Juanvvc/c172p-detailed repository)

6. Double check with `git remote -v` that "origin" points to your dany93/c172p-detailed repository.

7. Do: `git push origin master` (I'm assuming here that "origin" is the dany93/c172p-detailed repository)

8. Git will complain saying that the branch is different on Github, so now do this instead: `git push --force origin master`

**Comment by dany93** [comment]
True, I'd done a mess. I couldn't even see my c172p-detailed at all in FGRun... (although the files appeared, but probably wrong).
Yet, I followed what was written by git to do in the console. Bad idea.

With your procedure, everything came back all right. My c172p-detailed works again, everything is clean and updated.

Stressful but I hope I'm learning...

Thank you very much onox, and thank you too, wlbragg.

**Pull request closed without merging**
