### PR TITLE
Transmit co-pilot's and passengers' presence over MP

### LINKED ISSUE #386: Human models not visible over MP
Human models are not visible over MP. Their presence (in the seat or not) should be transmitted over MP (4 bits), but whether they are actually displayed should depend on the local setting (show/hide human models) in the Aircraft Options dialog.

### PR DESCRIPTION
**Pull request by onox**
Fixes #386

### CODE REVIEW

**Comment by onox** [comment]
@gilbertohasnofb @wlbragg Please test :smile:

**Comment by gilbertohasnofb** [comment]
Hmm, I never did MP, but I can check how it works. Is any of you online right now so we can test this?

**Comment by onox** [comment]
Yes, I'll come online. Which airport code?

**Comment by onox** [comment]
Is FHAW okay?

**Comment by onox** [comment]
@gilbertohasnofb I'm at FHAW.

**Comment by gilbertohasnofb** [comment]
FHAW is fine, just gimme a second to get my head around MP

**Comment by gilbertohasnofb** [comment]
@onox which hostname should I use?

**Comment by onox** [comment]
Uhh... I currently use mpserver03

**Comment by onox** [comment]
And make sure to give yourself a proper callsign.

**Comment by gilbertohasnofb** [comment]
@onox that was fun :smile: 

As for the shadows problem, this is what I saw:
fgfs-screen-002

During your whole flight your shadows were at 0ft (maybe because mine was also at 0ft?). Is this a known issue? It looks horrible...

**Comment by onox** [comment]
@gilbertohasnofb Can you move that picture to #387?

**Comment by gilbertohasnofb** [comment]
@onox sure!

**Comment by onox** [comment]
> During your whole flight your shadows were at 0ft (maybe because mine was also at 0ft?). Is this a known issue? It looks horrible...

Yes, it's a known issue.

**Comment by gilbertohasnofb** [comment]
Okay. Maybe at least as a temporary solution for 3.6 we should disable shadows for MP aircraft, what you think? This thing above is just not acceptable IMO.

**Comment by onox** [comment]
We can just disable it for remote aircraft.

**Comment by gilbertohasnofb** [comment]
> We can just disable it for remote aircraft.

That's what I meant. We should do this for now and then try to fix it with #387

**Comment by onox** [comment]
Yes, I'll create a new issue for disabling the shadow for remote aircraft.

**Comment by gilbertohasnofb** [comment]
Okay. I will be around here for at least the next 2-3 hours so let me know if you want to test it.

**Comment by onox** [comment]
I have created #411.

**Comment by gilbertohasnofb** [comment]
Perfect. If you have a solution just let me know here on GitHub and then we can test it.

**Pull request merged**
