### PR TITLE
New textures for the interior and cockpit

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
New textures for the interior and cockpit

Some of you may know that what started the thread that lead to our project was actually a question concerning an early attempt to texturize the panel of the c172p by an user called Horacio. Today I had a look on his files, and actually there were some great textures done by him, all GPL, so I decided to scavenge and incorporate what I could, making some small alterations when necessary. The yokes look much better in my opinion, as well as the mixture and throttle levers. I also added some more text signs to the cockpit, I think those look great in an older model like ours. The parking brake lever is also modified now.

This is what I got so far:

fgfs-screen-004

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
:warning: :warning: PLEASE DO NOT MERGE THIS PR YET! I still want to have a look on his textures for the doors as they look really good, I will see if I manage to incorporate them in the project. :warning: :warning:

**Comment by gilbertohasnofb** [comment]
I tested those other textures and though they look good on the png files, they would need a major UV remapping of the interior. Given that we may have a new 3D model of the plane soon, I don't think it would worth to do this twice, so let's wait a bit longer. In that case, this PR is ready to be merged.

**Comment by legoboyvdlp** [comment]
Very, very, very, nice Gilberto.

**Comment by gilbertohasnofb** [comment]
Thanks @legoboyvdlp but all credit here goes to Horacio, I just made some small adjustments.

**Comment by onox** [comment]
@gilbertohasnofb Does this fix any issues? I don't see any link in the description :confused:

**Comment by onox** [comment]
You might as well add "Horacio" to `README.md`.

**Comment by gilbertohasnofb** [comment]
> Does this fix any issues? I don't see any link in the description

No it doesn't, I hadn't opened any issues about this. I just created the branch, experimented a bit, liked the result and then made a PR.

> You might as well add "Horacio" to `README.md`.

Good idea, I will do it right now and then we can merge this.

**Comment by gilbertohasnofb** [comment]
Done, ready to be merged.

**Comment by legoboyvdlp** [comment]
Very good! Can't wait to test. Beautiful.

**Pull request merged**
