### PR TITLE
co-pilot view, pilot model now depends on weight

### LINKED ISSUE #416: Create Co-Pilot View
Create Co-Pilot View

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Creates a Cockpit Right Seat View. For this to work well, I also made the pilot model dependent of its weight (so that one can set 100 pounds of weight to the right seat and less than 100 pounds to the left seat and have an empty pilot chair). 

Fixes #416.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox I hope this is the right time for a PR with new features since our master has been tagged as `3.7` already.

**Comment by onox** [comment]
You need to update `Models/c172p.xml` and `Nasal/c172p.nas` as well for the pilot to be visible over MP.

**Comment by gilbertohasnofb** [comment]
Okay, I will do that!

**Comment by gilbertohasnofb** [comment]
Done and I am about to commit, but shouldn't I also change https://github.com/Juanvvc/c172p-detailed/blob/bug-416/Nasal/c172p.nas#L209 ?

**Comment by gilbertohasnofb** [comment]
@onox Just ignore that, I obviously need to update those lines as well. I am committing these modifications now, but I'd still like to to work on the rear window views before testing and possibly merging this.

**Comment by gilbertohasnofb** [comment]
Passenger views added. Also, on lines 5223 and 5232 of `Models/c172p.xml`, the right and left passenger models were at inverted positions (that is, the model called Right Passenger was located on the left seat and vice versa)! To fix this, someone inverted the passenger models on lines 5294 and 5304, which made it all more confusing, so I took the liberty of fixing this mess :smile:

@onox this is ready for testing

**Comment by onox** [comment]
Can you set the view numbers to 100, 101, etc.?

**Comment by onox** [comment]
The helicopter view is gone.

**Comment by onox** [comment]
@gilbertohasnofb I don't how you fixed (if fixed) the LeftPassenger and RightPassenger problem. The left passenger object is called RightPassenger and I don't see you changed the Blender and ac files.

**Comment by onox** [comment]
@gilbertohasnofb Could you move the `<view>`'s to a separate file? Also you cannot use view number like 1, 2, 3, etc. because you will override the standard views. So use something like 100, 101, etc.

See https://github.com/onox/V-22/blob/master/Sim/views.xml

You would have to include it in `<PropertyList>` in https://github.com/Juanvvc/c172p-detailed/blob/master/c172p-set.xml#L19

In the new c172p-views.xml file you can then include the walker. Same trick:

```xml
<PropertyList include="Aircraft/Generic/Human/Include/walker-include.xml">
```

**Comment by gilbertohasnofb** [comment]
> Can you set the view numbers to 100, 101, etc.?

Will do that.

>  Could you move the <view>'s to a separate file? 

Sure, I will do that. 

> In the new c172p-views.xml file you can then include the walker. 

I will have a look if I understand this and try to implement it, okay?

> I don't see how you fixed (if fixed) the LeftPassenger and RightPassenger problem. The left passenger object is called RightPassenger and I don't see you changed the Blender and ac files.

The model position is defined in `Models/c172p.xml`, such as in:

    <model>
        <name>LeftPassenger</name>
        <path>Human/male-copilot.xml</path>
        <offsets>
            <x-m> 0.9 </x-m>
            <y-m> -0.2 </y-m>
            <z-m> -1.45 </z-m>
        </offsets>
    </model>

So I fix it by changing the `y-m` and my tests showed that everything we all right. Which problems with it are you still seeing?

**Comment by onox** [comment]
> The model position is defined in Models/c172p.xml, such as in:

Ah, ok, that explains it.

**Comment by gilbertohasnofb** [comment]
@onox 

> You would have to include it in `<PropertyList>` in https://github.com/Juanvvc/c172p-detailed/blob/master/c172p-set.xml#L19
> 
> In the new c172p-views.xml file you can then include the walker. Same trick:
> 
> ```xml
> <PropertyList include="Aircraft/Generic/Human/Include/walker-include.xml">

Hmm, that didn't work. What worked for me was to simply have `<PropertyList>` in the `c172p-views.xml` file and have the following in the `c172p-set.xml` file:

    <PropertyList include="Aircraft/Generic/Human/Include/walker-include.xml">
    
        <sim include="c172p-views.xml">

* * *

Also, there is a little problem with the walker. The pilot model (if present due to weight and "show models" option is on) is programmed to be shown in every view except in the following: if in the cockpit view, if in the walker view, if in the walker orbit view. That means that the pilot will be seating in the cockpit AND the walker will be outside if we chose another view while the walker is enabled (let's say model view, or cockpit right seat view). Also, the walker is male while the pilot is female. Are these things known bugs? Should I open new issues for them?

**Comment by onox** [comment]
> Hmm, that didn't work

That's probably because you didn't add the `<sim>` tags to the `c172p-views.xml` file. But the solution you have chosen now will probably work as well and is maybe even better.

I'll look at the other little issues in your comment tomorrow.

**Comment by gilbertohasnofb** [comment]
> That's probably because you didn't add the <sim> tags to the c172p-views.xml file. But the solution you have chosen now will probably work as well and is maybe even better.

Yeah, now that you mention it I completely understand what was wrong, but if you are satisfied with the result then I will leave it as it is.

> I'll look at the other little issues in your comment tomorrow.

Sure, take your time. If you want, I can create issues here in our repository for them. But they are not directly related to this PR, and this work here is basically done, so once you have time you can test it and merge if you like the result.

**Comment by onox** [comment]
@gilbertohasnofb I have moved the co-pilot view to the last position, so that when you press Shift+V you can go from the pilot view immediately to the co-pilot view. If you're ok with that, you can merge the PR.

You can open new issues for the two issues with the walker.

**Comment by gilbertohasnofb** [comment]
@onox 
> I have moved the co-pilot view to the last position, so that when you press Shift+V you can go from the pilot view immediately to the co-pilot view. 

Great idea!

> You can open new issues for the two issues with the walker.

I will do that straight away!

**Comment by gilbertohasnofb** [comment]
See #423 and #424.

**Pull request merged**
