### PR TITLE
Some improvements to the dialogs and autostart

### LINKED ISSUE #543: Fuel and luggage GUI sliders shouldn't be available in-flight
Similarly to how the oil and fuel sump GUI become inactive if the airplane is moving, the fuel and luggage dialogs should do the same (I am not referring to the Fuel and Payload dialog but rather the new ones that open when clicking on the fuel caps and baggage door).

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
- all dialogs that are opened via pick animations (oil quantity, baggage weight, both fuel tanks and fuel sumps) are disabled if the aircraft is in movement
- added warning message when dialogs are disabled (as not to baffle people of why they can't click anywhere)
- fixed some indentation
- parking brake default state set to ON
- autostart sets parking brake automatically to OFF and also removes chocks, tie-downs and pitot tube cover, sets oil-level to a good value and removes any contamination from both fuel tank

Closes #543 and #548

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox if you want, I can try to fix https://github.com/Juanvvc/c172p-detailed/issues/544 on this same branch. It's fairly simple to disable the pick animation for the doors and luggage doors if the airspeed is above a certain threshold, but what if someone takes off with those doors opened? Should they be automatically closed at that very threshold?

**Comment by wkitty42** [comment]
On 11/15/2015 03:11 PM, Gilberto Agostinho wrote:
> @onox if you want, I can try to fix #544 on this same branch. It's fairly
> simple to disable the pick animation for the doors and luggage doors if the
> airspeed is above a certain threshold, but what if someone takes off with
> those doors opened? Should they be automatically closed at that very
> threshold?

i would say yes, they should close automatically.. maybe even faster than normal 
with a possibly louder closing sound if they slam shut...

i know that at 45 to 50 mph, it is very hard to open a car door very far... much 
harder the faster you go if you can get it to open a few inches at all...

**Comment by onox** [comment]
> @onox if you want, I can try to fix #544 on this same branch. It's fairly simple to disable the pick animation for the doors and luggage doors if the airspeed is above a certain threshold, but what if someone takes off with those doors opened? Should they be automatically closed at that very threshold?

Can you do this for the luggage door only? I would like to implement limited opening of the doors in #544.

**Comment by onox** [comment]
> Can you do this for the luggage door only?

Disabling the pick animation that is.

**Comment by onox** [comment]
It would be cool if I can add a wind force that pushes against the doors.

**Comment by onox** [comment]
Or let the pick animation enabled for the luggage door, but disable the dialog and don't open the door itself.

**Comment by onox** [comment]
Or let the pick animation enabled for the luggage door, but display a disabled dialog and don't open the door itself.

**Comment by gilbertohasnofb** [comment]
> Can you do this for the luggage door only?

> Or let the pick animation enabled for the luggage door, but display a disabled dialog and don't open the door itself (if it's closed).

I will do that now.

**Comment by gilbertohasnofb** [comment]
@onox Done.

Also, as discussed here https://github.com/Juanvvc/c172p-detailed/issues/471#issuecomment-156912286, I created a file `NEWS.md` with the features and bug fixes for version 3.6.

**Comment by gilbertohasnofb** [comment]
I also implemented a very minor modification from #548. It simply modifies the default state of parking brake from off to on, and then the autostart function sets the parking brake to off automatically now. This way beginners using autostart won't get stuck but people who don't want to use save states for the switches can start the sim with parking brakes on.

**Comment by gilbertohasnofb** [comment]
Autostarts also handles oil and fuel contamination now.

And as @Juanvvc wrote in the forum:

> Probably, if you all agree, this function should be moved to c172p.nas and perform all the new preflight inspection.

Effectively the autostart is doing all the pre-flight inspection now, but it's still located in `engine.nas`. If you all agree, I can move it to the `c172p.nas`.

**Comment by dg-505** [comment]
IMO in c172p.nas it would make more sense.

**Comment by onox** [comment]
> Also, as discussed here #471 (comment), I created a file NEWS.md with the features and bug fixes for version 3.6. 

@gilbertohasnofb It's a bit whiny/pedantic to say this, but try not to mix up different unrelated features/bugs in the same branch. In this case it doesn't matter, but it doesn't look nice. If someone is checking/following commits in an app that shows the commit tree, it can be confusing if there are suddenly totally unrelated commits in a branch of the tree.

If your `git status` is clean, you could have just switched/created a new branch and have added `NEWS.md` in that branch. So it's not impossible to work on multiple branches at the same time. You can leave the commit in this time, or you can do interactive rebasing and delete the commit. Your choice.

**Comment by gilbertohasnofb** [comment]
@onox It makes complete sense, onox. I just thought that it would be easier to test a single large PR than several tiny ones, but I think you are right with this. So in this case, what should I do? Should we remove these commit and create a new branch then a new PR, or should I simply watch out next time?

As for which `.nas` file the autostart function should be, do you have any preferences? If you also think it belongs to `c172p.nas` like the others, I can do that and then we can think about merging this.

**Comment by onox** [comment]
Well, this is a nice example for you to try interactive rebasing:

1. Backup `NEWS.md`

2. Check with `git log` that your latest commit in the branch is "autostarts handles oil and fuel..."

3. Do `git rebase -i HEAD~5`

4. You should see a line with `pick 702dad5 created NEWS.md` at the top of your editor. Delete that line. Leave other lines untouched. Save.

5. Check with `git log` that your other commits are still there. Force push.

**Comment by onox** [comment]
@gilbertohasnofb You can move the `autostart` function if you want. Just remember to adjust the listener callback which calls the function (around line 205).

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@onox I followed the steps you gave me above, but at step 5 when I do a `git log` I can only see the commits _previous_ to the introduction of NEWS.md, but all the commits done after that have disappeared. obviously did not force push yet.

Also, what does the argument `HEAD-5` in `git rebase -i HEAD~5` mean?

**Comment by onox** [comment]
"Well, this is a nice example for you to try *interactive rebasing*"

**Comment by onox** [comment]
Try to do `git rebase --abort` and check if you got your stuff back.

**Comment by onox** [comment]
Ok, pull to get your stuff back. When I do `git rebase -i HEAD~5` I get an editor with the following in it:

```
 1 pick 702dad5 created NEWS.md
 2 pick deddc93 fixing small typo
 3 pick d25ddb3 implementing #548
 4 pick 9e264b1 autostart also removes chocks, tie-downs and pitot tube cover
 5 pick e7ae16c autostarts handles oil and fuel contamination as well
 6 
 7 # Rebase 48f653e..e7ae16c onto 48f653e (5 command(s))
...
```

Now I delete the 1st and 2nd line, so I get this:

```
 1 pick d25ddb3 implementing #548
 2 pick 9e264b1 autostart also removes chocks, tie-downs and pitot tube cover
 3 pick e7ae16c autostarts handles oil and fuel contamination as well
 4 
 5 # Rebase 48f653e..e7ae16c onto 48f653e (5 command(s))
...
```

**Comment by onox** [comment]
> I can only see the commits previous to the introduction of NEWS.md

In that case your last commit should be 48f653ef283d4b4f36542efe6ce528513bb57a75, so just do `git pull` to get your stuff back.

**Comment by gilbertohasnofb** [comment]
Success! :smile:

**Comment by onox** [comment]
Nice.

**Comment by onox** [comment]
So you wanted to move `autostart` to `Nasal/c172p.nas`?

**Comment by gilbertohasnofb** [comment]
Yes, I will do it right now then we can merge this. As for the NEWS.md, see the PR https://github.com/Juanvvc/c172p-detailed/pull/553

**Comment by onox** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Hmm, it's a bit more tricky than I thought. In the `engine.xml`, the function `autostart` is first defined in its own block (so far so good):

```
var autostart = func (msg=1) {
[...]
};
```

But then it's called in the following block:

```
setlistener("/controls/switches/starter", func {
	if (!getprop("/fdm/jsbsim/complex"))
	    autostart(0);
    var v = getprop("/controls/switches/starter") or 0;
    if (v == 0) {
        print("Starter off");
        # notice the starter will be reset after 5 seconds
        primerTimer.restart(5);
    }
    else {
        print("Starter on");
        setprop("/controls/engines/engine/use-primer", 1);
        if (primerTimer.isRunning) {
            primerTimer.stop();
        }
    }
}, 1, 0);
```

Which makes use of the function `primerTimer`. So if I moved the `autostart` function as well as this block to c172p.nas, how would it be able to call `primerTimer` from there? Should it also be moved?

**Comment by onox** [comment]
Why would you move the whole listener?

**Comment by onox** [comment]
You can just call `c172p.autostart(0);`

**Comment by gilbertohasnofb** [comment]
> You can just call c172p.autostart(0);

Derp. Thanks :smile:

**Comment by gilbertohasnofb** [comment]
Done. Seems to be working well.

**Comment by onox** [comment]
There are a few tabs (in the old code as well). Could you remove those?

**Comment by gilbertohasnofb** [comment]
Sure.

**Comment by gilbertohasnofb** [comment]
I fixed all `.nas` files, they were a mess.

**Comment by onox** [comment]
:+1:

**Pull request merged**
