### PR TITLE
Bug 745

### PR DESCRIPTION
**Pull request by dg-505**
I did some work on the tutorials

I tested it a bit, but I might have missed something.

Any thoughts?

Cheers
Jonathan

### CODE REVIEW

**Comment by onox** [comment]
I'm not sure about that merge commit in which you merged Juanvvc:bug-745 to your own bug-745.

**Comment by onox** [comment]
The best thing would have been to make sure that you got our bug-745 without creating a merge commit and then adding your own commits. That would have made the PR much cleaner.

If you used `git pull` it should have fast-forwarded. (You can add `--ff-only` to prevent a merge commit and just stop if it can't fast forward). I think I'll just cherry-pick your last (and single) commit.

**Comment by onox** [comment]
I've cherry-picked the commit and added it to our `bug-745` branch. I'll open a new PR for it. Just for anyone's information, this is what I did:

```sh
git remote add dg-505 https://github.com/dg-505/c172p-detailed.git
git fetch dg-505
git cherry-pick -esS 7d98252051fda9f0bde17cd73e70d352e5b9769b
git remote remove dg-505
```

**Comment by dg-505** [comment]
>I've cherry-picked the commit and added it to our bug-745 branch. I'll open a new PR for it. Just for anyone's information, this is what I did:

I have no idea what this did, but it looks good.
Thanks :smile:

**Comment by onox** [comment]
With cherry picking you can add a single commit instead of a sequence of commits (which is what you get when you merge something).

Just some general advice: try to bring your local branch (`dg-505:bug-745`) up-to-date with the target branch (`Juanvvc:bug-745`) before you starting working on something. If you then create a PR, it will show just one nice single commit instead of a dozen commits (including a bunch of merge commits).

If you look at the "Files changed" tab you see that there were all kinds of irrelevant changes visible in this PR. That makes it more difficult for a developer to review your changes and also see what code actually gets added to the repository. In a large project a developer is likely to close such a PR and say "Open a new PR with a clean branch", especially if the contribution comes from a new person that they have never worked with before.

**Pull request closed without merging**
