### PR TITLE
No-previews to effect and accessory models.

### PR DESCRIPTION
**Pull request by wlbragg**
See #557

### CODE REVIEW

**Comment by wlbragg** [comment]
See #557

**Comment by onox** [comment]
Can someone with fgrun test this?

**Comment by gilbertohasnofb** [comment]
I will do that.

**Comment by gilbertohasnofb** [comment]
It works, but I have three comments:

- the lights should all be off IMO as they look strange:
screenshot from 2015-11-22 11 12 44

- the engine should be off, but at the moment we can see both the stopped propeller AND the propeller disk:
screenshot from 2015-11-22 11 12 49


- maybe we should use the default livery, not D-EEQA

**Comment by wlbragg** [comment]
I guess I'm the only one with FGRun so I'll merge this. It's only 4 "noprivew" statements.

**Comment by gilbertohasnofb** [comment]
@wlbragg I also have FGRun, and I posted some issues about this branch above, did you not receive my previous posts?

**Comment by gilbertohasnofb** [comment]
I wrote:

> It works, but I have three comments:
> 
> - the lights should all be off IMO as they look strange:
> - the engine should be off, but at the moment we can see both the stopped propeller AND the propeller disk:
> - maybe we should use the default livery, not D-EEQA

**Comment by onox** [comment]
Just add some new commit to `bug-557` and create another PR.

**Comment by wlbragg** [comment]
@gilbertohasnofb, sorry, I didn't see the comments.

OK, I'll take care of it this afternoon, stepping out for a bit.

**Comment by gilbertohasnofb** [comment]
Okay, no rush! Then we do as @onox said above, use the same branch and create another PR

**Comment by wlbragg** [comment]
I must be blind, I thought those pictures were the ones I posted elsewhere, I too noticed the funny lighting and posted a question about it. I didn't think anyone responded (because I thought those were my images, didn't bother to look at them again, ha). Too funny, anyone watching this must know I am brain dead!

**Comment by gilbertohasnofb** [comment]
Hopefully not to brain dead! :stuck_out_tongue_closed_eyes: I remember seeing your pictures before, but I had (and still have) no idea how to fix it. I reposted now just to remind that IMO that needs to be taken care of

**Comment by onox** [comment]
Issues fixed in branch `bug-562`. See PR #572

**Pull request merged**
