### PR TITLE
sounds: Reduce alpha by -0.5 deg when using flaps

### PR DESCRIPTION
**Pull request by onox**
Stall AoA is reached earlier with flaps, so reduce the alpha by -0.5 deg
instead of +0.5 for each 10 degree of flaps.

See PR #328

### CODE REVIEW

**Comment by onox** [comment]
Well done @onox, excellent work! :+1:

**Comment by wlbragg** [comment]
Yes, I second that. Sorry onox, I am FDM challenged and really have no business reviewing these types of changes, otherwise I would have merged it!

**Comment by gilbertohasnofb** [comment]
> I am FDM challenged and really have no business reviewing these types of changes

Same here, onox.

**Comment by wkitty42** [comment]
@onox what they said... i'm just trying to keep up and test things :wink:

**Pull request merged**
