### PR TITLE
"Preflight Inspection" checklists

### PR DESCRIPTION
**Pull request by dg-505**
Added a checklist for preflight inspection, removed twice contained items (in ```Preflight``` and ```Before starting engine```, and expanded the Securing aircraft checklist.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@dg-505 First of all, thanks for this work! :smile: I had a quick look on your code and I have only two comments about it:

- you are mixing tabs and spaces for indentation, while we decided to use 4 spaces. You can probably set your text editor to use 4 spaces instead of tabs.
- what about automatically opening the dialogs when clicking in the items for fuel quantity (one for each tank), fuel contamination check and oil check?

**Comment by dg-505** [comment]
1. I'm gonna remove the tabs and replace them with 4 spaces, thanks for the hint.
2. I didn't implement the "execute"-button for these items, because for other items this will *execute* the required action (setting/releasing the parking brake, switch lights on/off, etc.). After that you can jump to the next chacklist item. Just opening the dialog window, wouldn't execute the fuel sampling, the oil check, etc. Even if the "execute"-button would open the dialog, you couldn't jump to the next step, i.e. you wouldn't really *execute* this item.

You know what I mean? It's explained a bit awkward...

**Comment by gilbertohasnofb** [comment]
I think I know what you mean, and I don't know what's the best solution. I just wonder if opening the dialogs wouldn't give a help, even if it doesn't change the status of the item because it's not _executing_ it.

**Comment by dg-505** [comment]
IMHO the "execute"-button should set the status to green/checked. Maybe there is a way to to the fuel sampling and the oil check with this button, but this is beyond my skills, and I don't know enough about this system...

**Comment by onox** [comment]
@dg-505 Does this PR fix a particular issue?

**Comment by onox** [comment]
The execute action for closing the baggage door on page 2 is instant. Use:

```xml
<binding>
    <command>nasal</command>
    <script>c172p.baggageDoor.close();</script>
</binding>
```

**Comment by onox** [comment]
Perhaps change "Beacon" to "Beacon light" and add a marker.

**Comment by onox** [comment]
No other remarks. Nice work @dg-505.

**Comment by dg-505** [comment]
@onox this fixes partially issue #493

**Comment by dg-505** [comment]
Okay, thanks @onox . Corrected.

**Comment by onox** [comment]
@dg-505 Does this PR closes #493 or are there things remaining to be fixed?

**Comment by dg-505** [comment]
It doesn't close it, because I plan to add the preflight inspection and the securing aircraft procedure to the tutorials. When this is done, I think #493 can be closed.

**Pull request merged**
