### PR TITLE
Bug 728: Animate panel/radios light knob

### LINKED ISSUE #728: Animate panel/radios light knob
I don't think this knob is animated.
lightswitch

### PR DESCRIPTION
**Pull request by onox**
Fixes #728

### CODE REVIEW

**Comment by onox** [comment]
@gilbertohasnofb You need to force pull.

**Comment by gilbertohasnofb** [comment]
Checking it now. By the way, what does the green tag "Verified" means on the side of your commits?

**Comment by onox** [comment]
Click on it :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
"This commit was signed with a verified signature." What that means? I want that on my commits as well hahaha

**Comment by onox** [comment]
Click on the blue link inside the small window that appeared :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
I see, quite cool! I will read about it later.

About the PR, I have only two comments/questions:

- I thought that the radio illumination controlled the radio of the metallic parts of the radio, not of the displays. Are you sure you can have the radio on but by setting the illumination to 0% have them display nothing?! 
- would be really useful if we could have a different cursor when hoovering over each of the two options, like in the c182. In that project, we use :left_right_arrow: and :arrow_up_down: for each dual knob like this. Is that possible here?

**Comment by onox** [comment]
> I thought that the radio illumination controlled the radio of the metallic parts of the radio, not of the displays.

Do you mean just comm0 and comm1? So no adf, dme, and autopilot?

**Comment by gilbertohasnofb** [comment]
I meant that you are fading the displays themselves where the digits are shown, and I didn't think that was possible. I thought that radio illumination was the illumination of the radio stack as a whole, including the metallic parts but NOT affecting the displays. But I may be completely wrong here...

**Comment by gilbertohasnofb** [comment]
I will check how the c182 works on that now, just give me a second

**Comment by onox** [comment]
I think the metallic parts are affected as well, but I doubt that is how it is working in RL. I would say that it's the LED's that are controlled by the knob.

**Comment by gilbertohasnofb** [comment]
The 182 has two of these dials. The inner part of the first dial controls only the lightning of some buttons (such as the button that swaps frequencies) and the inner part of the second dial controls the lightning of the stack. None of the four options (inner, outer, first or second) affect the displays themselves.

I really wonder why would one be able to fade the radio digits out, that sounds at least dangerous and not useful at all to me. But once again, that is just a guess.

**Comment by gilbertohasnofb** [comment]
I really think they both should control flood lights (one for panel instruments, one for radio). See this:

> Instrument panel and switch and control panel lighting is providedby flood lighting, integral lighting, and post lighting (if installed). Lighting intensity is controlled by a dual dimming rheostat equipped with an outer knob labeled PANEL LT, and an inner knob labeled RADIO LT, located below the throttle. 

From a 172RG POH

**Comment by gilbertohasnofb** [comment]
Although it later states:

> The engine instrument cluster, radio equipment, digital clock and magnetic compass have integral lighting and operate independently of post or flood lighting. The intensity of instrument cluster, radio, and digital clock lighting is controlled by the inner knob on the light dimming rheostat labeled RADIO LT; compass lighting is controlled by the outer knob labeled PANEL LT. Rotate the knobs clockwise to obtain the desired light intensity. However, for daylight operation, the engine instrument, digital clock and compass lights may be turned off while still maintaining maximum light intensity for the digital readouts in the radio equipment. This is accomplished by rotating the knobs full counterclockwise. The flood lightslpost lights are also turned off for daylight operation by rotating the PANEL LT knob full counterclockwise.

:confounded:

**Comment by onox** [comment]
Which knob do you want to control the plastic parts of the radio stack? The "instrument" knob or the "radio" knob? Currently it is the "instrument" knob.

"radio" knob controls the LED's.

**Comment by gilbertohasnofb** [comment]
> "radio" knob controls the LED's.

That's the thing, I thought it didn't. It turns out it does, but it does something more. As far as I could understand from the quote above from the POH, it controls BOTH the flood radio light + digital displays, and the leftmost position has the special property of 0% flood light and 100% display lights.

**Comment by onox** [comment]
> it controls BOTH the flood radio light + digital displays

@Juanvvc @algefaen @tigert Does it?

**Comment by gilbertohasnofb** [comment]
I found the pages concerning these lights in the 172P POH (I have the one from 1982):

> The engine instrument cluster (if post lights are installed), radio equipment, and magnetic compass have integral lightning and operate independently of post or flood lightning. The intensity of this lightning is controlled by the inner knob on the light dimming rheostat labelled RADIO LT; rotate the knob clockwise to obtain the desired light intensity. However, for daylight operation, the compass and engine instrument lights may be turned off while still maintaining maximum light intensity for the digital readouts in the radio equipment. This is accomplished by rotating the RADIO LT knob full counterclockwise. Check that the flood lights/post lights are turned off for daylight operation by rotating the PANEL LT knob full counterclockwise.

From Section 7, page 29.

**Comment by gilbertohasnofb** [comment]
Though this is a different model than ours, this is how A2A handled their 172, watch from 5:30: https://www.youtube.com/watch?v=hQnqxKkqWxY

**Comment by gilbertohasnofb** [comment]
@onox about the mouse cursor having different arrows for the inner and outer knobs, is there a way of implementing that? 

As for the functionality of the knob, I posted the question [here](http://aviation.stackexchange.com/questions/27506/cessna-172-light-rheostat) so maybe we can get a clear answer soon.

**Comment by gilbertohasnofb** [comment]
I got a great answer in that link I posted in the previous message, and I am quite convinced now that the RADIO LT shouldn't dim the digital displays. Can you take a look at it?

**Comment by onox** [comment]
So what needs to change relative to what is currently in `bug-728`? Let the radio light knob just control the flood light of the radio stack (which is currently handled by the instrument light knob)? And don't do anything with the digits in the radio stack?

**Comment by gilbertohasnofb** [comment]
Hi @onox , so what I think it should be done is the following:

- PANEL LT should control _only_ the gauges backlight, nothing else
- RADIO LT should _not_ affect the digital displays. I become convinced that what the POH is referencing is not the digital LED displays we have but rather those old type of radios which have backlight such as [this one](http://i.stack.imgur.com/qPuOM.jpg); so I think RADIO LT should activate only the backlight of all buttons in the radio stack

I also would consider the following:
- as mentioned before, using different cursors for the inner and outer knob of the light rheostats as right now it's really tough to guess where you are clicking, particularly at night!
- lowering a bit the illumination of the autopilot in the radio stack as it's clearly over illuminated when compared to the other elements:

fgfs-screen-001

**Comment by onox** [comment]
When I read https://aviation.stackexchange.com/questions/27506/what-lights-does-the-cessna-172-light-rheostat-control I would say that the RADIO LT knob controls the digital LED displays *and* the backlight of the buttons in the radio stack.

**Comment by gilbertohasnofb** [comment]
Yes, I re-read it and it seems to imply that. So I suppose this would be the way to go:

- PANEL LT should control _only_ the gauges backlight, nothing else
- from let's say 1% to 100%, RADIO LT should affect the digital displays and also activate only the backlight of all buttons in the radio stack 
- At 0% instead of turning the radio lights completely off we have the "special" daylight configuration, so that the digital displays of all radios are at maximal intensity, but no backlight is activated on the buttons
- as mentioned before, using different cursors for the inner and outer knob of the light rheostats as right now it's really tough to guess where you are clicking, particularly at night!
- lowering a bit the illumination of the autopilot in the radio stack as it's clearly over illuminated when compared to the other elements

What do you think?

**Comment by onox** [comment]
That's a good summary. I'll work on it tomorrow.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
@gilbertohasnofb Implemented all the changes in your comment.

You or someone can test this.

**Comment by gilbertohasnofb** [comment]
I will test it now.

**Comment by gilbertohasnofb** [comment]
Looks great, @onox! Thanks for implementing this! :+1: 

Still, in the future we could ask someone with RL experience to confirm the behaviour of the RADIO LT knob, just for the sake of making sure our understanding of those text sources is correct.

**Comment by onox** [comment]
Yeah.

**Comment by algefaen** [comment]
> Still, in the future we could ask someone with RL experience to confirm the
> behaviour of the RADIO LT knob, just for the sake of making sure our
> understanding of those text sources is correct. 

I'll check next time I'm at the airport and have time. If there's any other
panel related things or extra photos / videos that would be useful, feel free
to give me a hint.

**Comment by gilbertohasnofb** [comment]
@algefaen that would be great, thanks! And if I can think of something else to be checked/photographed, I will let you know.

**Pull request merged**
