### PR TITLE
Bug 628: Startup tutorial

### PR DESCRIPTION
**Pull request by dg-505**
See #628

Fix throttle setting, add lights off and master/alternator off in initial step.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Should we investigate the tie-downs problem a bit further before merging this, since it is also described in https://github.com/Juanvvc/c172p-detailed/issues/628?

**Comment by gilbertohasnofb** [comment]
(clearing milestone as this is a PR not an issue, sorry)

**Comment by onox** [comment]
The tutorial sets `/sim/model/c172p/tiedownL`, etc. to `0` instead of setting `/sim/model/c172p/securing/tiedownL-visible`, etc. to `false`.

**Comment by onox** [comment]
`/sim/model/c172p/chock` has been moved to `/sim/model/c172p/securing/chock`.

`/sim/model/c172p/pitot-cover` has been moved to `/sim/model/c172p/securing/pitot-cover-visible`.

**Comment by dg-505** [comment]
To my kowledge it doesn't matter if a value is set to 0/false or 1/true. In the end it does the same thing.

>  /sim/model/c172p/chock has been moved to /sim/model/c172p/securing/chock.
/sim/model/c172p/pitot-cover has been moved to /sim/model/c172p/securing/pitot-cover-visible.

Ah, that's the point.

**Comment by gilbertohasnofb** [comment]
@dg-505 Some problems:

- at line 86 shouldn't you add `<value>0</value>`? My alternator isn't being set to off.
- for some reason, the pitot tube cover, tiedowns and chcoks are still not being removed, but I can't spot the problem with your code... did you test it? Is it working for you?
- strobe, beacon and nav lights, as well as pitot heat, are not being set to off to me, and I also can't find a problem in the code

Can you try to reproduce it?

**Comment by gilbertohasnofb** [comment]
@dg-505 actually, if you notice, the problem happens to all properties that come after the alternator in that code; so I figured that by adding `<value>false</value>` below line 86 the problem would be solved, and voila! It is :)

Some other problems though:

- circuit breakers are not being set by the tutorial
- nor is the carburetor heat
- the primer lever starts at the position we last left it, though I think it should start in the position IN
- instrument light is also not being set to 0%

**Comment by onox** [comment]
> To my kowledge it doesn't matter if a value is set to 0/false or 1/true. In the end it does the same thing.

It depends on how weakly/strongly typed the language is. For the property tree system it doesn't matter much whether you use 0/false or 1/true, so yes it does the same thing, but I still find it ugly if numbers are being used for a property that has a boolean type. Also, if you use true/false you clearly see (when you read the code) there are only two valid values: true or false. If you use numbers, it could be anything: 0, -1, 1, -2, 2, etc.

**Comment by onox** [comment]
@dg-505 @gilbertohasnofb Do the problems in https://github.com/Juanvvc/c172p-detailed/pull/629#issuecomment-165099315 and https://github.com/Juanvvc/c172p-detailed/pull/629#issuecomment-165102115 still need to be fixed?

**Comment by gilbertohasnofb** [comment]
@onox Yes, they do still need to be fixed. I don't think @dg-505 has made any more commits since I spotted that little problem with the code (so I don't think he committed the fix yet), and that list of other things that need to be set is still not implemented AFAIK.

**Comment by gilbertohasnofb** [comment]
In the next week or so I will be travelling and I probably won't be able to collaborate much (if at all), but once I have time I will take a look at this and try to fix it myself if @dg-505 doesn't do it first. Happy new year to you all!! :beers:

**Comment by dg-505** [comment]
Fixed it. Sorry guys for the delay :smiley: 
Also happy new year! :tada:

**Comment by gilbertohasnofb** [comment]
@dg-505 :+1: Thanks, but I think those other things I pointed out at https://github.com/Juanvvc/c172p-detailed/pull/629#issuecomment-165102115 still need to be taken care :smile:

**Comment by dg-505** [comment]
You check the circuit breakers in the tutorial step as of line 225 and the Carburetor Heat as of line 438 so I consider it unnecessary to set them when initializing the tutorial because later you make sure they're all in and the Carb heat is cold before starting the engine.

**Comment by gilbertohasnofb** [comment]
> I consider it unnecessary to set them when initializing the tutorial because later you make sure they're all in and the Carb heat is cold before starting the engine.

You are completely right, it actually simulates then someone forgetting these things in the wrong position. So now that you corrected the primer lever and instrument lights, I think this is ready to be merged. I will test it right now.

**Comment by gilbertohasnofb** [comment]
@dg-505 Okay, I tested and everything seems good, but I still have a bit of a problem with the last item from https://github.com/Juanvvc/c172p-detailed/issues/628 about the throttle values (sorry to be picky). The thing is the tutorial seems to want the throttle to be between 10 and 12%, and not between 10-15% as you commented in the code. Anyway, I think even that is too few and that it should be more like between 10-2x % (maybe 22-23 as the upper bound). If you think about it, our autostart function itself sets the throttle to 20% and the engine does turn on normally, so it does make sense to allow it in the tutorial as well. What do you think?

**Comment by dg-505** [comment]
> sorry to be picky

No problem, it's good to have high quality standards :)

The following commit will allos the throttle to be between 15 and 20 %

**Comment by dg-505** [comment]
>12 and 20 %

Oops, this is just a typo mistake in the commit message :laughing:

**Comment by gilbertohasnofb** [comment]
Looks good, thanks a lot! :+1:

**Pull request merged**
