### PR TITLE
Fixed issue #119

### PR DESCRIPTION
**Pull request by dg-505**
I fixed issue #119.
I only uploaded the .blend file with out having exportet it to the c172p-detailed.ac, because Juanvvc mentioned once, that not all of the .blend-file is exportet to the .ac-file and I don't know how to export it properly.
Maybe someone with more knowledge about blender could export the .blend file?

### CODE REVIEW

**Comment by Juanvvc** [comment]
Thanks dg-505! As usual, I'll be up there flying in real life during the weekend. I won't be able to check your merge until Monday.

**Comment by wlbragg** [comment]
These changes really should be done in c172p-detailed-damage.blend also.

That is why I questioned the other issue and update with the struts as it also needed to update c172p-detailed-damage.blend and c172p-detailed-bushkit.blend.

Any thought on how this is best accomplished?

**Comment by dg-505** [comment]
The only object i've changed is "fuselage1". Is it possible to just copy/paste this object to c172p-detailed-bushkit.blend and c172p-detailed-damage.blend (as long as it has no other modifications)?
Unfortunately I'm not at home this weekend, so I can do this the earliest on monday evening.

**Comment by wlbragg** [comment]
"The only object i've changed is "fuselage1"
Oh, good, that in not part of the damage or bushkit. You just made my day!
If you do anything to the wing, ailerons or flaps, then I will have my hands full. They are the objects that are duplicated and then damaged.

**Comment by onox** [comment]
What's going to happen with this PR? It cannot be merged unless you know how to merge binary .blend files :wink: Can it be closed?

**Comment by Juanvvc** [comment]
No, please, keep the PR open to remind me about this issue. I'll blend manually the .blend file.

**Comment by Juanvvc** [comment]
Manually merged, I close this issue. Thanks!

**Pull request closed without merging**
