### PR TITLE
Bug 551, 533, and 555

### LINKED ISSUE #551: Create water rudder lever
Create water rudder lever for float and amphibian models

Reference: http://austingwatson.com/yahoo_site_admin1/assets/docs/Cessna172FloatplanePOH.32573617.pdf

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #551, #533, #555  

Wait to merge this until I get the water rudder system deploy animation and  limiting of amphibious gear retraction/deploy to power only finished. Right now the animation is only "rudders up". I am going to tie in a  "water rudder system deploy" animation to the "rudders down" position and event. Plus limit the gear from being deployed or retracted without power available.

### CODE REVIEW

**Comment by onox** [comment]
I've added an animation to toggle the water rudders by clicking on the handle.

@wlbragg Could you please remove the spaces from the object names? The names are already very inconsistently named in the model files (CamelCase, under_score, etc.) :confused: No need to introduce a third convention :laughing:

**Comment by wlbragg** [comment]
Will do, I should have noticed that it was even more inconsistent. Thanks for adding the animation toggle to the handle,  never even occured to me to do that.

**Comment by wlbragg** [comment]
OK, are we done?

**Comment by wlbragg** [comment]
Oops, I need to finish the renaming with your select animation.

**Comment by gilbertohasnofb** [comment]
So I just tested this, the water rudder system seems to be working perfectly well and the baggages are now properly UV mapped (thanks again!). I just noticed that both the pontoon and the amphibian models have two strange polygons showing inside the cockpit, see:

fgfs-screen-002

To better view them, simply switch from the default to float in the sim and you will see those polygons popping up into existence.

**Comment by onox** [comment]
> OK, are we done?

Yes.

One small comment: when you have added a local commit and you see here on Github I have added a commit as well, you can do `git pull --rebase` instead of `git pull` to put your commit on top of (in this case) mine, thereby avoiding a merge commit.

> I just noticed that both the pontoon and the amphibian models have two strange polygons showing inside the cockpit

I see those things in the master branch as well, so not caused by this branch. Shall we fix those small mistakes when we get the new model from @thevirtualfer?

**Comment by gilbertohasnofb** [comment]
>>  I just noticed that both the pontoon and the amphibian models have two strange polygons showing inside the cockpit

> I see those things in the master branch as well, so not caused by this branch. Shall we fix those small mistakes when we get the new model from @thevirtualfer?

Sounds good. I will open an issue for it anyway so we don't forget about it, ok?

**Comment by onox** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/556

**Pull request merged**
