### PR TITLE
Bug 238

### LINKED ISSUE #238: Apply new click sounds to switches
Apply new click sounds to cockpit switches (lights, master, avionics switch, etc.). Should be fairly soft.

Could you give me a hand with this, @onox?

### PR DESCRIPTION
**Pull request by onox**
Fixes #238 

If the sounds are too loud compared to other sounds, just say how much I should lower the volume.

### CODE REVIEW

**Comment by onox** [comment]
:warning: Don't delete the branch just yet, in case we want to add more sounds. :warning:

**Comment by onox** [comment]
:warning: Don't merge this PR just yet, we're adding more sounds. :warning:

**Comment by onox** [comment]
:warning: Don't merge this PR just yet, we're adding more sounds. :warning:

**Comment by onox** [comment]
:warning: Don't merge this PR just yet, we're adding more sounds. :warning:

**Comment by onox** [comment]
This PR is ready after @gilbertohasnofb has fixed `trim.wav`.

**Comment by gilbertohasnofb** [comment]
@onox I did the conversion but I still can't hear any sounds from the trim. I think the problem may be something else than the bit resolution of the sound. Anyway, the new `trim.wav` is already committed.

**Comment by onox** [comment]
@gilbertohasnofb Actually, it does work now. I don't get any error anymore, it's just that the volume is too soft.

**Comment by gilbertohasnofb** [comment]
> I don't get any error anymore, it's just that the volume is too soft.

Glad to hear that! So just tweak the volume to your taste and I guess we are done with this PR, right?

**Comment by onox** [comment]
I've pushed the commit. I don't really like the sound that much, but it's not as confusing as using `scroll.wav`. It's good enough for now.

**Comment by onox** [comment]
If you're happy with the branch, then you may merge the PR :smile: :+1:

**Comment by gilbertohasnofb** [comment]
> If you're happy with the branch, then you may merge the PR

I just tested and all works now, so I am merging right now.

> I don't really like the sound that much

To be honest, I don't like it much either, but it was the best I could come up with so far. The thing is I can't really find any sound that resembles a plastic piece softly moving. Let's leave this sound for now, and if I manage to find something better then I will simply substitute it directly in the main repository, okay?

**Comment by onox** [comment]
> okay?

OK :+1:

**Comment by gilbertohasnofb** [comment]
>> I don't really like the sound that much

> To be honest, I don't like it much either

Okay, so I added a new trim sound. What do you think, @onox?

**Comment by onox** [comment]
Yeah, the new sound sounds better :smile:

**Pull request merged**
