### PR TITLE
Bug 413

### LINKED ISSUE #413: Improve behavior of beacon and strobes
Use MP properties to indicate whether the lighting is enabled/disabled instead of actually being visible/invisible at the moment. The latter is unreliable because the duration in which a light is visible is very short, too short sometimes for MP.

### PR DESCRIPTION
**Pull request by onox**
Fixes #413

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox Ok, same place then. I am ready!

**Comment by gilbertohasnofb** [comment]
@onox I forgot, are you at mpserver02.flightgear.org or mpserver03.flightgear.org ?

**Comment by wlbragg** [comment]
You guys got this?

**Comment by onox** [comment]
@wlbragg Yes, we are done testing. PR can be merged.

**Comment by onox** [comment]
@wlbragg I have now freed up int[0], int[1], int[2], and int[3]. Those are used by the immat system on old c172p versions. After most people have upgraded to 3.6, we can start using them for new stuff.

**Comment by onox** [comment]
I'm gonna sleep now :sleeping: I'll try to fix #293 tomorrow evening.

**Comment by wlbragg** [comment]
OK, sleep tight!

**Comment by onox** [comment]
I have set the deadline to 14th so we have one more day of testing. @wlbragg Can you make a lot of noise on the forum so that people know they have one more day of testing?

**Comment by gilbertohasnofb** [comment]
> I'm gonna sleep now

Same here. See you guys tomorrow for more testing!

**Comment by wlbragg** [comment]
Will do!

**Comment by onox** [comment]
Make sure people really do `git pull` because I moved some MP properties, and we shouldn't waste our time on fake bugs.

**Comment by onox** [comment]
Have a good night! :smiley:

**Comment by gilbertohasnofb** [comment]
You too!

**Pull request merged**
