### PR TITLE
Improvements to Ground Equipment menu

### LINKED ISSUE #867: Improve Ground Equipment dialog
Improve Ground Equipment dialog:

- add recharge battery button for when the Power Unit is connected
- add fuel adjustment when the portable fuel tank is on toggled

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #867 

Improvements to Ground Equipment menu:
- added a button to recharge the battery when ground power unit is connected
- added a button to add/remove fuel when fuel trailer is toggled
- improve conditionals to the regular individual fuel tank dialogs (the ones that open when you click on the fuel tank caps above the wings)

### CODE REVIEW

**Comment by onox** [comment]
I have some comments: this gives two "Recharge battery" buttons. I don't mind adding a "Recharge battery" button to the Ground Equipment dialog, but in that case the button in Aircraft Options should be removed and the label "Battery charge: 100.0 %" should be added to the Ground Equipment dialog as well.

About the fuel tanks dialog: do you have a strong preference for showing that new dialog or should we show the regular Fuel and Payload Settings dialog? If former, the number in the Fuel Tanks dialog should be put next to each other, just like in the Fuel and Payload Settings dialog.

Also the name "Add/remove fuel" could be changed to "Show fuel tanks dialog" or "Add/remove fuel..." (notice the 3 dots -- in a (non-web) GUI those dots indicate that the button does not perform a (potentially destructive) action but shows a new dialog)

**Comment by gilbertohasnofb** [comment]
Great, I agree with most here:

> I don't mind adding a "Recharge battery" button to the Ground Equipment dialog, but in that case the button in Aircraft Options should be removed and the label "Battery charge: 100.0 %" should be added to the Ground Equipment dialog as well.

Hmm, I can remove the battery button from the aircraft dialog, but I am not sure what to do about the charge. Maybe I am overthinking this, but I didn't add it before because it would give an impression that the power cable recharging the battery was also measuring it? I also had left the battery button and charge in the aircraft dialog as to have a quick way of recharging the plane, since the ground equipment takes a million click (open dialog, add ground power unit, connect cable, recharge, disconnect cable, remove power unit, close dialog). But I am really on the fence on this, if you think it's really a good idea to have it only in the ground equipment dialog I am up for it. Let me know so I can fix it.

> About the fuel tanks dialog: do you have a strong preference for showing that new dialog or should we show the regular Fuel and Payload Settings dialog? If former, the number in the Fuel Tanks dialog should be put next to each other, just like in the Fuel and Payload Settings dialog.

I thought of doing that, but because that dialog also shows weight of baggage and pilots, I thought it had nothing to do with the fuel trailer (same reason why the fuel tank cap have their own dialogs). I will improve the new dialog as you say then.

> Also the name "Add/remove fuel" could be changed to "Show fuel tanks dialog" or "Add/remove fuel..."

I think adding the "..." would look better indeed, going to fix it

**Comment by onox** [comment]
> I also had left the battery button and charge in the aircraft dialog as to have a quick way of recharging the plane, since the ground equipment takes a million click (open dialog, add ground power unit, connect cable, recharge, disconnect cable, remove power unit, close dialog). But I am really on the fence on this, if you think it's really a good idea to have it only in the ground equipment dialog I am up for it. Let me know so I can fix it.

It's a bit inconsistent I think that the recharge button in the GE dialog is realistic (you need to connect the cable), but in the AO dialog, you can basically cheat.

**Comment by gilbertohasnofb** [comment]
> It's a bit inconsistent I think that the recharge button in the GE dialog is realistic (you need to connect the cable), but in the AO dialog, you can basically cheat.

:+1: removing from AO and adding charge label to GE

**Comment by gilbertohasnofb** [comment]
@onox It turned out that just by connecting the cable the battery is recharging, but slowly just like in RL. But then again, if one runs out of battery the repair button will recharge it immediately. So I propose to get rid of the recharge battery button on both dialogs and add the battery charge to the ground equipment dialog only, agreed?

**Comment by onox** [comment]
I kinda like the "Battery recharge" button :smile:

**Comment by gilbertohasnofb** [comment]
> I kinda like the "Battery recharge" button

Hmm, if you really want it we can have it as "recharge battery now!" or something like that, but I really like how realistic is to use the cable. And as I said, there are ways around it for the lazy people (and careless to have ran out of battery): either repair the plane or speed up time to make the charge faster. I really don't see the point of the button any longer to be frank!

**Comment by onox** [comment]
Ok, let's remove the buttons.

**Comment by onox** [comment]
But add the label to the GE dialog?

**Comment by onox** [comment]
Perhaps rename the "Connect Ground Power Unit" to "Connect GPU to aircraft"?

**Comment by onox** [comment]
or "Connect unit to aircraft"

**Comment by gilbertohasnofb** [comment]
> But add the label to the GE dialog?

Yes, I did that.

> Perhaps rename the "Connect Ground Power Unit" to "Connect GPU to aircraft"?
> or "Connect unit to aircraft"

Sounds better indeed

I am just tweaking the fuel dialog and then I will push

**Comment by gilbertohasnofb** [comment]
@onox this is done, you can check it again

**Comment by onox** [comment]
I'll check it, in the mean time you can check my commit in `bug-866` :wink:

**Comment by onox** [comment]
Changes look good. One last comment: could you let align the battery charge label with the checkbox "Connect GPU to aircraft". (so label has same indentation as that checkbox)

**Comment by onox** [comment]
Fuel Tanks dialog is :+1:

**Comment by onox** [comment]
I can fix `aircraft-dialog.xml`.

**Comment by onox** [comment]
... when I merge the PR.

**Comment by gilbertohasnofb** [comment]
> Changes look good. One last comment: could you let align the battery charge label with the checkbox "Connect GPU to aircraft". (so label has same indentation as that checkbox)

Sure :+1: 

> Fuel Tanks dialog is :+1:

Great to hear it!

> I can fix aircraft-dialog.xml.

Because of the previous PR? Sure, thanks then!

**Comment by gilbertohasnofb** [comment]
@onox done

**Comment by onox** [comment]
Nice work @gilbertohasnofb :+1: :smile:

**Comment by gilbertohasnofb** [comment]
Thanks a lot @onox! :smile: 

(by the way, I already added all this work of today to the list of new features/bug fixes)

**Pull request merged**
