### PR TITLE
Bug 453: Inconsistent damage reporting to user

### LINKED ISSUE #453: Inconsistent damage reporting to user
Not sure if this is worth mentioning but I noticed we popup pontoon and wing damage but not gear.

### PR DESCRIPTION
**Pull request by onox**
Fixes #453 

* Damage sound when gear breaks
* Scratch sound when tail or broken gear scratches over the ground
* Improved center of nose wheel rotation animation
* Removed textual notifications (tooltips). See https://github.com/Juanvvc/c172p-detailed/issues/453#issuecomment-170369759

### CODE REVIEW

**Comment by onox** [comment]
@gilbertohasnofb You started the branch from a commit in `bug-633` instead of master, so I have removed that commit from this branch (`bug-453`). If you want to test:

```sh
git checkout bug-453
git reset --hard b299f860c39d11b06c5bdd810b7249e8008b63a5
git pull
```

**Comment by gilbertohasnofb** [comment]
> You started the branch from a commit in bug-633 instead of master

Oops, my bad...


> If you want to test:

I reset that branch as you instructed, I will test now.

**Comment by gilbertohasnofb** [comment]
Really good! I love how you applied the new sound, it sounds really realistic IMO :+1:

**Comment by wlbragg** [comment]
Outstanding, first time I heard some of the new sounds!

**Pull request merged**
