### PR TITLE
New shadow and reflection cubes.

### PR DESCRIPTION
**Pull request by wlbragg**
Replaces #687 - Added smoother interior shadows

Adds new shadow and reflection cubes.
Renames black and default cubes to shadow and reflection respectively.
It includes unused red, blue and greyscale sets of cubes for independent users use.
The blue and greyscale will be reworked by @jarlarntzen to match the resolution and proportions of the other three, but at a later date.

Please test and merge, it should be ready to go.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
These png files are looking good! I will test this now in the sim then merge it. But if this replaces #687 then could you please close that PR?

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
I love the new shadows, and the reflections are good as well. We can merge this right away, but I noticed something related to the reflections: sometimes they look really out of proportion! Look at this shot:

fgfs-screen-001

The reflection shows a gigantic white cockpit which is kind of strange... But to be honest, this is seen from unusual angles, and also I think this issue has always been present in our cube maps, so we may as well just merge this now and maybe rethink about it later. What do you say, would you like to open an issue for this or do you think there is no room for improvement, @wlbragg ?

**Comment by wlbragg** [comment]
If you see this with the existing cubes then OK lets merge, but yes I would like to take a look at it in the future to see if it can be corrected so a new issue would be appropriate.

**Comment by gilbertohasnofb** [comment]
:+1: See https://github.com/Juanvvc/c172p-detailed/issues/699

**Pull request merged**
