### PR TITLE
Bug 311

### LINKED ISSUE #311: Wheels of amphibious do not rotate
1. [x] The wheels of the amphibious gear do not rotate. Not even in singleplayer.

2. [x] Object RightWheel uses `gear/gear[1]/rollspeed-ms`, but should be using `gear/gear[2]/rollspeed-ms`

3. [x] `rollspeed-ms` is not transferred automatically, so we should do aliasing again.

We should decide how many properties we want to alias. If you want to send `rollspeed-ms` over MP for each gear, then we would have to alias 7 properties (3 for default + 4 for pontoons). We can also use the `/velocities/groundspeed-kt` property for the nosegear (1 for default + 2 for pontoons). That will result in 5 properties (`groundspeed-kt` + 2x `rollspeed-ms` for default + 2x `rollspeed-ms` for pontoons)

### PR DESCRIPTION
**Pull request by onox**
Fixes #311

### CODE REVIEW

**Comment by wlbragg** [comment]
Looks good, including checking it over MP.

**Comment by wlbragg** [comment]
How do we get this over to 3.6?

**Comment by onox** [comment]
@wlbragg It's part of master now. We only fix 3.6 bugs in master. Once in a while I'll merge master to version-3.6 branch.

**Comment by onox** [comment]
But for now we don't need to merge it to version-3.6 branch because no decision about (dis)allowing CC-BY licensed files has been made yet.

**Comment by wlbragg** [comment]
Oh, OK I was wondering why you made that comment. So we have no place to put 3.8 work?

**Comment by wkitty42** [comment]
i don't understand why there is not a branch for 3.6-fixes...

git checkout version-3.6
git checkout -b version3.6-fixes
do the work
push it back into version3.6-fixes for testing
push it to version3.6 for updating the release
push it to master to update that code

and all this time keep working in master doing 3.7+ features and such... it is just a matter of ensuring that you're in the proper branch and that the merges go back into the proper ones when necessary...

what am i missing? can't github have PRs for branches??

**Comment by onox** [comment]
@wkitty42 We're using master branch for fixing 3.6 bugs. On 17th of July we start working on 3.8 features. version-3.6 only exists because Stuart wanted a branch so he could possibly replace the CC-BY sounds with GPL ones.

**Comment by onox** [comment]
> So we have no place to put 3.8 work?

@wlbragg Not really no. But if you do your 3.8 work in a feature branch (bug-?) then we can merge it on the 17th of July.

**Comment by wlbragg** [comment]
OK, that works.

**Comment by wkitty42** [comment]
i still don't understand why this route was chosen and what the problem is with having branches for release versions... i'm not going to try to explain the logic for a fourth time... i drew a line graphic in the forum topic when this came up on the 16th... it showed how to have master for current work and you leave branches behind for each release... if a release needs a bug fix, you checkout that branch and then make a fix branch for it, create the fixes, then merge them back into the release and any other branch, including master, that needs the fix... that way you can fix releases, have new release candidates for the next release and still keep on working on master for all the new features... apparently the graphic and explanations have been ignored? :disappointed:

**Comment by onox** [comment]
@wkitty42 We didn't do a release last week, we only did a feature freeze. In July we do the actual release. See http://wiki.flightgear.org/Release_plan

**Comment by wkitty42** [comment]
@onox i know we didn't but that would/should become the release branch when we get to that point... it is just a name i used to describe it anyway...

**Pull request merged**
