### PR TITLE
adding names to README

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Adding names and more information about the work done by @onox and @Juanvvc (you guys deserve more credit than just having your nickname inside a parenthesis). I also added the name of @wkitty42.

So before merging, each one of you please confirm you are fine with these modifications as I don't want to force anyone here to add more information than they are comfortable with, okay?

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Or if you three would rather have only your pseudonyms that's obviously also fine! This PR is merely a suggestion, ok? If any of you don't like this, we can either change it or simply delete this PR and this branch.

**Comment by onox** [comment]
I put the names in an unordered list so that it looks better on Github. Also replaced the image, but you can revert that if you want.

**Comment by gilbertohasnofb** [comment]
The new image is fine with me, as well as how you handled the list. Let's just wait for @Juanvvc and @wkitty42 and see what they want to do with their real names and contribution descriptions, ok?

**Comment by onox** [comment]
Sure.

**Comment by wkitty42** [comment]
i use both pseudonyms interchangeably and always have since being knighted with the "waldo kitty" moniker back in the early '80s by some lady friends on a large communications system that i administrated at that time... everyone on the 'net who knows me knows me by them...

**Comment by gilbertohasnofb** [comment]
@wkitty42 so that means you are okay with the new README file? If so, then we are just missing a confirmation by @Juanvvc to then merge this PR.

**Comment by gilbertohasnofb** [comment]
@onox may I also suggest something: since you don't want to use your name, maybe you could remove the parenthesis around (onox) in this file as it looks a bit strange, what do you think? (yep, I am a professional nitpicker!)

**Comment by wkitty42** [comment]
@gilbertohasnofb yes, i'm ok with it... i forgot to write that explicitly :laughing:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
> maybe you could remove the parenthesis around

You could do that, but then you should also remove them around @thevirtualfer's name.

**Comment by gilbertohasnofb** [comment]
> You could do that, but then you should also remove them around @thevirtualfer's name.

Yep, of course. Although I am still waiting for his response by mail, as maybe he would like to include his name still. If he doesn't answer me until shortly before our deadline, then I will do that for both pseudonyms.

**Comment by gilbertohasnofb** [comment]
Hi guys, so since we didn't hear from Juan nor from thevirtualfer, I left them only with their pseudonyms and no real names. I removed the parenthesis from their pseudonyms (and from onox as well). I hope they will be fine with the description I wrote about their work, and I hope I didn't miss anything. Also, can you think of anyone we might be forgetting to add in this file? Is there some other contributor that should be there? If not, @onox feel free to check and merge this.

**Comment by onox** [comment]
When do you qualify as a contributor? >= 10 commits or >= 1 commit?

**Comment by gilbertohasnofb** [comment]
I really don't know, that's difficult to judge...

**Comment by gilbertohasnofb** [comment]
I don't think it's only about number of commits. E.g.: tigert and wkitty42 have very few commits, but their help throughout this project has been extremely significant and I am happy to see their names recognized in this file.

**Comment by onox** [comment]
We can add @dg-505, he added the new starter switch and exhaust smoke.

**Comment by gilbertohasnofb** [comment]
I was writing you an e-mail about it right now :smile: Okay, so I will add him and then we can merge this I guess. Later, if he wants his full name there as well, he can simply change this file directly in the master.

**Comment by onox** [comment]
:+1:

**Comment by dg-505** [comment]
Thanks :smile:

**Comment by gilbertohasnofb** [comment]
@dg-505 Would you like to have your real name added as well or just the pseudonym?

**Comment by dg-505** [comment]
Yeah, I can add it mayself later today.

**Comment by gilbertohasnofb** [comment]
Ok. And by the way, if you have a chance, please check #157. We moved it to the 3.8 milestone because we are having troubles, but if you'd have a chance of fixing it for the 3.6 release I'd be very happy! (that is, if you know how to do that)

**Comment by dg-505** [comment]
I'll have a look

**Comment by gilbertohasnofb** [comment]
Thanks a lot!

**Pull request merged**
