### PR TITLE
Bug 673: Add some damping to the PID controllers of the tiedowns

### LINKED ISSUE #673: Wings may oscillate if tied down while fps is very low
If the the fps is low and the wings are tied down, the aircraft may start to oscillate a bit. Adjust the PID controllers to add some damping.

### PR DESCRIPTION
**Pull request by onox**
Fixes #673

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
How can I test this, @onox?

**Comment by wlbragg** [comment]
Really the only way is to see if the aircraft remains stable when tied down. You can apply force to it when tied down and also watch that reaction.
I can do this one if you want?

**Comment by gilbertohasnofb** [comment]
> Really the only way is to see if the aircraft remains stable when tied down.

I never thought it was unstable before!

> I can do this one if you want?

That would be nice :smile:

**Comment by wlbragg** [comment]
That was fun, very stable. I applied full prop and it stretched slightly. I hit it with a 110 knot wind from the front, enough to collapse the front gear and it held tight. Works great!

**Comment by onox** [comment]
Haha, try to press Ctrl+u while being tied down, quite funny to see :laughing:

**Comment by onox** [comment]
> I never thought it was unstable before!

I would become unstable at low fps (< 15 or something).

**Pull request merged**
