### PR TITLE
Some 3D-improvements

### PR DESCRIPTION
**Pull request by dg-505**
Did some improvements wit the exterior model: More detailed struts for the landing gear, and corrected issue #158.

### CODE REVIEW

**Comment by Juanvvc** [comment]
dg-505, I cannot accept your push without the .blend file, or we won't be able to make any additional modifications.

Please, keep in mind we are using a custom plugin to export the .ac file from blender. Our version of the plugin also manages groups, and (afaik) some of these groups are used in the .xml file. Are you using our plugin in Blender?

Unfortunately, it seems ropbox is not working in this moment and I had the plugin there. Guys, we need adding a .zip file with the blender plugin asap!

**Comment by dg-505** [comment]
I'm sorry, I use AC3D instead of Blender so there are no .blend-files. Is there a way to modify the .blend-file anyway?

**Comment by onox** [comment]
@dg-505 Why don't you install Blender (it's free) and learn it? You already know how to do 3D modelling in general, so it's just a matter of learning how Blender works.

Without an updated .blend file, the .ac file is not very useful.

**Comment by Juanvvc** [comment]
Let me think about it, but I cannot see an easy way to manage this situation. I'm afraid we all must use the same tool to modify our files, and AC3D is not free in any sense.

One "easy" way (unless you modified all objects!) is that you make a list of the name of the objects you modified, and I can import them in blender.

If you insist in using AC3D with some model (there is nothing wrong about it!), please, keep in mind you'll be assigned as the maintainer of that model and you alone will have the responsibility of changing it as many times as we need. And you are talking here about the main model in the project!

**Comment by dg-505** [comment]
I already have blender, but I find AC3D easier and more intuitive to use.
Would it be possible to import the changed c172p-detailed.ac into blender and then save the file as the c172p-detailed.blend?

**Comment by Juanvvc** [comment]
No, because our current .blend files include lots of additional things not exported to the .ac file. For example, temporal version of some objects or views.

We can include individual objects from the .ac file, but you must tell us the name of the objects you changed. Please, don't make us check all the objects to identify your changes!

**Comment by dg-505** [comment]
I messed some things up, better you delete this pull request... :neutral_face:

**Comment by onox** [comment]
@dg-505 Do you need git instructions to revert your repository to "Some 3D-improvements" the commit? (deleting the "Added c172p-detailed.blend" and "Delete c172p-detailed.blend" commits)

**Comment by dg-505** [comment]
Yes, it would be very nice if you help me with that.

**Comment by onox** [comment]
1. Do `git remote -v` and check that `origin` is dg-505/c172p-detailed

2. Do `git branch` and check that you're in branch `master`

3. Do `git log` and check that the top commit is "Delete c172p-detailed.blend"

4. Do `git reset --hard 87e3d0dc5decbdbbea9bf0122010f8c30ddc043a`

5. Do `git log` and check that the top commit is "Some 3D-improvements"

6. Do `git push`. Github should complain that the branches are different.

7. Do `git push --force`. If you now go to Github you should see that the "Added c172p-detailed.blend" and "Delete c172p-detailed.blend" commits have disappeared.

**Comment by dg-505** [comment]
Worked. Thank you, onox :grinning:

**Comment by dg-505** [comment]
@Juanvvc I modified the following objects:
- LeftWheelStrut
- RightWheelStrut
- NoseWheelStrut
- TopLink
- BottomLink
- Exhaust

**Comment by Juanvvc** [comment]
Thanks! Do you remember which objects you modified in #187 ?

**Comment by dg-505** [comment]
I modified "InstrumentCover" in c172p-detailed.ac
Other changes of 3D objects were made in seperate files.

**Comment by Juanvvc** [comment]
Thanks, dg-505. I have manually imported your enhanced objects.

**Comment by dg-505** [comment]
Thanky you :sweat_smile:

**Pull request closed without merging**
