### PR TITLE
Disable 3D shadow for other c172p in MP because of #387

### LINKED ISSUE #411: Disable 3D shadow for other aircraft over MP
Because of issue #387 we should disable the shadow for other aircraft.

### PR DESCRIPTION
**Pull request by onox**
Fixes #411

### CODE REVIEW

**Comment by onox** [comment]
@gilbertohasnofb Can you help test this?

**Comment by gilbertohasnofb** [comment]
@onox absolutely! Let's meet FHAW

**Comment by gilbertohasnofb** [comment]
I will be at ramp A like before

**Comment by gilbertohasnofb** [comment]
@onox I am there waiting for you

**Comment by onox** [comment]
I'll be there.

**Comment by gilbertohasnofb** [comment]
@onox should I open an issue for the lights being invisible when inside the cockpit (that is, when the glass is in between the lights and the point of view)?

Also, today I will probably go to sleep soon as I feel quite sick, but tomorrow I should be home during most if not all day, and I can help testing everything we still miss for the release milestone, okay? Just let me know if I can help with anything.

**Comment by onox** [comment]
> should I open an issue for the lights being invisible when the view is inside the cockpit (that is, when the glass is in between the lights and the point of view)?

Yes, please.

**Comment by gilbertohasnofb** [comment]
Done, see #414

**Comment by onox** [comment]
@gilbertohasnofb do you have the problem that you cannot move the time slider in the replay dialog?

**Comment by gilbertohasnofb** [comment]
@onox I will test it right now, I almost never use the replay.

**Comment by gilbertohasnofb** [comment]
Tested, I can move the slider normally. Also, I have no problems with the attitude indicator nor heading indicator during replay, the only slightly buggy thing I see is that when dragging the slider too fast, the vertical speed indicator goes crazy for a second or two.

**Comment by onox** [comment]
Hmm, I cannot move the time slider because I have strange unnamed views in the combo box. I submitted a patch to the mailing list, but I'm being ghosted by the core devs.

**Comment by gilbertohasnofb** [comment]
Do you want me to do any specific test about this? Here it's working just fine.

**Comment by onox** [comment]
Can't think of any test.

**Comment by gilbertohasnofb** [comment]
> I have strange unnamed views in the combo box

Why is that so? All my views have names in the replay dialogue (and in the view menu as well).

**Comment by onox** [comment]
@gilbertohasnofb Could you help test PR for #413? I have it ready in a minute.

**Comment by gilbertohasnofb** [comment]
Sure!

**Comment by onox** [comment]
Almost ready, just need to move nav lights MP property.

**Comment by gilbertohasnofb** [comment]
ok

**Comment by onox** [comment]
@gilbertohasnofb See PR #415

**Pull request merged**
