### PR TITLE
Bug 633 light effects, Bug 670,418 seat mounts, Bug 314 glass effects

### LINKED ISSUE #633: Improve our lights
Improve our lights using https://github.com/HHS81/c182 as reference. That plane's lights are not only smaller and more realistic, but they also fade away depending on the angle (e.g. starting at the landing lights head on makes it be seen at its brightest, and then it fades when the camera moves away).

lights

To be done
* [x] add new lights texture to branch `bug-633`

~~rename texture `transparent2.png` to `lights.png` and also in the `.ac` model (main and damage models)~~

* [x] rename texture `transparent2.png` to `lights.png` in the Model folder as well as in the Blender files (both main model as well as damage model)
* [ ] resize lights in Blender, particularly strobes (way too large) and the red beacon lights in the tail as well (just a bit too large)
* [x] solve the "squareness" problem of the flashing lights (see screenshots below)
* [x] add taxi lights to ~~front gear~~ ~~right~~ left wing, together with landing light (but weaker and pointing downwards)
* [x] make lights dependable on viewing angle in Blender (see c182 repository for an example of aircraft using this technique)

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #633, #670, #418, #314 

:warning:  Not to merge until thoroughly tested! :warning:

I don't want to wait to long on this though as the blend touches a lot of thing and we need to make a decision and get this merged before we get too many conflicts.

### CODE REVIEW

**Comment by wlbragg** [comment]
The conflict is in the blend and ac, I don't think it will be an issue but I need to check it out closely.

**Comment by wlbragg** [comment]
@onox, I merged master into 633 locally and fixed the conflict with no ill effects. How do we do this online?

**Comment by onox** [comment]
If you have verified that after merging `master` into `bug-633`, that the resulting .blend and .ac files are those from the `bug-633` branch, then you can push `bug-633` to Github. The PR should then indicate that the conflict has been resolved.

**Comment by wlbragg** [comment]
:+1:

**Comment by onox** [comment]
PR fixed #418 and #670 (seats)

Almost fixed #314 (the reflection color is a bit too blueish) and #633 (see comments by @gilbertohasnofb)

Lights are much more pleasant to look at :smile:

**Comment by wlbragg** [comment]
The tail beacon is adjusted as good as I can get it. Landing and taxi light are set side-by-side but the effect is worse when they both are on then when they were on top of each other.
Strobe planes in Blender were reduced by about 25 percent, 50% reduction was too small.

**Comment by onox** [comment]
> but the effect is worse when they both are on then when they were on top of each other

Have you tried giving the taxi light and landing light a slight difference on the x axis (nose to tail)?

> Strobe planes in Blender were reduced by about 25 percent, 50% reduction was too small.

I liked the strobes as they used to be, they're now a bit difficult too see from a distance. But maybe that's my opinion, I could be wrong.

**Comment by onox** [comment]
@wlbragg I have modified the visibility arc range of the nav lights a bit. Use `git pull --rebase` instead of `git pull` in case you have already committed something locally.

**Comment by onox** [comment]
@wlbragg If I look in Blender, I see the red/green lights have a cone that isn't really 180 deg. That causes the lights to become invisible too soon when viewed from the front.

**Comment by gilbertohasnofb** [comment]
@onox are you sure they are supposed to be 180 degrees? I once came across this image here, but I didn't check if the values are correct:

**Comment by onox** [comment]
The same goes for the tail nav light:

nav-lights-cones

@gilbertohasnofb The actual visibility range can be controlled via the "flash" animation.

**Comment by onox** [comment]
@gilbertohasnofb Whatever is easier for @wlbragg. I have already adjusted the XML, but the cone object itself reduces the visibility too earlier:

wing-nav-light-cone

**Comment by gilbertohasnofb** [comment]
Well, I leave this decision to you two. I just wanted to share something I had once come across, but personally I have no idea how these lights should look in RL so :no_mouth:

**Comment by onox** [comment]
So I think that the actual cone object should be wider than the "flash" animation allows, because currently you can see it's a cone (You can see it's a cone when you look at the light at the edge angles of the cone).

**Comment by onox** [comment]
Currently the min value of the "flash" animations are still 0.5, that could be later set to a lower value or even 0.0.

**Comment by onox** [comment]
In other words: I think the cone should be a bit wider at the front, so that the "flash" animation reduces the visibility to 0.0 *before* you actually reach the edge of the cone.

**Comment by wlbragg** [comment]
So the cones need to be bigger? I don't understand what the cones do. What if you angled them forwards slightly to get the forward area covered?

**Comment by onox** [comment]
Let me make a FG screenshot to show the problem

**Comment by onox** [comment]
When you approach the edge of the cone:

fgfs-screen-449

**Comment by onox** [comment]
I could try to rotate it in XML... let me check.

**Comment by onox** [comment]
Hmm... I think best solution would be to widen the cone a bit in Blender.

**Comment by onox** [comment]
The front side that is, see https://github.com/Juanvvc/c172p-detailed/pull/678#issuecomment-174602619

**Comment by onox** [comment]
@wlbragg Can you measure the width of the cone in Blender?

**Comment by wlbragg** [comment]
I think I see. For the range of view, angle wise, I thought I noticed by increasing to the larger area or angle in the XML, that we have a little room to rotate the cone slightly forwards and still see get a view (left side) from 90 - 180, admittedly though, I don't know exactly what the cone is for.
Is it only to hide the light by its shape?
Same thing for the strobes, is it that you need a surface (or vert ice) to attach a light to?
Then you can use XML to position where that light is to appear?
If we moved the light to the convex side of the cone would it take on that range of view instead of
< 180 it would be >180? I'm not suggesting this, only trying to learn  about the lighting.

Yes I can measure it, hang on.

**Comment by onox** [comment]
I think the cones are just vertices to which you attach the `lights.png` texture.

**Comment by onox** [comment]
> If we moved the light to the convex side of the cone

What do you mean with this?

**Comment by wlbragg** [comment]
Crude measure is 0.358 m

**Comment by wlbragg** [comment]
That was left wing cone.

**Comment by onox** [comment]
> that we have a little room to rotate the cone slightly forwards and still see get a view (left side) from 90 - 180

For the red/green nav lights, the range is 110 deg, from 0 deg from nose to 20 deg behind wing. So I think we could just rotate the `navlight_left` and `navlight_right` objects around the z-axis a bit so that one side is perfectly aligned with the x axis?

**Comment by onox** [comment]
> Crude measure is 0.358 m

I meant in degrees :wink:

**Comment by onox** [comment]
Like this:

nav-light-new-cone

**Comment by onox** [comment]
@wlbragg I think `navlight_back` is OK. I measured that I can rotate it about 11 deg to align it with the y axis, which means the cone is 180 - 11*2 = 158 deg wide, wider than the required 140 deg, so tail nav light is OK.

**Comment by onox** [comment]
Red/green nav lights need to be rotated about 11.3 degrees.

**Comment by wlbragg** [comment]
the side cones 180 - 9.239 * 2 ?

**Comment by onox** [comment]
I measured 11 degrees by selecting the object and then pressing: r z 11.0

**Comment by onox** [comment]
How did you measure?

**Comment by onox** [comment]
But I'm not sure if that is what we want. Currently the normal of the cone is 90 deg from the x axis (perpendicular to it).

**Comment by onox** [comment]
We could set it to 35 (that's 55 deg from the nose).

**Comment by onox** [comment]
Then we just need to make sure that the "flash" animation has a min value of 0.0 instead of 0.5.

**Comment by onox** [comment]
@wlbragg Try this:

1. Rotate the red/green nav lights 35 around the z axis (towards the front)

2. Go to the flash animations (assuming you have done `git pull --rebase` to get my commit)

3. Change `<min>` from 0.5 to 0.0

4. Change `<offset>` from 0.0 to -0.5

**Comment by onox** [comment]
These settings might give a shorter descend from 3.0 to 0.0:

power = 2.0
factor = 12.0
offset = -3.6
min = 0.0
max = 3.0

**Comment by wlbragg** [comment]
Sorry, doing two things at the same time today.

cone3

**Comment by onox** [comment]
If I select face angles, I see 67.955: (90 - 67.955) / 11.0225

**Comment by onox** [comment]
Anyway, could you try 35 deg + the settings from https://github.com/Juanvvc/c172p-detailed/pull/678#issuecomment-174621852?

**Comment by onox** [comment]
I'm interested to know whether that gives better results :smile:

**Comment by wlbragg** [comment]
OK, I know nothing so definitely don't go by my GUESS!

Yes, give me a little bit and I'll see what I can do.

**Comment by onox** [comment]
It seems XML changes here are OK, so I think if you just rotate red/green nav lights in Blender 35 deg, that should be enough.

I'm currently adjusting the tail light XML.

**Comment by onox** [comment]
@wlbragg Have you done any commits already? XML is ready here locally.

**Comment by wlbragg** [comment]
No I haven't. Will it mess up the XML if I also adjust pos x and y by a tiny bit?

**Comment by wlbragg** [comment]
Rotate 35 deg cuts into the wind just a tad.

**Comment by onox** [comment]
> Will it mess up the XML if I also adjust pos x and y by a tiny bit?

No.

**Comment by wlbragg** [comment]
OK

**Comment by wlbragg** [comment]
I'm pulling now, I haven't done anything since my last commits.

**Comment by wlbragg** [comment]
You didn't touch anything in the blend?

**Comment by onox** [comment]
Nope. Just the XML file. But my latest changes in the XML aren't pushed yet.

**Comment by onox** [comment]
I can push those as well if you want.

**Comment by wlbragg** [comment]
Yes, go ahead.

**Comment by onox** [comment]
OK, hang on a second.

**Comment by wlbragg** [comment]
:+1:

**Comment by onox** [comment]
Pushed.

**Comment by wlbragg** [comment]
:+1:

**Comment by wlbragg** [comment]
I thought the strobes were fine the way they were, as you can never see the size of the circle but you need the distance. You want me to put that back or a compromise?

**Comment by onox** [comment]
If you want to revert shrinking the strobes, go ahead.

**Comment by onox** [comment]
Who said the strobes were too big?

**Comment by gilbertohasnofb** [comment]
me... :disappointed: I didn't try the new ones yet, but I really think the original was were huge, they were like twice the landing light size!

**Comment by onox** [comment]
But they blink, so don't they simulate blinding you a bit? :smile:

**Comment by gilbertohasnofb** [comment]
Not really, I think there is a difference between the halo and the "ball" of light itself. It just looked outrageously large to me!

**Comment by wlbragg** [comment]
But do we ever see the ball?

**Comment by gilbertohasnofb** [comment]
Well, I do

**Comment by onox** [comment]
@gilbertohasnofb What do you think of the new strobes when you zoom out?

I'll let @wlbragg decide what he thinks best.

**Comment by gilbertohasnofb** [comment]
But really, you two are doing all the work so the decision should be up to you. I was just giving my 2 cents.

**Comment by wlbragg** [comment]
@gilbertohasnofb, check them now for size and distance and give me your opinion!

**Comment by gilbertohasnofb** [comment]
@onox I will give it a try, just a sec

**Comment by wlbragg** [comment]
Moving the cones changes the XML x, y and z position of the lights. So I am trying to get it as close as I can by adjusting the cones and then the rest will have to be done in the XML. My experience has been lots of small corrections until its right. Also it may not be an issue cutting into the wing, still testing.

**Comment by gilbertohasnofb** [comment]
Hmm, I love the new size of the strobes, here it's zoomed out:

fgfs-screen-002

For me the problem comes from two things:

- is the strobe also sensitive to angles? I had the impression they are, and I think they shouldn't be.
- aren't the strobes and nav lights too close to each other? From the same distance as in the image above, but looking from the front, I can just see a short blink and it's indeed very difficult to tell the strobes are there.

**Comment by onox** [comment]
Just rotate those red/green cones 35 deg, as I said before. That should put the normal of them at 55 deg from the nose.

**Comment by onox** [comment]
@gilbertohasnofb Did you try zooming out to 150 meter?

**Comment by gilbertohasnofb** [comment]
That's the most zoom out I can get by pressing `x`. Does zooming out via the menu allows more? I will try again

**Comment by wlbragg** [comment]
OK, try that. The nav lights may need a slight XML adjustment.

**Comment by onox** [comment]
@gilbertohasnofb Don't use x. That's the FOV. Use mouse wheel.

**Comment by gilbertohasnofb** [comment]
oh

**Comment by onox** [comment]
Make sure you have reset the FOV with Ctrl + x. Mouse wheel only works in select views like Helicopter View.

**Comment by wlbragg** [comment]
Taxi and landing light, I think I need to re-position their cones offset side-by-side (I hadn't done that, only in the XML) and see what kind of visual we get. Right now it's unacceptable. Also @onox, you think I should have the taxi light offset closer to the plane than the landing light?

**Comment by onox** [comment]
Yeah, maybe that will fix your problem. Not sure.

**Comment by gilbertohasnofb** [comment]
Okay, so I got it now to 150m and it looks fine to me:

fg3

@wlbragg look what happens once we get in the angle where the nav lights are visible:

fg2

Probably we should move the strobes a bit backwards so they don't superimpose each other. Or maybe make the strobes slightly "away" from the wings, so that it covers the nav lights when blinking (that may be a better option).

**Comment by wlbragg** [comment]
@gilbertohasnofb, OK choose which one you want to try first, offset sideways or in front?

**Comment by gilbertohasnofb** [comment]
@wlbragg sideways I think! it will probably look good from any angle, while the other may be sensible to problems. Let's see :smile:

**Comment by onox** [comment]
Navigation lights are OK now :+1:

**Comment by onox** [comment]
Hmm... although they intersect with the wing. @wlbragg If possible you could try an arc width of 110 deg for red/green.

**Comment by onox** [comment]
But the dimming of the nav lights is OK now when viewing from the front.

**Comment by wlbragg** [comment]
>Hmm... although they intersect with the wing.

Not sure what you mean, in blend they do but I don't see it in the visual.

>try an arc width of 110 deg for red/green.

Where?

**Comment by onox** [comment]
Let me make another screenshot.

**Comment by wlbragg** [comment]
The taxi and landing lights, the cones interfere with each other no matter what I do, any suggestions?

**Comment by onox** [comment]
nav-light-110

**Comment by wlbragg** [comment]
OK, got it!

**Comment by onox** [comment]
Or better give it some extra margin, 120. We limit it to 110 in the "flash" animation anyway.

**Comment by wlbragg** [comment]
I think I can do that, but what are you seeing and where that make you think that is necessary?

**Comment by onox** [comment]
https://github.com/Juanvvc/c172p-detailed/pull/678#issuecomment-174653303 Press F5 to refresh the page.

**Comment by wlbragg** [comment]
OK

**Comment by onox** [comment]
Do you see the image in that comment?

**Comment by wlbragg** [comment]
Yes, I see it now.

**Comment by onox** [comment]
:+1:

**Comment by wlbragg** [comment]
If I move it away (then the XML will need adjusted.

**Comment by onox** [comment]
Yes, you can update its position if you have too. The other settings (power, offset, factor, min, max) do not need to be adjusted. They are correct for now.

**Comment by wlbragg** [comment]
OK, this is going to take a little bit, I'm also adjusting the taxi and landing and strobes as I go. My refresh takes long enough that I like to get as much as I can out of each refresh of FG.

**Comment by onox** [comment]
You can do Debug > Reload Aircraft Model in FG :smile:

**Comment by wlbragg** [comment]
While we were debating it all I managed to get this, the artifact is where the cones overlap, We won't be able to allow any overlap, I don't think.
Thanks for the "debug" tip, I already use it, I've just worked on computers and in programming too long and have an aversion to waiting, it causes major stress anymore :smile: .
cone6

**Comment by onox** [comment]
Hehe. You're welcome.

**Comment by gilbertohasnofb** [comment]
@wlbragg Your image above looks very good to me! :+1:

**Comment by wlbragg** [comment]
OK, it's all really close. I have to run for about 30 minutes, test and let me know if it needs any further adjustments.

**Comment by wlbragg** [comment]
The strobes may need more offset, the landing and taxi are adjusted farther than in the last image and look at them from angle above the aircraft. The nav lights cannot currently be moved any closer to the plane without moving behind the cones (bad effect).
See ya all later.

**Comment by onox** [comment]
You moved the nav lights? :open_mouth: I thought you were going to modify the shape of the nav light cones. The nav lights seem to be visibly distant from the wing tips :frowning:

**Comment by wlbragg** [comment]
Re-positioned the taxi and landing cones and XML slightly, there was a bad effect when using just the taxi. I'm really happy with them now.

I need feedback on the strobes specifically.

**Comment by wlbragg** [comment]
>You moved the nav lights?

Yes, I thought either option was a possibility.
You think the shape will work better? I think I have the ability to do that, let me try if it is not close enough the way it is.

**Comment by onox** [comment]
It looks like the taxi and landing lights are good now :+1:

**Comment by wlbragg** [comment]
OK, close to perfection on the nav's

**Comment by wlbragg** [comment]
The only other thing is the strobe positions, I need @gilbertohasnofb to sign-off on that, I guess.

**Comment by onox** [comment]
Navigations lights are better now! :+1: :smile:

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry that I am a bit away, but I am keeping track of the conversation here. Should I test the new strobes now or do you need to work on them still?

**Comment by wlbragg** [comment]
Test them now and let me know what you think compared to the last time you saw the. That may give me an idea on how much more to move them, if any.

**Comment by gilbertohasnofb** [comment]
Ok, I will do it right now :+1:

**Comment by onox** [comment]
What do you guys think of the brightness of the tail nav light? I think it's a little bit too dim.

**Comment by wlbragg** [comment]
Me too!

**Comment by gilbertohasnofb** [comment]
I agree with that as well. But everything else is looking fantastic in my opinion, really beautiful work! :clap:

**Comment by gilbertohasnofb** [comment]
What a difference from the previous lights :smile:

**Comment by wlbragg** [comment]
:clap: :clap: :clap:

**Comment by onox** [comment]
I'm updating the XML of the tail. Also increased the brightness of the green nav light a little bit.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
Pushed. Are the brightnesses ok?

**Comment by gilbertohasnofb** [comment]
Testing now.

**Comment by gilbertohasnofb** [comment]
Looks much better, @onox! The only thing I would still modify before merging this PR is the tail red beacon:

fg

If we can't solve the collision, then maybe we should raise the light so it doesn't collide with the glass, what do you guys think?

**Comment by onox** [comment]
> maybe we should raise the light

I'm not fond of that idea :frowning:

**Comment by onox** [comment]
Perhaps split the beacon object into two parts and hide the top part when the light blinks?

**Comment by wlbragg** [comment]
Me either, I tried that locally and didn't like the results. 
What I don't know or understand is the XML off-set, what is that for?
Is there a way to offset the light only from the viewers perspective?

**Comment by wlbragg** [comment]
I already split it to be able to change the transparent texture. We can try hiding it.

**Comment by gilbertohasnofb** [comment]
Yes, we can try that, but it sounds like a hack to me. Heiko wasn't able to figure out why are we having this problem and the c182 isn't?

**Comment by wlbragg** [comment]
BeaconOff is the clear, red glass. BeaconMount is the base of it now (new  object).

**Comment by onox** [comment]
I meant the top half of th red glass. But it does indeed feel like a hack.

**Comment by onox** [comment]
@wlbragg The c182s doesn't have the problem. Maybe we should first check how that plane does it.

**Comment by wlbragg** [comment]
>I meant the top half of th red glass. But it does indeed feel like a hack.

Oh, I agree.

I tried offsetting in XML various different ways and it always offset in one direction only and not from the viewers perspective.

I'm not prepared to change Blender versions to run the suggested Python scripts.

**Comment by onox** [comment]
c182s seems to use a "blend" animation.

**Comment by wlbragg** [comment]
I can take another look at the c182 and see if I can recognize the differences and the technique used.

>c182s seems to use a "blend" animation.

Makes sense!

**Comment by onox** [comment]
And "alpha-test", "billboard", and "dist-scale". If I'm looking at the correct object (PlaneX)

**Comment by onox** [comment]
I don't mind if we ignore that little problem for now and merge this PR :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
Works for me!
I will take another look at the tail beacon later on and see if I can figure it out, but I am in favor of getting what we have merged and closed.

**Comment by gilbertohasnofb** [comment]
Okay, who wants to press the big green button? :yum: 

And I will open a new issue for the beacon!

**Comment by onox** [comment]
First! :laughing:

**Comment by gilbertohasnofb** [comment]
hehehe

(see: https://github.com/Juanvvc/c172p-detailed/issues/682 )

**Comment by wlbragg** [comment]
:+1: :clap:

**Comment by gilbertohasnofb** [comment]
:clap: very nice work!

**Comment by onox** [comment]
Yeah, the lights look great :smiley: Nice work guys

**Comment by wlbragg** [comment]
Agreed, thanks for all the help and training!

**Comment by onox** [comment]
Now someone else may merge that other PR that I opened today :wink:

**Comment by gilbertohasnofb** [comment]
> Now someone else may merge that other PR that I opened today 

Would you be able to check that, @wlbragg ? I still have to read two articles before going to sleep :sob:

**Comment by onox** [comment]
Thanks you @wlbragg :smile:

**Comment by gilbertohasnofb** [comment]
@wlbragg Oh, I see you just did, thanks!

**Comment by onox** [comment]
Could someone notify on the forum in the FGPromo thread that they should download the lastest master and reshoot the scene with the c172p. Mention that we have proper external glass reflection and better lighting now.

**Comment by wlbragg** [comment]
>notify on the forum in the FG promo thread

Done.

**Pull request merged**
