### PR TITLE
baggage models + implementation according to baggage weight

### LINKED ISSUE #441: 3D Luggage
* [x] clicking on the luggage door and opening it could also open the dialogue in which luggage can be added
* [x] similar to the passengers, we can add some very simple 3D luggage to that compartment in case the luggage weight is above a certain threshold

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #441 

- adds two pieces of baggage models borrowed from the Diamond-Da42
- improvements of baggage texture
- baggages only appear if weight is above a certain threshold

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox while you are checking things, maybe you also would like to check this PR? :wink:

**Comment by onox** [comment]
Yeah yeah :laughing:, I'm busy finishing up the speed of sound code.

**Comment by gilbertohasnofb** [comment]
:grin:

**Comment by onox** [comment]
Works. Could you right align the close button? (Just like Aircraft Options) (Also for the fuel tank windows).

**Comment by gilbertohasnofb** [comment]
> Could you right align the close button? 

Sure, I just thought it looked better like this but let's keep it coherent.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by onox** [comment]
GUI's often put buttons in the bottom right corner. Even here below this comment box on Github for example. FG is the exception I guess.

**Comment by gilbertohasnofb** [comment]
Feel free to merge this one as it is completely done.

**Comment by onox** [comment]
Adding a little bit of padding and then I'll merge it.

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
