### PR TITLE
fixing some walker bugs

### LINKED ISSUE #423: Walker has the wrong gender
Our walker has the wrong gender: while our pilot model is female, the walker is male.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #423 and #424.

I had to make a local copy of the `walker-include.xml` in order to change the gender of our walker into the correct one. The model is still shared though.

### CODE REVIEW

**Comment by wlbragg** [comment]
I'll leave this for @onox to review and close out, I know next to nothing about the walker code, but it looks good.

**Comment by gilbertohasnofb** [comment]
@wlbragg no worries!

**Comment by onox** [comment]
There's no need to include the whole XML file, you can just override settings. Put the following in `<sim>` (you can put it before `<aircraft-data>` for example):

```xml
<walker>
    <gender>1</gender>
    <altitude-ft>-5.0</altitude-ft>
</walker>
```

Modify `c172p-set.xml`. Remove the included walker file: `git rm Systems/walker-include.xml`.

Then commit with `git commit --amend`. Check results with `git log` (or `tig`). You should see 1 commit, but with different commit id. Force push.

**Comment by onox** [comment]
(Removed milestone so that only issues show up in the milestone page)

**Comment by gilbertohasnofb** [comment]
I tried overriding it before but it didn't work out, hence why I copied the whole xml. I will try again as soon as I can, using your instructions above

**Comment by gilbertohasnofb** [comment]
@onox Seems to have worked out.

**Pull request merged**
