### PR TITLE
Bug 338 engine

### PR DESCRIPTION
**Pull request by onox**
Fixes https://github.com/Juanvvc/c172p-detailed/issues/338#issuecomment-118703532

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I don't think I have enough knowledge to test this PR. Maybe @tigert or @dany93 could have a look on it.

**Comment by onox** [comment]
Sure you have, just press P and look at the EGT, fuel flow, oil, and RPM instruments. The needles should move when you start the engine and play with the throttle and mixture :smile:

**Comment by gilbertohasnofb** [comment]
@onox sure, that I can test! But I read your comment in the #338 issue and it seems to involve much more than that (e.g. Bendix King HSI not being vacuum based). I will test it and report it here.

**Comment by onox** [comment]
> (e.g. Bendix King HSI not being vacuum based).

It directly used `/orientation/heading-deg` instead of the one in `/instrumentation/`.

**Comment by dany93** [comment]
Tested

- Why press P? (maybe you mean"s"?)
- Fuel flow: where? Fuel *level* change if I change both tanks in "Fuel and payload" (160 and 180 hp)

For 160 and 180 hp:
- Fuel levels, yes
- EGT, yes, changes with mixture,
- RPM, yes
- Oil temperature, yes (also by cutting off battery)
- Oil pressure, yes

**Comment by onox** [comment]
> Why press P? (maybe you mean"s"?)

That's just the standard key binding to show the high-res panel.

> Fuel flow: where?

In the same indicator as the EGT. Fuel flow is just the gallons per hour.

**Comment by dany93** [comment]
Mistake! I've checked the normal panel!!!!

**Comment by gilbertohasnofb** [comment]
@dany93 are you planning to check this again?

**Comment by dany93** [comment]
Repaired. High-res panel, 160 and 180 hp.
Fuel flow, EGT (with mixture or throttle)), Oil Temp, Oil Press, RPM: everything OK

**Comment by onox** [comment]
One of you can merge it then :smile:

**Comment by dany93** [comment]
I have to leave.
Are ADF and HSI to be tested?

**Comment by gilbertohasnofb** [comment]
> One of you can merge it the

Ok, I didn't test it myself but all should be fine according to @dany93

**Comment by onox** [comment]
>Are ADF and HSI to be tested?

You can test them yes.

**Pull request merged**
