### PR TITLE
MP model fix

### PR DESCRIPTION
**Pull request by wlbragg**
Hopefully this is all done and I can move on. Someone,  please take a look and merge when satisfied.

### CODE REVIEW

**Comment by wlbragg** [comment]
Oh, may want to HOLD ON!. I forgot, I still haven't found the fdm/jsbsim/crash getting switched on bug. We don't want that in master as it breaks starting the aircraft unless you click on "repair" first.
Let me find this bug before we merge.

**Comment by onox** [comment]
Yes, I noticed it too, my plane is broken when I start FG. Other than that, the lightning properties still work :+1: 

Btw, if the wing is broken, shouldn't the landing light (for the left wing) and the navigation lights and strobes be turned off?

**Comment by onox** [comment]
I have fixed the issue. It reminded me of an old issue I encountered in [#103](https://github.com/Juanvvc/c172p-detailed/issues/103#issuecomment-87404364). You can merge the branch :shipit: :smile:

**Comment by wlbragg** [comment]
That is really funny. I was just getting ready to commit the same fix. Mine wasn't as elegant (I just setprop). Nor was I going to explained the situation as I figured it was just a hack fix. I figured it had to be the link between alias and the original props. But I don't understand why others don't pick up the bad values. Whatever, it's done and works.

**Comment by onox** [comment]
It is indeed a strange issue :confused:

For future readers:

`/params` is an absolute path to the `<params>` element, while `../../../../params` is a relative path. And the latter is quite error-prone because it requires the correct number of `../`.

**Comment by Juanvvc** [comment]
Keep in mind there is an animation that unselects (i.e., do not render) some parts in MP. This is mainly for the internal objects and instruments, but we can also add to this animation any other object. Also, I'm not sure if any Nasal code is executed locally for the remote aircraft.

**Pull request merged**
