### PR TITLE
Multi thunder

### PR DESCRIPTION
**Pull request by wlbragg**
I think even 2 more thunder sound modules and this would be optimal, especially if there were 2 or 3 different thunder sounds. It's really a nice feature, you guys did a great job. Very immersive, I really like the rain sound too.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
I am working on the two other thunder sounds, so please do not merge this yet.

**Comment by gilbertohasnofb** [comment]
Just need someone to program these sounds in the code (preferably randomly selected), then we can test and merge.

**Comment by onox** [comment]
@wlbragg I'm a bit confused again why I see these "Merge branch 'master'" commits again. Also these "interior lighting" commits are stranged.

I rather see you just do `git checkout bug-443` and modify `Nasal/c172p.nas` and `c172-sound.xml
` in that branch.

**Comment by gilbertohasnofb** [comment]
In that case, should I also push those two new thunder sounds to branch `bug-443`?

**Comment by onox** [comment]
Yes.

**Comment by gilbertohasnofb** [comment]
Okay, I am doing it right now.

**Comment by onox** [comment]
@wlbragg I think after you are in the `bug-443` branch, you could do `git cherry-pick 39eb9b67c317194d57f540b110e570c83112d75c`.

**Comment by onox** [comment]
@wlbragg I have already done it for you in branch `bug-443`. You can ditch this `multi-thunder` branch.

**Pull request closed without merging**
