### PR TITLE
Set file refactoring

### PR DESCRIPTION
**Pull request by onox**
Move some code in the -set.xml file to separate files + fix FlightGear version check for ALS shadow volume

### CODE REVIEW

**Comment by onox** [comment]
@Juanvvc, @gilbertohasnofb: I see c172p-detailed2-set.xml is largely the same with the original c172p-detailed-set.xml. Shall I modify c172p-detailed2-set.xml to depend on c172p-detailed-set.xml?

**Comment by gilbertohasnofb** [comment]
That sounds good. The c172p-detailed2-set.xml uses Dany's FDM, while c172p-detailed-set.xml uses the default FDM.

**Comment by onox** [comment]
I'll do that after the merge then (c172p-detailed2-set.xml doesn't exist in this branch yet). Can you give me a :shipit: or :+1:  if you're ok with the changes in the commits? :smile:

**Comment by wlbragg** [comment]
I fine with these changes, well done..

**Comment by gilbertohasnofb** [comment]
The changes sound good to me.

**Comment by onox** [comment]
Thanks @wlbragg :smile:

**Comment by wlbragg** [comment]
Thank you for the very professional code.

**Pull request merged**
