### PR TITLE
Fix missing side of pitot cover and re-size.

### PR DESCRIPTION
**Pull request by wlbragg**
Not really sure why it wasn't working. I had to rebuild it to get it to work correctly.

### CODE REVIEW

**Comment by wlbragg** [comment]
OK, I'm out of here until later!

**Comment by gilbertohasnofb** [comment]
Perfect, it works fine once again! I also pushed a better texture for the cover. And can I delete this branch or do we still plan to use it for something else?

**Comment by wlbragg** [comment]
Were done with it.

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
