### PR TITLE
Bug 339: Port fgpanel panel from old c172p

### LINKED ISSUE #339: Port fgpanel panel from old c172p
Fgpanel lets you view a special panel with 2D xml instruments on a separate monitor.

https://www.dropbox.com/s/y1zobptukekdit7/000fgpanel.jpg?dl=0

This is useful for making a flight training device, or if you just have two monitors, you can have the instrument panel on one.

There was a c172 fgpanel variabt in the old 172, we could port that and the protocol file over to this.

### PR DESCRIPTION
**Pull request by onox**
Fixes #339 

This PR adds a new menu item in the c172p menu that opens a web page showing the 12 instruments of the cockpit.

This is just the basics of the web panel. No knobs, oil, volt/amp instruments, or radio stack.

Run `fgfs` with `--httpd=8080` to test it. All needles should work.

You can see and interact with the radio via http://localhost:8080/instruments/kingradio.html

### CODE REVIEW

**Comment by onox** [comment]
After this PR has been merged, we should open a new issue for the knobs, oil, volt/amp instruments, and radio stack.

**Comment by gilbertohasnofb** [comment]
screenshot from 2016-02-08 22 17 33

Some problems with this PR: the RPm and the EGT values shown in FG are not the same as the ones shown in the web panel (the difference is quite huge!))

**Comment by onox** [comment]
@gilbertohasnofb That's because this branch still contain the old instruments in the 3D cockpit. That's obvious because your work was done in a different branch (`bug-690`).

**Comment by onox** [comment]
@wlbragg Could you give this a quick test?

**Comment by wlbragg** [comment]
Sure!

**Comment by wlbragg** [comment]
Looks fine, go ahead and merge if your ready.

**Pull request merged**
