### PR TITLE
Add and adjust contact points, add vertical stabilizer WOW hook

### PR DESCRIPTION
**Pull request by wlbragg**
Please test!
Way better than before. Seems to have eliminated the super-ball bounce and has some better wing tip drag effects.
Minor tuning could still be needed.

### CODE REVIEW

**Comment by onox** [comment]
@wlbragg If the code needs more tuning, you can just push another commit to the branch. No need for another PR.

**Comment by wlbragg** [comment]
Thanks, I found some errors and I am struggling to correct it. I tried amending locally but then it wont take it on GitHub. I'll try a straight commit to this branch and see if it will take it,

**Comment by onox** [comment]
You can do this:

`git pull --rebase origin contact-points`

**Comment by wlbragg** [comment]
I'm using a gui shell program. But I do have access to a cmd line shell. Let me try a straight commit.

**Pull request closed without merging**
