### PR TITLE
Bug 710: Disable ASI while pitot tube cover is visible

### LINKED ISSUE #710: ASI instrument still functioning with pitot tube cover
ASI instrument still works with pitot tube cover visible.

As a quick fix we should set it to 0. Better behavior will be implemented in #538.

### PR DESCRIPTION
**Pull request by onox**
Fixes #710 Flight recorder should work as well.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Something is strange: when I open the sim the pitot cover wasn't there, so I added it via the aircraft dialog. Then I start to speed up on the runway and after some seconds the pitot tube cover disappeared by itself and the AIS was alive. From that point on everything worked as expected (adding the pitot tube cover via both the aircraft dialog and via clicking on the 3D model). Restarting FG made the same behaviour happen, so it's reproducible here. Can you try and see if you also encounter this issue?

I also noted that the property `instrumentation/airspeed-indicator/serviceable` doesn't change any longer, are you using a different type of logic than before?

**Comment by onox** [comment]
> I also noted that the property instrumentation/airspeed-indicator/serviceable doesn't change any longer, are you using a different type of logic than before?

Yes, we're using `Systems/indicated-airspeed.xml`. the instrument in `instrumentation/airspeed-indicator` is unused.

**Comment by onox** [comment]
Can you monitor `/sim/model/c172p/securing/pitot-cover-visible` and `/fdm/jsbsim/velocities/vias-kts` while reproducing that problem?

**Comment by gilbertohasnofb** [comment]
Hmm, I can't reproduce it again. I am suspecting that it may have been due to the file where we save startup properties having some of the older values there. Now it behaved as expected.

**Comment by gilbertohasnofb** [comment]
Maybe @wlbragg can double check this just to make sure everything is working well.

**Comment by onox** [comment]
I couldn't produce your problem either.

**Comment by gilbertohasnofb** [comment]
Well, it's up to you, but given that @wlbragg seems to be online we could have one more person testing. I am just a bit neurotic with all these bugs we found just before making the release branch...

**Comment by wlbragg** [comment]
I actually had something weird like that happen right after I fixed it and refreshed my program. I think it was a saved state glitch.

**Comment by gilbertohasnofb** [comment]
And after that it started behaving normally? So I think it's the same thing I have seen. Let me do just one final test: I will delete my saved state file and try to see if all is working well, then merge this.

**Comment by gilbertohasnofb** [comment]
Yes, it all seem to be fine.

@onox the AIS also works well in the replay including setting itself to 0 when the cover is in place, but the pitot tube cover (3D model) doesn't show up. I suspect the same is true for chocks and tie-downs. Should I simply merge this now and open a new issue for it, or would you like to tackle it now?

**Comment by gilbertohasnofb** [comment]
Well, I just merged it and opened a new issue for the replay not showing the pitot tube cover, tie-downs and wheel chocks, see: https://github.com/Juanvvc/c172p-detailed/issues/712

**Comment by onox** [comment]
Commits backported to `release/2016.1`.

**Comment by onox** [comment]
> Well, I just merged it and opened a new issue for the replay not showing the pitot tube cover, tie-downs and wheel chocks, see: #712

Thanks for opening an issue about that :+1:  I'll leave it for the next release. We've backported enough fixes for now :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
Okay! Thanks for the fixes, I think that should be it for the release. Would you write Stuart to let him now that now we are really really really ready for the merge? :smile:

**Comment by onox** [comment]
@stuartbuchanan We've fixed the issue with the DME and some other issues, so branch `release/2016.1` can now be merged to FGDATA.

**Pull request merged**
