### PR TITLE
Fix #103 by forcing initialization of lighting state properties

### LINKED ISSUE #103: instrument lights shouldn't be functioning when master is off
Currently, ~~all lights (strobe, beacon, nav, landing and instrument lights)~~ ~~some lights (landing and instrument lights)~~ the instrument lights work even when the master is off.

### PR DESCRIPTION
**Pull request by onox**
Should fix #103. Please do `git checkout bug-103` to test this locally before giving a :+1:.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Hi onox, 

I did a `git checkout bug-103`, for which I get:

    Branch bug-103 set up to track remote branch bug-103 from origin.
    Switched to a new branch 'bug-103'
    
But then when I do a `git pull` I get `Already up-to-date.` Am I doing something wrong?

**Comment by gilbertohasnofb** [comment]
Ok, since just one file was modified, I copied and pasted the raw data and it solves half of the issue https://github.com/Juanvvc/c172p-detailed/issues/103 (the ALS landing lights and instrument lights still work when the master is off). Thanks a lot!

**Comment by onox** [comment]
I think you first need to do `git pull` (or do `git fetch`) and then do `git checkout bug-103` to switch your working copy to that branch. Then you just launch the c172p-detailed and test that the fix works. If it works, you write :+1: in a comment on Github and then you can then switch back to master with `git checkout master`.

Note that `git pull` is just a shorthand for `git fetch` to download the latest commits from Github, and then `git merge` to merge any commits from others with the commits in the repository on your local computer.

**Comment by gilbertohasnofb** [comment]
I see, thanks onox, next time I will try it that way. Anyway, as I wrote before I tested it and it seems to work perfectly well, so :+1:

**Comment by onox** [comment]
Okay :smile:

Btw, if you want to see which branches you have on your computer, you can type `git branch`. If you want to see which branches exist on Github, you do `git branch -a`.

If you then see, for example, `remotes/origin/bug-103`, you can forget the `remotes/origin/` part and just type `git checkout bug-103` to switch to `bug-103`.

**Comment by gilbertohasnofb** [comment]
Ok, makes perfectly sense! Thanks a lot onox, I am learning a lot from you all :smile:

**Pull request merged**
