### PR TITLE
Bug 441

### LINKED ISSUE #486: Baggage door closing sound must be delayed
Baggage door closing sound needs to be a bit more delayed, it's being played before the baggage door is closed!

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
This PR fixes #486 and #487, and contributes to #441 and #303.

It also brings three new dialogs: left and right fuel tank dialogs when clicking on the fuel caps in the exterior model, and baggage weight dialogue when opening baggage door.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox can you see what you think about this?

**Comment by onox** [comment]
@gilbertohasnofb Code looks good. Could you perhaps add the weight in pounds to the fuel tank dialogs?

One more thing: aren't "Float chamber1" and "Float chamber2" internal tanks in the Fuel and Payload Settings window? I think it's possible to hide them.

**Comment by gilbertohasnofb** [comment]
Great!

> Could you perhaps add the weight in pounds to the fuel tank dialogs?

Sure, I will do that still tonight.

> One more thing: aren't "Float chamber1" and "Float chamber2" internal tanks in the Fuel and Payload Settings window? I think it's possible to hide them.

Yes, they are still there and I think we should hide them (I don't know how though). But just to be clear, the main reason I created these new dialogues is to make the much smaller than the default Fuel and Payload, as well as simulating a kind of walk around the plane (to fill each tank, one has to click on each fuel cap, and you must add baggage separately than fuel).

**Comment by onox** [comment]
> as well as simulating a kind of walk around the plane

That's cool :smile:

**Comment by onox** [comment]
I'll look up how to hide these tanks.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by gilbertohasnofb** [comment]
Dialogs improved. But I seem to have done something wrong, what is this `Merge branch 'bug-441' of https://github.com/Juanvvc/c172p-detailed into bug-441` commit I did? Did I break anything? I had forgotten to do a `git pull` before trying to push the improvements to the dialogs.... sorry

**Comment by onox** [comment]
Because I added a commit as well.

**Comment by gilbertohasnofb** [comment]
Ok, I see.

**Comment by onox** [comment]
You can try to do:

```sh
git reset --hard e54bd0b98133085b78b8695515df261f402b6d96
git pull --rebase
```

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by onox** [comment]
Is your commit on top of mine?

**Comment by gilbertohasnofb** [comment]
Yep:

```
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git log --pretty=oneline
2f52158168d3ddfa386cd4bdf18bee922a893c3e Merge branch 'bug-441' of https://githu
e54bd0b98133085b78b8695515df261f402b6d96 improvements to the dialogs, adding fue
e5f057beea806d1a11ea00b2ee55364bf7ab5052 Hide internal float chamber tanks
```

**Comment by onox** [comment]
But your merge commit is still there.

**Comment by gilbertohasnofb** [comment]
Yes, it is still there on top of yours, that's what I meant.

**Comment by onox** [comment]
But the merge commit should disappear if you do `reset --hard` and `pull --rebase`.

**Comment by onox** [comment]
Oh wait, you already pushed of course.

**Comment by onox** [comment]
Can you do `git reset --hard e54bd0b98133085b78b8695515df261f402b6d96`?

**Comment by gilbertohasnofb** [comment]
Sure:

```
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git reset --hard e54bd0b98133085b78b8695515df261f402b6d96
HEAD is now at e54bd0b improvements to the dialogs, adding fuel weight in pounds
```

**Comment by gilbertohasnofb** [comment]
But my wrong commit is still being shown here in this PR.

**Comment by onox** [comment]
Ok, hang on. I'll force push.

**Comment by onox** [comment]
Ok now do: `git pull --rebase`.

**Comment by gilbertohasnofb** [comment]
Seems to have worked:

```
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git pull --rebase
From https://github.com/Juanvvc/c172p-detailed
 + 2f52158...e5f057b bug-441    -> origin/bug-441  (forced update)
First, rewinding head to replay your work on top of it...
Applying: improvements to the dialogs, adding fuel weight in pounds
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git log --pretty=oneline
3eea59dd3729fda4830d41853af24123b05949e0 improvements to the dialogs, adding fue
e5f057beea806d1a11ea00b2ee55364bf7ab5052 Hide internal float chamber tanks
b150b190c71a6b51d8a606541b7916756b656511 new dialogs for baggage and fuel tanks
```

**Comment by onox** [comment]
Ok, now do `git push --force`.

**Comment by gilbertohasnofb** [comment]
Okay, I think we are golden now :hand:

**Comment by onox** [comment]
:hand: :smile:

**Comment by onox** [comment]
Do you also want to fix #487?

**Comment by gilbertohasnofb** [comment]
Yes, I can do that myself.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by onox** [comment]
I'm not completely happy about #487, yellow lines look buggy :worried:

**Comment by gilbertohasnofb** [comment]
You mean the yellow lines that appear after hitting Ctrl+C? They don't look buggy to me, they have the mesh of the 3D model:

fgfs-screen-002

**Comment by onox** [comment]
Here they look grey sometimes.

**Comment by gilbertohasnofb** [comment]
Can you post an image so I can try to reproduce? Here they seem to look fine all the time. And is this affecting only the doors or all other yellow lines?

**Comment by onox** [comment]
fgfs-screen-281

**Comment by onox** [comment]
It's ok for me, I just won't press Ctrl+C then. Lets merge this PR?

**Comment by gilbertohasnofb** [comment]
Yeah, I don't see this problem at all. Okay, let's merge this and then I will continue working on #303 and #441 afterwards.

**Pull request merged**
